#######################################################################################
# WARNING: This file is written to by the build process, any manual edits will be lost!
#######################################################################################
sensor.roof_temperature:
  friendly_name: Roof
sensor.netatmo_ada_temperature:
  friendly_name: Ada
sensor.netatmo_edwin_temperature:
  friendly_name: Edwin
sensor.netatmo_parents_temperature:
  friendly_name: Parents
sensor.netatmo_bertram_2_office_temperature:
  friendly_name: Office
sensor.netatmo_bertram_2_kitchen_temperature:
  friendly_name: Kitchen
sensor.netatmo_bertram_2_office_pantry_temperature:
  friendly_name: Pantry
sensor.netatmo_bertram_2_office_lounge_temperature:
  friendly_name: Lounge
sensor.netatmo_bertram_2_office_dining_temperature:
  friendly_name: Dining
sensor.netatmo_laundry_temperature:
  friendly_name: Laundry
sensor.netatmo_bertram_2_office_basement_temperature:
  friendly_name: Basement
sensor.rack_temperature:
  friendly_name: Rack
sensor.roof_apparent_temperature:
  friendly_name: Roof Apparent
sensor.roof_dew_point:
  friendly_name: Roof Dew Point
sensor.roof_heat_index:
  friendly_name: Roof Heat Index
sensor.roof_humidity_index:
  friendly_name: Roof Humidity Index
sensor.rack_dew_point:
  friendly_name: Rack Dew Point
sensor.roof_wind_chill_temperature:
  friendly_name: Wind Chill
sensor.netatmo_ada_co2:
  friendly_name: Ada
  icon: mdi:molecule-co2
sensor.netatmo_edwin_co2:
  friendly_name: Edwin
  icon: mdi:molecule-co2
sensor.netatmo_parents_co2:
  friendly_name: Parents
  icon: mdi:molecule-co2
sensor.netatmo_bertram_2_office_co2:
  friendly_name: Office
  icon: mdi:molecule-co2
sensor.netatmo_bertram_2_kitchen_co2:
  friendly_name: Kitchen
  icon: mdi:molecule-co2
sensor.netatmo_bertram_2_office_pantry_co2:
  friendly_name: Pantry
  icon: mdi:molecule-co2
sensor.netatmo_bertram_2_office_lounge_co2:
  friendly_name: Lounge
  icon: mdi:molecule-co2
sensor.netatmo_bertram_2_office_dining_co2:
  friendly_name: Dining
  icon: mdi:molecule-co2
sensor.netatmo_laundry_co2:
  friendly_name: Laundry
  icon: mdi:molecule-co2
sensor.roof_humidity:
  friendly_name: Roof
sensor.netatmo_ada_humidity:
  friendly_name: Ada
sensor.netatmo_edwin_humidity:
  friendly_name: Edwin
sensor.netatmo_parents_humidity:
  friendly_name: Parents
sensor.netatmo_bertram_2_office_humidity:
  friendly_name: Office
sensor.netatmo_bertram_2_kitchen_humidity:
  friendly_name: Kitchen
sensor.netatmo_bertram_2_office_pantry_humidity:
  friendly_name: Pantry
sensor.netatmo_bertram_2_office_lounge_humidity:
  friendly_name: Lounge
sensor.netatmo_bertram_2_office_dining_humidity:
  friendly_name: Dining
sensor.netatmo_laundry_humidity:
  friendly_name: Laundry
sensor.netatmo_bertram_2_office_basement_humidity:
  friendly_name: Basement
sensor.rack_humidity:
  friendly_name: Rack
sensor.netatmo_ada_noise:
  friendly_name: Ada
sensor.netatmo_edwin_noise:
  friendly_name: Edwin
sensor.netatmo_parents_noise:
  friendly_name: Parents
sensor.netatmo_bertram_2_office_noise:
  friendly_name: Office
sensor.netatmo_bertram_2_kitchen_noise:
  friendly_name: Kitchen
sensor.netatmo_laundry_noise:
  friendly_name: Laundry
sensor.roof_cloud_base:
  friendly_name: Roof Cloud Base
  icon: mdi:cloud-outline
sensor.roof_max_solar_radiation:
  friendly_name: Roof Max Solar Radiation
  icon: mdi:solar-power
sensor.roof_barometer_pressure:
  friendly_name: Roof Barometer
sensor.roof_pressure:
  friendly_name: Roof
sensor.roof_wind_direction:
  friendly_name: Direction
  icon: mdi:weather-windy
sensor.roof_wind_gust_direction:
  friendly_name: Gust Direction
  icon: mdi:weather-windy
sensor.roof_wind_gust_speed:
  friendly_name: Gust Speed
  icon: mdi:weather-windy
sensor.roof_wind_speed_10min:
  friendly_name: Speed over 10m
  icon: mdi:weather-windy
sensor.roof_wind_samples:
  friendly_name: Samples
  icon: mdi:weather-windy
sensor.roof_wind_run:
  friendly_name: Run
  icon: mdi:weather-windy
sensor.roof_wind_speed:
  friendly_name: Speed
  icon: mdi:weather-windy
sensor.roof_rain_rate:
  friendly_name: Rate
  icon: mdi:weather-pouring
sensor.roof_hourly_rain:
  friendly_name: Hourly
  icon: mdi:weather-pouring
sensor.roof_daily_rain:
  friendly_name: Daily
  icon: mdi:weather-pouring
sensor.roof_24hour_rain:
  friendly_name: 24 Hour
  icon: mdi:weather-pouring
sensor.roof_monthly_rain:
  friendly_name: Monthly
  icon: mdi:weather-pouring
sensor.roof_yearly_rain:
  friendly_name: Yearly
  icon: mdi:weather-pouring
sensor.roof_rain:
  friendly_name: Total
  icon: mdi:weather-pouring
sensor.roof_storm_rain:
  friendly_name: Storm
  icon: mdi:weather-pouring
fan.ada:
  friendly_name: Ada
  icon: mdi:fan
fan.edwin:
  friendly_name: Edwin
  icon: mdi:fan
fan.parents:
  friendly_name: Parents
  icon: mdi:fan
switch.kitchen_fan:
  friendly_name: Kitchen
  icon: mdi:fan
fan.lounge:
  friendly_name: Lounge
  icon: mdi:fan
fan.deck_east:
  friendly_name: Deck East
  icon: mdi:fan
fan.deck_west:
  friendly_name: Deck West
  icon: mdi:fan
light.dining:
  friendly_name: Dining Main
light.ada_light:
  friendly_name: Ada Main
light.edwin_light:
  friendly_name: Edwin Main
light.lounge_light:
  friendly_name: Lounge Fan
light.hallway:
  friendly_name: Hallway Main
light.hue_color_candle_2:
  friendly_name: Hallway Main
light.hue_color_candle_3:
  friendly_name: Hallway Main
light.hue_color_candle_4:
  friendly_name: Hallway Main
light.hue_color_candle_5:
  friendly_name: Hallway Main
light.dining:
  friendly_name: Dining Main
light.hue_color_candle_6:
  friendly_name: Dining Main
light.hue_color_candle_7:
  friendly_name: Dining Main
light.hue_color_candle_8:
  friendly_name: Dining Main
light.hue_color_candle_9:
  friendly_name: Dining Main
light.hue_color_candle_10:
  friendly_name: Dining Main
light.hue_color_candle_11:
  friendly_name: Dining Main
light.lounge:
  friendly_name: Lounge Main
light.hue_color_candle_12:
  friendly_name: Lounge Main
light.hue_color_candle_13:
  friendly_name: Lounge Main
light.hue_color_candle_14:
  friendly_name: Lounge Main
light.parents:
  friendly_name: Parents Main
light.hue_color_candle_15:
  friendly_name: Parents Main
light.hue_color_candle_16:
  friendly_name: Parents Main
light.hue_color_candle_17:
  friendly_name: Parents Main
light.kitchen:
  friendly_name: Kitchen Main
light.hue_ambiance_lamp_1:
  friendly_name: Kitchen Main
light.hue_ambiance_lamp_2:
  friendly_name: Kitchen Main
light.hue_ambiance_lamp_3:
  friendly_name: Kitchen Main
light.hue_ambiance_lamp_12:
  friendly_name: Kitchen Main
light.laundry:
  friendly_name: Laundry Main
light.hue_ambiance_lamp_4:
  friendly_name: Laundry Main
light.pantry:
  friendly_name: Pantry Main
light.hue_ambiance_lamp_5:
  friendly_name: Pantry Main
light.office:
  friendly_name: Office Main
light.hue_ambiance_lamp_6:
  friendly_name: Office Main
light.bathroom:
  friendly_name: Bathroom Main
light.hue_ambiance_lamp_7:
  friendly_name: Bathroom Main
light.ensuite:
  friendly_name: Ensuite Main
light.hue_ambiance_lamp_8:
  friendly_name: Ensuite Main
light.wardrobe:
  friendly_name: Wardrobe Main
light.hue_ambiance_lamp_9:
  friendly_name: Wardrobe Main
light.edwin:
  friendly_name: Edwin Lamp
light.hue_ambiance_lamp_10:
  friendly_name: Edwin Lamp
light.ada:
  friendly_name: Ada Lamp
light.hue_ambiance_lamp_11:
  friendly_name: Ada Lamp
light.lamp:
  friendly_name: Lounge Lamp
light.hue_ambiance_lamp_13:
  friendly_name: Lounge Lamp
switch.kitchen_dish_washer:
  friendly_name: Dish Washer
  icon: mdi:dishwasher
switch.laundry_clothes_dryer:
  friendly_name: Clothes Dryer
  icon: mdi:tumble-dryer
switch.laundry_washing_machine:
  friendly_name: Washing Machine
  icon: mdi:washing-machine
switch.kitchen_coffee_machine:
  friendly_name: Coffee Machine
  icon: mdi:coffee-maker
switch.kitchen_fridge:
  friendly_name: Kitchen Fridge
  icon: mdi:fridge-outline
switch.deck_freezer:
  friendly_name: Deck Freezer
  icon: mdi:fridge-top
switch.deck_lights:
  friendly_name: Deck Lights
  icon: mdi:string-lights
switch.bathroom_rails:
  friendly_name: Bathroom Rails
  icon: mdi:radiator
switch.study_battery_charger:
  friendly_name: Battery Charger
  icon: mdi:battery-charging-30
switch.laundry_vacuum_charger:
  friendly_name: Vacuum Charger
  icon: mdi:battery-charging-30
switch.various_adhoc_outlet:
  friendly_name: Adhoc Outlet
  icon: mdi:power-plug-outline
switch.study_outlet:
  friendly_name: Study Outlet
  icon: mdi:power-plug-outline
switch.office_outlet:
  friendly_name: Office Outlet
  icon: mdi:power-plug-outline
switch.lounge_tv:
  friendly_name: Lounge TV
  icon: mdi:television
switch.rack_outlet:
  friendly_name: Server Rack
  icon: mdi:server
switch.roof_network_switch:
  friendly_name: Network Switch
  icon: mdi:server-network
switch.rack_internet_modem:
  friendly_name: Internet Modem
  icon: mdi:router-wireless
sensor.kitchen_dish_washer_current_consumption:
  friendly_name: Dish Washer
  icon: mdi:home-lightning-bolt
sensor.laundry_clothes_dryer_current_consumption:
  friendly_name: Clothes Dryer
  icon: mdi:home-lightning-bolt
sensor.laundry_washing_machine_current_consumption:
  friendly_name: Washing Machine
  icon: mdi:home-lightning-bolt
sensor.kitchen_coffee_machine_current_consumption:
  friendly_name: Coffee Machine
  icon: mdi:home-lightning-bolt
sensor.kitchen_fan_current_consumption:
  friendly_name: Kitchen Fan
  icon: mdi:home-lightning-bolt
sensor.kitchen_fridge_current_consumption:
  friendly_name: Kitchen Fridge
  icon: mdi:home-lightning-bolt
sensor.deck_freezer_current_consumption:
  friendly_name: Deck Freezer
  icon: mdi:home-lightning-bolt
sensor.deck_lights_current_consumption:
  friendly_name: Deck Lights
  icon: mdi:home-lightning-bolt
sensor.lounge_tv_current_consumption:
  friendly_name: Lounge TV
  icon: mdi:home-lightning-bolt
sensor.bathroom_rails_current_consumption:
  friendly_name: Bathroom Rails
  icon: mdi:home-lightning-bolt
sensor.study_outlet_current_consumption:
  friendly_name: Study Outlet
  icon: mdi:home-lightning-bolt
sensor.office_outlet_current_consumption:
  friendly_name: Office Outlet
  icon: mdi:home-lightning-bolt
sensor.rack_outlet_current_consumption:
  friendly_name: Server Rack
  icon: mdi:home-lightning-bolt
sensor.roof_network_switch_current_consumption:
  friendly_name: Network Switch
  icon: mdi:home-lightning-bolt
sensor.rack_internet_modem_current_consumption:
  friendly_name: Internet Modem
  icon: mdi:home-lightning-bolt
sensor.study_battery_charger_current_consumption:
  friendly_name: Battery Charger
  icon: mdi:home-lightning-bolt
sensor.laundry_vacuum_charger_current_consumption:
  friendly_name: Vacuum Charger
  icon: mdi:home-lightning-bolt
sensor.various_adhoc_outlet_current_consumption:
  friendly_name: Adhoc Outlet
  icon: mdi:home-lightning-bolt
sensor.kitchen_dish_washer_today_s_consumption:
  friendly_name: Dish Washer
  icon: mdi:battery-charging
sensor.laundry_clothes_dryer_today_s_consumption:
  friendly_name: Clothes Dryer
  icon: mdi:battery-charging
sensor.laundry_washing_machine_today_s_consumption:
  friendly_name: Washing Machine
  icon: mdi:battery-charging
sensor.kitchen_coffee_machine_today_s_consumption:
  friendly_name: Coffee Machine
  icon: mdi:battery-charging
sensor.kitchen_fan_today_s_consumption:
  friendly_name: Kitchen Fan
  icon: mdi:battery-charging
sensor.kitchen_fridge_today_s_consumption:
  friendly_name: Kitchen Fridge
  icon: mdi:battery-charging
sensor.deck_freezer_today_s_consumption:
  friendly_name: Deck Freezer
  icon: mdi:battery-charging
sensor.deck_lights_today_s_consumption:
  friendly_name: Deck Lights
  icon: mdi:battery-charging
sensor.lounge_tv_today_s_consumption:
  friendly_name: Lounge TV
  icon: mdi:battery-charging
sensor.bathroom_rails_today_s_consumption:
  friendly_name: Bathroom Rails
  icon: mdi:battery-charging
sensor.study_outlet_today_s_consumption:
  friendly_name: Study Outlet
  icon: mdi:battery-charging
sensor.office_outlet_today_s_consumption:
  friendly_name: Office Outlet
  icon: mdi:battery-charging
sensor.rack_outlet_today_s_consumption:
  friendly_name: Server Rack
  icon: mdi:battery-charging
sensor.roof_network_switch_today_s_consumption:
  friendly_name: Network Switch
  icon: mdi:battery-charging
sensor.rack_internet_modem_today_s_consumption:
  friendly_name: Internet Modem
  icon: mdi:battery-charging
sensor.study_battery_charger_today_s_consumption:
  friendly_name: Battery Charger
  icon: mdi:battery-charging
sensor.laundry_vacuum_charger_today_s_consumption:
  friendly_name: Vacuum Charger
  icon: mdi:battery-charging
sensor.various_adhoc_outlet_today_s_consumption:
  friendly_name: Adhoc Outlet
  icon: mdi:battery-charging
