sensor.roof_temperature:
  friendly_name: Roof
sensor.ada_temperature:
  friendly_name: Ada
sensor.basement_temperature:
  friendly_name: Basement
sensor.dining_temperature:
  friendly_name: Dining
sensor.edwin_temperature:
  friendly_name: Edwin
sensor.kitchen_temperature:
  friendly_name: Kitchen
sensor.laundry_temperature:
  friendly_name: Laundry
sensor.lounge_temperature:
  friendly_name: Lounge
sensor.office_temperature:
  friendly_name: Office
sensor.pantry_temperature:
  friendly_name: Pantry
sensor.parents_temperature:
  friendly_name: Parents
sensor.rack_temperature:
  friendly_name: Rack
sensor.dining_carbon_dioxide:
  friendly_name: Dining
sensor.edwin_carbon_dioxide:
  friendly_name: Edwin
sensor.kitchen_carbon_dioxide:
  friendly_name: Kitchen
sensor.lounge_carbon_dioxide:
  friendly_name: Lounge
sensor.office_carbon_dioxide:
  friendly_name: Office
sensor.pantry_carbon_dioxide:
  friendly_name: Pantry
sensor.parents_carbon_dioxide:
  friendly_name: Parents
sensor.roof_humidity:
  friendly_name: Roof
sensor.ada_humidity:
  friendly_name: Ada
sensor.basement_humidity:
  friendly_name: Basement
sensor.dining_humidity:
  friendly_name: Dining
sensor.edwin_humidity:
  friendly_name: Edwin
sensor.kitchen_humidity:
  friendly_name: Kitchen
sensor.laundry_humidity:
  friendly_name: Laundry
sensor.lounge_humidity:
  friendly_name: Lounge
sensor.office_humidity:
  friendly_name: Office
sensor.pantry_humidity:
  friendly_name: Pantry
sensor.parents_humidity:
  friendly_name: Parents
sensor.rack_humidity:
  friendly_name: Rack
sensor.ada_noise:
  friendly_name: Ada
sensor.edwin_noise:
  friendly_name: Edwin
sensor.kitchen_noise:
  friendly_name: Kitchen
sensor.laundry_noise:
  friendly_name: Laundry
sensor.office_noise:
  friendly_name: Office
sensor.parents_noise:
  friendly_name: Parents
sensor.last_30_min_rain:
  friendly_name: Last 30 Min
sensor.various_adhoc_power_consumption:
  friendly_name: Various Adhoc
sensor.rack_modem_power_consumption:
  friendly_name: Rack Modem
sensor.rack_power_power_consumption:
  friendly_name: Rack Power
sensor.roof_switch_power_consumption:
  friendly_name: Roof Switch
sensor.kitchen_fan_power_consumption:
  friendly_name: Kitchen Fan
sensor.kitchen_fridge_power_consumption:
  friendly_name: Kitchen Fridge
sensor.kitchen_coffee_power_consumption:
  friendly_name: Kitchen Coffee
sensor.deck_freezer_power_consumption:
  friendly_name: Deck Freezer
sensor.deck_festoons_power_consumption:
  friendly_name: Deck Festoons
sensor.office_power_power_consumption:
  friendly_name: Office Power
sensor.lounge_tv_power_consumption:
  friendly_name: Lounge Tv
sensor.study_power_power_consumption:
  friendly_name: Study Power
sensor.bathroom_towelrails_power_consumption:
  friendly_name: Bathroom Towelrails
sensor.various_adhoc_energy_consumption:
  friendly_name: Various Adhoc
sensor.rack_modem_energy_consumption:
  friendly_name: Rack Modem
sensor.rack_power_energy_consumption:
  friendly_name: Rack Power
sensor.roof_switch_energy_consumption:
  friendly_name: Roof Switch
sensor.kitchen_fan_energy_consumption:
  friendly_name: Kitchen Fan
sensor.kitchen_fridge_energy_consumption:
  friendly_name: Kitchen Fridge
sensor.kitchen_coffee_energy_consumption:
  friendly_name: Kitchen Coffee
sensor.deck_freezer_energy_consumption:
  friendly_name: Deck Freezer
sensor.deck_festoons_energy_consumption:
  friendly_name: Deck Festoons
sensor.lounge_tv_energy_consumption:
  friendly_name: Lounge Tv
sensor.study_power_energy_consumption:
  friendly_name: Study Power
sensor.office_power_energy_consumption:
  friendly_name: Office Power
sensor.bathroom_towelrails_energy_consumption:
  friendly_name: Bathroom Towelrails
