#######################################################################################
# WARNING: This file is written to by the build process, any manual edits will be lost!
#######################################################################################

#######################################################################################
# Temperature
#######################################################################################
sensor.roof_temperature:
  friendly_name: Roof
sensor.netatmo_ada_temperature:
  friendly_name: Ada
sensor.netatmo_edwin_temperature:
  friendly_name: Edwin
sensor.netatmo_parents_temperature:
  friendly_name: Parents
sensor.netatmo_bertram_2_office_temperature:
  friendly_name: Office
sensor.netatmo_bertram_2_kitchen_temperature:
  friendly_name: Kitchen
sensor.netatmo_bertram_2_office_pantry_temperature:
  friendly_name: Pantry
sensor.netatmo_bertram_2_office_lounge_temperature:
  friendly_name: Lounge
sensor.netatmo_bertram_2_office_dining_temperature:
  friendly_name: Dining
sensor.netatmo_laundry_temperature:
  friendly_name: Laundry
sensor.netatmo_bertram_2_office_basement_temperature:
  friendly_name: Basement
sensor.rack_temperature:
  friendly_name: Rack
sensor.roof_apparent_temperature:
  friendly_name: Roof Apparent
sensor.roof_dew_point:
  friendly_name: Roof Dew Point
sensor.roof_heat_index:
  friendly_name: Roof Heat Index
sensor.roof_humidity_index:
  friendly_name: Roof Humidity Index
sensor.rack_dew_point:
  friendly_name: Rack Dew Point
sensor.roof_wind_chill_temperature:
  friendly_name: Wind Chill

#######################################################################################
# Carbon Dioxide
#######################################################################################
sensor.netatmo_ada_co2:
  friendly_name: Ada
sensor.netatmo_edwin_co2:
  friendly_name: Edwin
sensor.netatmo_parents_co2:
  friendly_name: Parents
sensor.netatmo_bertram_2_office_co2:
  friendly_name: Office
sensor.netatmo_bertram_2_kitchen_co2:
  friendly_name: Kitchen
sensor.netatmo_bertram_2_office_pantry_co2:
  friendly_name: Pantry
sensor.netatmo_bertram_2_office_lounge_co2:
  friendly_name: Lounge
sensor.netatmo_bertram_2_office_dining_co2:
  friendly_name: Dining
sensor.netatmo_laundry_co2:
  friendly_name: Laundry

#######################################################################################
# Humidity
#######################################################################################
sensor.roof_humidity:
  friendly_name: Roof
sensor.netatmo_ada_humidity:
  friendly_name: Ada
sensor.netatmo_edwin_humidity:
  friendly_name: Edwin
sensor.netatmo_parents_humidity:
  friendly_name: Parents
sensor.netatmo_bertram_2_office_humidity:
  friendly_name: Office
sensor.netatmo_bertram_2_kitchen_humidity:
  friendly_name: Kitchen
sensor.netatmo_bertram_2_office_pantry_humidity:
  friendly_name: Pantry
sensor.netatmo_bertram_2_office_lounge_humidity:
  friendly_name: Lounge
sensor.netatmo_bertram_2_office_dining_humidity:
  friendly_name: Dining
sensor.netatmo_laundry_humidity:
  friendly_name: Laundry
sensor.netatmo_bertram_2_office_basement_humidity:
  friendly_name: Basement
sensor.rack_humidity:
  friendly_name: Rack

#######################################################################################
# Noise
#######################################################################################
sensor.netatmo_ada_noise:
  friendly_name: Ada
sensor.netatmo_edwin_noise:
  friendly_name: Edwin
sensor.netatmo_parents_noise:
  friendly_name: Parents
sensor.netatmo_bertram_2_office_noise:
  friendly_name: Office
sensor.netatmo_bertram_2_kitchen_noise:
  friendly_name: Kitchen
sensor.netatmo_laundry_noise:
  friendly_name: Laundry

#######################################################################################
# Irradiance
#######################################################################################
sensor.roof_cloud_base:
  friendly_name: Roof Cloud Base
sensor.roof_max_solar_radiation:
  friendly_name: Roof Max Solar Radiation

#######################################################################################
# Pressure
#######################################################################################
sensor.roof_barometer_pressure:
  friendly_name: Roof Barometer
sensor.roof_pressure:
  friendly_name: Roof

#######################################################################################
# Wind
#######################################################################################
sensor.roof_wind_direction:
  friendly_name: Direction
sensor.roof_wind_gust_direction:
  friendly_name: Gust Direction
sensor.roof_wind_gust_speed:
  friendly_name: Gust Speed
sensor.roof_wind_speed_10min:
  friendly_name: Speed over 10m
sensor.roof_wind_samples:
  friendly_name: Samples
sensor.roof_wind_run:
  friendly_name: Run
sensor.roof_wind_speed:
  friendly_name: Speed

#######################################################################################
# Rain
#######################################################################################
sensor.roof_rain_rate:
  friendly_name: Rate
sensor.roof_hourly_rain:
  friendly_name: Hourly
sensor.roof_daily_rain:
  friendly_name: Daily
sensor.roof_24hour_rain:
  friendly_name: 24 Hour
sensor.roof_monthly_rain:
  friendly_name: Monthly
sensor.roof_yearly_rain:
  friendly_name: Yearly
sensor.roof_rain:
  friendly_name: Total
sensor.roof_storm_rain:
  friendly_name: Storm
