sensor.roof_temperature:
  friendly_name: Roof
sensor.ada_temperature:
  friendly_name: Ada
sensor.basement_temperature:
  friendly_name: Basement
sensor.dining_temperature:
  friendly_name: Dining
sensor.edwin_temperature:
  friendly_name: Edwin
sensor.kitchen_temperature:
  friendly_name: Kitchen
sensor.laundry_temperature:
  friendly_name: Laundry
sensor.lounge_temperature:
  friendly_name: Lounge
sensor.office_temperature:
  friendly_name: Office
sensor.pantry_temperature:
  friendly_name: Pantry
sensor.parents_temperature:
  friendly_name: Parents
sensor.rack_temperature:
  friendly_name: Rack
sensor.dining_carbon_dioxide:
  friendly_name: Dining
sensor.edwin_carbon_dioxide:
  friendly_name: Edwin
sensor.kitchen_carbon_dioxide:
  friendly_name: Kitchen
sensor.lounge_carbon_dioxide:
  friendly_name: Lounge
sensor.office_carbon_dioxide:
  friendly_name: Office
sensor.pantry_carbon_dioxide:
  friendly_name: Pantry
sensor.parents_carbon_dioxide:
  friendly_name: Parents
sensor.ada_noise:
  friendly_name: Ada
sensor.edwin_noise:
  friendly_name: Edwin
sensor.kitchen_noise:
  friendly_name: Kitchen
sensor.laundry_noise:
  friendly_name: Laundry
sensor.office_noise:
  friendly_name: Office
sensor.parents_noise:
  friendly_name: Parents
sensor.roof_humidity:
  friendly_name: Roof
sensor.ada_humidity:
  friendly_name: Ada
sensor.basement_humidity:
  friendly_name: Basement
sensor.dining_humidity:
  friendly_name: Dining
sensor.edwin_humidity:
  friendly_name: Edwin
sensor.kitchen_humidity:
  friendly_name: Kitchen
sensor.laundry_humidity:
  friendly_name: Laundry
sensor.lounge_humidity:
  friendly_name: Lounge
sensor.office_humidity:
  friendly_name: Office
sensor.pantry_humidity:
  friendly_name: Pantry
sensor.parents_humidity:
  friendly_name: Parents
sensor.rack_humidity:
  friendly_name: Rack
sensor.last_30_min_rain:
  friendly_name: Last 30 Min
sensor.fridge_power_consumption:
  friendly_name: Fridge
sensor.servers_power_consumption:
  friendly_name: Servers
sensor.kitchenfan_power_consumption:
  friendly_name: Kitchenfan
sensor.towelrails_power_consumption:
  friendly_name: Towelrails
sensor.fridge_energy_consumption:
  friendly_name: Fridge
sensor.servers_energy_consumption:
  friendly_name: Servers
sensor.kitchenfan_energy_consumption:
  friendly_name: Kitchenfan
sensor.towelrails_energy_consumption:
  friendly_name: Towelrails
