#######################################################################################
# WARNING: This file is written to by the build process, any manual edits will be lost!
#######################################################################################
input_boolean.home_movie:
  name: Home Movie
  aliases: ['Home Movie Mode', 'Movie', 'Movie Mode']
  room: Home
input_boolean.home_sleep:
  name: Home Sleep
  aliases: ['Home Sleep Mode', 'Sleep', 'Sleep Mode']
  room: Home
input_boolean.home_wakeup:
  name: Home Wakeup
  aliases: ['Home Wakeup Mode', 'Wakeup', 'Wakeup Mode']
  room: Home
input_boolean.home_reset:
  name: Home Reset
  aliases: ['Home Reset Mode', 'Reset', 'Reset Mode']
  room: Home
switch.bathroom_rails:
  name: Bathroom Towel Rails
  aliases: ['Towel Rails']
  room: Bathroom
switch.roof_water_heater_booster:
  name: Roof Water Booster
  aliases: ['Water Booster']
  room: Roof
fan.ada_fan:
  name: Ada Fan
  aliases: ['Fan']
  room: Ada
fan.edwin_fan:
  name: Edwin Fan
  aliases: ['Fan']
  room: Edwin
fan.parents_fan:
  name: Parents Fan
  aliases: ['Fan']
  room: Parents
switch.kitchen_fan:
  name: Kitchen Fan
  aliases: ['Fan']
  room: Kitchen
fan.lounge_fan:
  name: Lounge Fan
  aliases: ['Fan']
  room: Lounge
fan.deck_fan:
  name: Deck Fans
  aliases: ['Fans']
  room: Deck
fan.lounge_air_purifier:
  name: Lounge Air Purifier
  aliases: ['Air Purifier']
  room: Lounge
light.ada_fan:
  name: Ada Main
  aliases: ['Main']
  room: Ada
light.edwin_fan:
  name: Edwin Main
  aliases: ['Main']
  room: Edwin
light.lounge_fan:
  name: Lounge Fan
  aliases: ['Fan']
  room: Lounge
#######################################################################################
