title: Home
views:

  - path: default_view
    title: Weather
    cards: !include ui-lovelace/weather.yaml

  - path: control
    title: Control
    cards: !include ui-lovelace/control.yaml

  - path: media
    title: Media
    cards: !include ui-lovelace/media.yaml

  - path: cameras
    title: Cameras
    cards: !include ui-lovelace/cameras.yaml

  - path: monitor
    title: Monitor
    cards: !include ui-lovelace/monitor.yaml
