draft: false
acme:
  email_account: graham.gear@gmail.com
  staging: ${LETSENCRYPT_STAGING}
profiles:
  - name: cloudflare_profile
    provider: cloudflare
    provider_options:
      auth_username: graham.gear@gmail.com
      auth_token: ${CLOUDFLARE_TOKEN}
certificates:
  - domains:
      - janeandgraham.com
      - "*.janeandgraham.com"
      - "*.local.janeandgraham.com"
    profile: cloudflare_profile
    deploy_hook: '/bin/bash -c "[[ -f /etc/letsencrypt/live/janeandgraham.com/privkey.pem ]] && touch /etc/letsencrypt/live/janeandgraham.com/privkey.pem"'