permit_join: false
frontend:
  port: $ZIGBEE2MQTT_HTTP_PORT
  url: 'http://$ZIGBEE2MQTT_SERVICE:$ZIGBEE2MQTT_HTTP_PORT'
mqtt:
  version: 5
  base_topic: zigbee
  server: 'mqtt://$VERNEMQ_SERVICE:$VERNEMQ_PORT'
homeassistant:
  discovery_topic: 'homeassistant'
  status_topic: 'homeassistant/status'
  legacy_entity_attributes: false
  legacy_triggers: true
availability:
  active:
    timeout: 10
  passive:
    timeout: 1500
device_options:
  retain: true
  qos: 1
  debounce: 0.5
  optimistic: true
devices: devices.yaml
groups: groups.yaml
serial:
  port: /dev/ttyACM0
advanced:
  channel: 11
  adapter_delay: 200
  last_seen: ISO_8601_local
  legacy_availability_payload: false
  log_level: error
