#######################################################################################
# WARNING: This file is written to by the build process, any manual edits will be lost!
#######################################################################################
'100':
  friendly_name: 'Ada Lamp'
  retain: true
  transition: 1
  optimistic: true
  off_state: 'all_members_off'
'101':
  friendly_name: 'Edwin Lamp'
  retain: true
  transition: 1
  optimistic: true
  off_state: 'all_members_off'
'102':
  friendly_name: 'Edwin Night Light'
  retain: true
  transition: 1
  optimistic: true
  off_state: 'all_members_off'
'103':
  friendly_name: 'Hallway Main'
  retain: true
  transition: 1
  optimistic: true
  off_state: 'all_members_off'
'120':
  friendly_name: 'Hallway Sconces'
  retain: true
  transition: 1
  optimistic: true
  off_state: 'all_members_off'
'104':
  friendly_name: 'Dining Main'
  retain: true
  transition: 1
  optimistic: true
  off_state: 'all_members_off'
'105':
  friendly_name: 'Lounge Main'
  retain: true
  transition: 1
  optimistic: true
  off_state: 'all_members_off'
'114':
  friendly_name: 'Lounge Lamp'
  retain: true
  transition: 1
  optimistic: true
  off_state: 'all_members_off'
'106':
  friendly_name: 'Parents Main'
  retain: true
  transition: 1
  optimistic: true
  off_state: 'all_members_off'
'119':
  friendly_name: 'Parents Sconces'
  retain: true
  transition: 1
  optimistic: true
  off_state: 'all_members_off'
'117':
  friendly_name: 'Study Lamp'
  retain: true
  transition: 1
  optimistic: true
  off_state: 'all_members_off'
'107':
  friendly_name: 'Kitchen Main'
  retain: true
  transition: 1
  optimistic: true
  off_state: 'all_members_off'
'108':
  friendly_name: 'Laundry Main'
  retain: true
  transition: 1
  optimistic: true
  off_state: 'all_members_off'
'109':
  friendly_name: 'Pantry Main'
  retain: true
  transition: 1
  optimistic: true
  off_state: 'all_members_off'
'110':
  friendly_name: 'Office Main'
  retain: true
  transition: 1
  optimistic: true
  off_state: 'all_members_off'
'111':
  friendly_name: 'Bathroom Main'
  retain: true
  transition: 1
  optimistic: true
  off_state: 'all_members_off'
'121':
  friendly_name: 'Bathroom Sconces'
  retain: true
  transition: 1
  optimistic: true
  off_state: 'all_members_off'
'112':
  friendly_name: 'Ensuite Main'
  retain: true
  transition: 1
  optimistic: true
  off_state: 'all_members_off'
'118':
  friendly_name: 'Ensuite Sconces'
  retain: true
  transition: 1
  optimistic: true
  off_state: 'all_members_off'
'113':
  friendly_name: 'Wardrobe Main'
  retain: true
  transition: 1
  optimistic: true
  off_state: 'all_members_off'
'115':
  friendly_name: 'Garden Pedestals'
  retain: true
  transition: 4
  optimistic: true
  off_state: 'all_members_off'
'116':
  friendly_name: 'Tree Spotlights'
  retain: true
  transition: 4
  optimistic: true
  off_state: 'all_members_off'
