#!/bin/sh
#######################################################################################
# WARNING: This file is written to by the build process, any manual edits will be lost!
#######################################################################################
while [ $(mosquitto_sub -h ${VERNEMQ_IP} -p ${VERNEMQ_PORT} -t 'zigbee/bridge/state' -W 1 2>/dev/null | grep online | wc -l) -ne 1 ]; do :; done
mosquitto_pub -h $VERNEMQ_IP -p $VERNEMQ_PORT -t 'zigbee/Ada Lamp Bulb 1/set' -m '{ "hue_power_on_behavior": "on", "hue_power_on_brightness": 3, "hue_power_on_color_temperature": 500, "color_temp_startup": 500 }' && echo 'Published to [zigbee/Ada Lamp Bulb 1/set] config { "hue_power_on_behavior": "on", "hue_power_on_brightness": 3, "hue_power_on_color_temperature": 500, "color_temp_startup": 500 }' && sleep 1
mosquitto_pub -h $VERNEMQ_IP -p $VERNEMQ_PORT -t 'zigbee/Edwin Lamp Bulb 1/set' -m '{ "hue_power_on_behavior": "on", "hue_power_on_brightness": 254, "hue_power_on_color_temperature": 65535, "color_temp_startup": 65535 }' && echo 'Published to [zigbee/Edwin Lamp Bulb 1/set] config { "hue_power_on_behavior": "on", "hue_power_on_brightness": 254, "hue_power_on_color_temperature": 65535, "color_temp_startup": 65535 }' && sleep 1
mosquitto_pub -h $VERNEMQ_IP -p $VERNEMQ_PORT -t 'zigbee/Edwin Night Light Bulb 1/set' -m '{ "hue_power_on_behavior": "on", "hue_power_on_brightness": 3, "hue_power_on_color_temperature": 500, "color_temp_startup": 500 }' && echo 'Published to [zigbee/Edwin Night Light Bulb 1/set] config { "hue_power_on_behavior": "on", "hue_power_on_brightness": 3, "hue_power_on_color_temperature": 500, "color_temp_startup": 500 }' && sleep 1
mosquitto_pub -h $VERNEMQ_IP -p $VERNEMQ_PORT -t 'zigbee/Hallway Main Bulb 1/set' -m '{ "hue_power_on_behavior": "on", "hue_power_on_brightness": 3, "hue_power_on_color_temperature": 65535, "color_temp_startup": 65535 }' && echo 'Published to [zigbee/Hallway Main Bulb 1/set] config { "hue_power_on_behavior": "on", "hue_power_on_brightness": 3, "hue_power_on_color_temperature": 65535, "color_temp_startup": 65535 }' && sleep 1
mosquitto_pub -h $VERNEMQ_IP -p $VERNEMQ_PORT -t 'zigbee/Hallway Main Bulb 2/set' -m '{ "hue_power_on_behavior": "on", "hue_power_on_brightness": 3, "hue_power_on_color_temperature": 65535, "color_temp_startup": 65535 }' && echo 'Published to [zigbee/Hallway Main Bulb 2/set] config { "hue_power_on_behavior": "on", "hue_power_on_brightness": 3, "hue_power_on_color_temperature": 65535, "color_temp_startup": 65535 }' && sleep 1
mosquitto_pub -h $VERNEMQ_IP -p $VERNEMQ_PORT -t 'zigbee/Hallway Main Bulb 3/set' -m '{ "hue_power_on_behavior": "on", "hue_power_on_brightness": 3, "hue_power_on_color_temperature": 65535, "color_temp_startup": 65535 }' && echo 'Published to [zigbee/Hallway Main Bulb 3/set] config { "hue_power_on_behavior": "on", "hue_power_on_brightness": 3, "hue_power_on_color_temperature": 65535, "color_temp_startup": 65535 }' && sleep 1
mosquitto_pub -h $VERNEMQ_IP -p $VERNEMQ_PORT -t 'zigbee/Hallway Main Bulb 4/set' -m '{ "hue_power_on_behavior": "on", "hue_power_on_brightness": 3, "hue_power_on_color_temperature": 65535, "color_temp_startup": 65535 }' && echo 'Published to [zigbee/Hallway Main Bulb 4/set] config { "hue_power_on_behavior": "on", "hue_power_on_brightness": 3, "hue_power_on_color_temperature": 65535, "color_temp_startup": 65535 }' && sleep 1
mosquitto_pub -h $VERNEMQ_IP -p $VERNEMQ_PORT -t 'zigbee/Dining Main Bulb 1/set' -m '{ "hue_power_on_behavior": "on", "hue_power_on_brightness": 254, "hue_power_on_color_temperature": 65535, "color_temp_startup": 65535 }' && echo 'Published to [zigbee/Dining Main Bulb 1/set] config { "hue_power_on_behavior": "on", "hue_power_on_brightness": 254, "hue_power_on_color_temperature": 65535, "color_temp_startup": 65535 }' && sleep 1
mosquitto_pub -h $VERNEMQ_IP -p $VERNEMQ_PORT -t 'zigbee/Dining Main Bulb 2/set' -m '{ "hue_power_on_behavior": "on", "hue_power_on_brightness": 254, "hue_power_on_color_temperature": 65535, "color_temp_startup": 65535 }' && echo 'Published to [zigbee/Dining Main Bulb 2/set] config { "hue_power_on_behavior": "on", "hue_power_on_brightness": 254, "hue_power_on_color_temperature": 65535, "color_temp_startup": 65535 }' && sleep 1
mosquitto_pub -h $VERNEMQ_IP -p $VERNEMQ_PORT -t 'zigbee/Dining Main Bulb 3/set' -m '{ "hue_power_on_behavior": "on", "hue_power_on_brightness": 254, "hue_power_on_color_temperature": 65535, "color_temp_startup": 65535 }' && echo 'Published to [zigbee/Dining Main Bulb 3/set] config { "hue_power_on_behavior": "on", "hue_power_on_brightness": 254, "hue_power_on_color_temperature": 65535, "color_temp_startup": 65535 }' && sleep 1
mosquitto_pub -h $VERNEMQ_IP -p $VERNEMQ_PORT -t 'zigbee/Dining Main Bulb 4/set' -m '{ "hue_power_on_behavior": "on", "hue_power_on_brightness": 254, "hue_power_on_color_temperature": 65535, "color_temp_startup": 65535 }' && echo 'Published to [zigbee/Dining Main Bulb 4/set] config { "hue_power_on_behavior": "on", "hue_power_on_brightness": 254, "hue_power_on_color_temperature": 65535, "color_temp_startup": 65535 }' && sleep 1
mosquitto_pub -h $VERNEMQ_IP -p $VERNEMQ_PORT -t 'zigbee/Dining Main Bulb 5/set' -m '{ "hue_power_on_behavior": "on", "hue_power_on_brightness": 254, "hue_power_on_color_temperature": 65535, "color_temp_startup": 65535 }' && echo 'Published to [zigbee/Dining Main Bulb 5/set] config { "hue_power_on_behavior": "on", "hue_power_on_brightness": 254, "hue_power_on_color_temperature": 65535, "color_temp_startup": 65535 }' && sleep 1
mosquitto_pub -h $VERNEMQ_IP -p $VERNEMQ_PORT -t 'zigbee/Dining Main Bulb 6/set' -m '{ "hue_power_on_behavior": "on", "hue_power_on_brightness": 254, "hue_power_on_color_temperature": 65535, "color_temp_startup": 65535 }' && echo 'Published to [zigbee/Dining Main Bulb 6/set] config { "hue_power_on_behavior": "on", "hue_power_on_brightness": 254, "hue_power_on_color_temperature": 65535, "color_temp_startup": 65535 }' && sleep 1
mosquitto_pub -h $VERNEMQ_IP -p $VERNEMQ_PORT -t 'zigbee/Lounge Main Bulb 1/set' -m '{ "hue_power_on_behavior": "on", "hue_power_on_brightness": 254, "hue_power_on_color_temperature": 65535, "color_temp_startup": 65535 }' && echo 'Published to [zigbee/Lounge Main Bulb 1/set] config { "hue_power_on_behavior": "on", "hue_power_on_brightness": 254, "hue_power_on_color_temperature": 65535, "color_temp_startup": 65535 }' && sleep 1
mosquitto_pub -h $VERNEMQ_IP -p $VERNEMQ_PORT -t 'zigbee/Lounge Main Bulb 2/set' -m '{ "hue_power_on_behavior": "on", "hue_power_on_brightness": 254, "hue_power_on_color_temperature": 65535, "color_temp_startup": 65535 }' && echo 'Published to [zigbee/Lounge Main Bulb 2/set] config { "hue_power_on_behavior": "on", "hue_power_on_brightness": 254, "hue_power_on_color_temperature": 65535, "color_temp_startup": 65535 }' && sleep 1
mosquitto_pub -h $VERNEMQ_IP -p $VERNEMQ_PORT -t 'zigbee/Lounge Main Bulb 3/set' -m '{ "hue_power_on_behavior": "on", "hue_power_on_brightness": 254, "hue_power_on_color_temperature": 65535, "color_temp_startup": 65535 }' && echo 'Published to [zigbee/Lounge Main Bulb 3/set] config { "hue_power_on_behavior": "on", "hue_power_on_brightness": 254, "hue_power_on_color_temperature": 65535, "color_temp_startup": 65535 }' && sleep 1
mosquitto_pub -h $VERNEMQ_IP -p $VERNEMQ_PORT -t 'zigbee/Lounge Lamp Bulb 1/set' -m '{ "hue_power_on_behavior": "on", "hue_power_on_brightness": 3, "hue_power_on_color_temperature": 500, "color_temp_startup": 500 }' && echo 'Published to [zigbee/Lounge Lamp Bulb 1/set] config { "hue_power_on_behavior": "on", "hue_power_on_brightness": 3, "hue_power_on_color_temperature": 500, "color_temp_startup": 500 }' && sleep 1
mosquitto_pub -h $VERNEMQ_IP -p $VERNEMQ_PORT -t 'zigbee/Parents Main Bulb 1/set' -m '{ "hue_power_on_behavior": "on", "hue_power_on_brightness": 3, "hue_power_on_color_temperature": 65535, "color_temp_startup": 65535 }' && echo 'Published to [zigbee/Parents Main Bulb 1/set] config { "hue_power_on_behavior": "on", "hue_power_on_brightness": 3, "hue_power_on_color_temperature": 65535, "color_temp_startup": 65535 }' && sleep 1
mosquitto_pub -h $VERNEMQ_IP -p $VERNEMQ_PORT -t 'zigbee/Parents Main Bulb 2/set' -m '{ "hue_power_on_behavior": "on", "hue_power_on_brightness": 3, "hue_power_on_color_temperature": 65535, "color_temp_startup": 65535 }' && echo 'Published to [zigbee/Parents Main Bulb 2/set] config { "hue_power_on_behavior": "on", "hue_power_on_brightness": 3, "hue_power_on_color_temperature": 65535, "color_temp_startup": 65535 }' && sleep 1
mosquitto_pub -h $VERNEMQ_IP -p $VERNEMQ_PORT -t 'zigbee/Parents Main Bulb 3/set' -m '{ "hue_power_on_behavior": "on", "hue_power_on_brightness": 3, "hue_power_on_color_temperature": 65535, "color_temp_startup": 65535 }' && echo 'Published to [zigbee/Parents Main Bulb 3/set] config { "hue_power_on_behavior": "on", "hue_power_on_brightness": 3, "hue_power_on_color_temperature": 65535, "color_temp_startup": 65535 }' && sleep 1
mosquitto_pub -h $VERNEMQ_IP -p $VERNEMQ_PORT -t 'zigbee/Study Lamp Bulb 1/set' -m '{ "hue_power_on_behavior": "on", "hue_power_on_brightness": 3, "hue_power_on_color_temperature": 500, "color_temp_startup": 500 }' && echo 'Published to [zigbee/Study Lamp Bulb 1/set] config { "hue_power_on_behavior": "on", "hue_power_on_brightness": 3, "hue_power_on_color_temperature": 500, "color_temp_startup": 500 }' && sleep 1
mosquitto_pub -h $VERNEMQ_IP -p $VERNEMQ_PORT -t 'zigbee/Kitchen Main Bulb 1/set' -m '{ "hue_power_on_behavior": "on", "hue_power_on_brightness": 254, "hue_power_on_color_temperature": 65535, "color_temp_startup": 65535 }' && echo 'Published to [zigbee/Kitchen Main Bulb 1/set] config { "hue_power_on_behavior": "on", "hue_power_on_brightness": 254, "hue_power_on_color_temperature": 65535, "color_temp_startup": 65535 }' && sleep 1
mosquitto_pub -h $VERNEMQ_IP -p $VERNEMQ_PORT -t 'zigbee/Kitchen Main Bulb 2/set' -m '{ "hue_power_on_behavior": "on", "hue_power_on_brightness": 254, "hue_power_on_color_temperature": 65535, "color_temp_startup": 65535 }' && echo 'Published to [zigbee/Kitchen Main Bulb 2/set] config { "hue_power_on_behavior": "on", "hue_power_on_brightness": 254, "hue_power_on_color_temperature": 65535, "color_temp_startup": 65535 }' && sleep 1
mosquitto_pub -h $VERNEMQ_IP -p $VERNEMQ_PORT -t 'zigbee/Kitchen Main Bulb 3/set' -m '{ "hue_power_on_behavior": "on", "hue_power_on_brightness": 254, "hue_power_on_color_temperature": 65535, "color_temp_startup": 65535 }' && echo 'Published to [zigbee/Kitchen Main Bulb 3/set] config { "hue_power_on_behavior": "on", "hue_power_on_brightness": 254, "hue_power_on_color_temperature": 65535, "color_temp_startup": 65535 }' && sleep 1
mosquitto_pub -h $VERNEMQ_IP -p $VERNEMQ_PORT -t 'zigbee/Kitchen Main Bulb 4/set' -m '{ "hue_power_on_behavior": "on", "hue_power_on_brightness": 254, "hue_power_on_color_temperature": 65535, "color_temp_startup": 65535 }' && echo 'Published to [zigbee/Kitchen Main Bulb 4/set] config { "hue_power_on_behavior": "on", "hue_power_on_brightness": 254, "hue_power_on_color_temperature": 65535, "color_temp_startup": 65535 }' && sleep 1
mosquitto_pub -h $VERNEMQ_IP -p $VERNEMQ_PORT -t 'zigbee/Laundry Main Bulb 1/set' -m '{ "hue_power_on_behavior": "on", "hue_power_on_brightness": 254, "hue_power_on_color_temperature": 65535, "color_temp_startup": 65535 }' && echo 'Published to [zigbee/Laundry Main Bulb 1/set] config { "hue_power_on_behavior": "on", "hue_power_on_brightness": 254, "hue_power_on_color_temperature": 65535, "color_temp_startup": 65535 }' && sleep 1
mosquitto_pub -h $VERNEMQ_IP -p $VERNEMQ_PORT -t 'zigbee/Pantry Main Bulb 1/set' -m '{ "hue_power_on_behavior": "on", "hue_power_on_brightness": 254, "hue_power_on_color_temperature": 65535, "color_temp_startup": 65535 }' && echo 'Published to [zigbee/Pantry Main Bulb 1/set] config { "hue_power_on_behavior": "on", "hue_power_on_brightness": 254, "hue_power_on_color_temperature": 65535, "color_temp_startup": 65535 }' && sleep 1
mosquitto_pub -h $VERNEMQ_IP -p $VERNEMQ_PORT -t 'zigbee/Office Main Bulb 1/set' -m '{ "hue_power_on_behavior": "on", "hue_power_on_brightness": 254, "hue_power_on_color_temperature": 250, "color_temp_startup": 250 }' && echo 'Published to [zigbee/Office Main Bulb 1/set] config { "hue_power_on_behavior": "on", "hue_power_on_brightness": 254, "hue_power_on_color_temperature": 250, "color_temp_startup": 250 }' && sleep 1
mosquitto_pub -h $VERNEMQ_IP -p $VERNEMQ_PORT -t 'zigbee/Bathroom Main Bulb 1/set' -m '{ "hue_power_on_behavior": "on", "hue_power_on_brightness": 3, "hue_power_on_color_temperature": 65535, "color_temp_startup": 65535 }' && echo 'Published to [zigbee/Bathroom Main Bulb 1/set] config { "hue_power_on_behavior": "on", "hue_power_on_brightness": 3, "hue_power_on_color_temperature": 65535, "color_temp_startup": 65535 }' && sleep 1
mosquitto_pub -h $VERNEMQ_IP -p $VERNEMQ_PORT -t 'zigbee/Ensuite Main Bulb 1/set' -m '{ "hue_power_on_behavior": "on", "hue_power_on_brightness": 3, "hue_power_on_color_temperature": 65535, "color_temp_startup": 65535 }' && echo 'Published to [zigbee/Ensuite Main Bulb 1/set] config { "hue_power_on_behavior": "on", "hue_power_on_brightness": 3, "hue_power_on_color_temperature": 65535, "color_temp_startup": 65535 }' && sleep 1
mosquitto_pub -h $VERNEMQ_IP -p $VERNEMQ_PORT -t 'zigbee/Wardrobe Main Bulb 1/set' -m '{ "hue_power_on_behavior": "on", "hue_power_on_brightness": 3, "hue_power_on_color_temperature": 65535, "color_temp_startup": 65535 }' && echo 'Published to [zigbee/Wardrobe Main Bulb 1/set] config { "hue_power_on_behavior": "on", "hue_power_on_brightness": 3, "hue_power_on_color_temperature": 65535, "color_temp_startup": 65535 }' && sleep 1
mosquitto_pub -h $VERNEMQ_IP -p $VERNEMQ_PORT -t 'zigbee/Garden Pedestals Bulb 1/set' -m '{ "hue_power_on_behavior": "off" }' && echo 'Published to [zigbee/Garden Pedestals Bulb 1/set] config { "hue_power_on_behavior": "off" }' && sleep 1
mosquitto_pub -h $VERNEMQ_IP -p $VERNEMQ_PORT -t 'zigbee/Garden Pedestals Bulb 2/set' -m '{ "hue_power_on_behavior": "off" }' && echo 'Published to [zigbee/Garden Pedestals Bulb 2/set] config { "hue_power_on_behavior": "off" }' && sleep 1
mosquitto_pub -h $VERNEMQ_IP -p $VERNEMQ_PORT -t 'zigbee/Garden Pedestals Bulb 3/set' -m '{ "hue_power_on_behavior": "off" }' && echo 'Published to [zigbee/Garden Pedestals Bulb 3/set] config { "hue_power_on_behavior": "off" }' && sleep 1
mosquitto_pub -h $VERNEMQ_IP -p $VERNEMQ_PORT -t 'zigbee/Garden Pedestals Bulb 4/set' -m '{ "hue_power_on_behavior": "off" }' && echo 'Published to [zigbee/Garden Pedestals Bulb 4/set] config { "hue_power_on_behavior": "off" }' && sleep 1
mosquitto_pub -h $VERNEMQ_IP -p $VERNEMQ_PORT -t 'zigbee/Tree Spotlights Bulb 1/set' -m '{ "hue_power_on_behavior": "off" }' && echo 'Published to [zigbee/Tree Spotlights Bulb 1/set] config { "hue_power_on_behavior": "off" }' && sleep 1
mosquitto_pub -h $VERNEMQ_IP -p $VERNEMQ_PORT -t 'zigbee/Tree Spotlights Bulb 2/set' -m '{ "hue_power_on_behavior": "off" }' && echo 'Published to [zigbee/Tree Spotlights Bulb 2/set] config { "hue_power_on_behavior": "off" }' && sleep 1
