version: '3.7'
services:
  postgres:
    container_name: postgres
    image: postgres:12.5-alpine
    init: true
    restart: ${RESTART}
    environment:
      - TZ=Australia/Perth
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_KEY}
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ${DATA_DIR}:/var/lib/postgresql/data
    ports:
      - 5432:5432
    deploy:
      resources:
        limits:
          memory: 4G