version: '3.7'
services:
  postgres:
    container_name: postgres
    image: postgres:12.4
    init: true
    restart: ${RESTART}
    environment:
      - TZ=Australia/Perth
      - POSTGRES_USER=asystem
      - POSTGRES_PASSWORD=Asystem1980!
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ${DATA_DIR}:/var/lib/postgresql/data
    ports:
      - 5432:5432
