x-common: &common
  image: influxdb3:${SERVICE_VERSION_ABSOLUTE}
  init: true
  environment:
    - TZ=Australia/Perth
    - INFLUXDB3_SERVICE
    - INFLUXDB3_API_PORT
    - INFLUXDB3_HOST_URL=http://${INFLUXDB3_SERVICE}:${INFLUXDB3_API_PORT}
    - INFLUXDB3_AUTH_TOKEN=${INFLUXDB3_TOKEN_ADMIN}
    - INFLUXDB3_TOKEN_ADMIN
    - INFLUXDB3_TOKEN_PUBLIC
    - INFLUXDB3_TOKEN_PRIVATE
    - INFLUXDB3_DATABASE_HOME_PUBLIC
    - INFLUXDB3_DATABASE_HOME_PRIVATE
    - INFLUXDB3_DATABASE_DATA_PUBLIC
    - INFLUXDB3_DATABASE_HOST_PRIVATE
    - INFLUXDB3_HTTP_BIND_ADDR=0.0.0.0:8181
    - INFLUXDB3_OBJECT_STORE=file
    - INFLUXDB3_DB_DIR=/asystem/mnt
    - INFLUXDB3_NODE_IDENTIFIER_PREFIX=node_1
    - INFLUXDB3_ENTERPRISE_CLUSTER_ID=cluster_1
    - INFLUXDB3_ENTERPRISE_COMPACTOR_ID=compactor_1
    - INFLUXDB3_ENTERPRISE_COMPACTION_GEN2_DURATION=2h
    - INFLUXDB3_ENTERPRISE_COMPACTION_MULTIPLIERS=3,5,8,13,21,34,55
    - INFLUXDB3_ENTERPRISE_COMPACTION_MAX_NUM_FILES_PER_PLAN=10000
    - INFLUXDB3_ENTERPRISE_LICENSE_TYPE=home
    - INFLUXDB3_ENTERPRISE_LICENSE_EMAIL=${INFLUXDB3_EMAIL}
    - INFLUXDB3_PERMISSION_TOKENS_FILE=/asystem/mnt/cluster_1/init.json
    - INFLUXDB3_TELEMETRY_DISABLE_UPLOAD=true
    - LOG_FILTER=info
  volumes:
    - ${SERVICE_DATA_DIR}:/asystem/mnt
  logging:
    driver: "json-file"
    options:
      max-file: "5"
      max-size: "100m"
services:
  influxdb3:
    container_name: influxdb3
    <<: *common
    restart: ${SERVICE_RESTART}
    ports:
      - ${INFLUXDB3_API_PORT}:8181
    healthcheck:
      test: /asystem/etc/checkready.sh
      interval: 2m
      timeout: 10s
      retries: 3
      start_period: 1m
      start_interval: 10s
    deploy:
      resources:
        limits:
          memory: 5G
  influxdb3_bootstrap:
    container_name: influxdb3_bootstrap
    <<: *common
    restart: 'no'
    entrypoint: bash
    command: /asystem/etc/bootstrap.sh
    depends_on:
      - influxdb3
