x-common: &common
  image: sonarr:${SERVICE_VERSION_ABSOLUTE}
  init: true
  environment:
    - TZ=Australia/Perth
    - PUID=0
    - PGID=0
    - SONARR_SERVICE_PROD
    - SONARR_HTTP_PORT
    - SONARR_API_KEY
    - SONARR_URL
    - SABNZBD_SERVICE_PROD
    - SABNZBD_HTTP_PORT
    - SABNZBD_API_KEY
    - SABNZBD_SHARE_DIR
    - GEEK_KEY
  volumes:
    - ${SERVICE_DATA_DIR}:/root/.config/Sonarr
    - ${SABNZBD_SHARE_DIR}:/tv
    - ${SABNZBD_SHARE_DIR}:/downloads
    - ${PLEX_SHARE_DIR}:${PLEX_SHARE_DIR}
  logging:
    driver: "json-file"
    options:
      max-file: "5"
      max-size: "100m"
services:
  sonarr:
    container_name: sonarr
    <<: *common
    restart: ${SERVICE_RESTART}
    ports:
      - ${SONARR_HTTP_PORT}:8989
    healthcheck:
      test: /asystem/etc/checkready.sh
      interval: 2m
      timeout: 10s
      retries: 3
      start_period: 1m
      start_interval: 10s
    deploy:
      resources:
        limits:
          memory: 512M
  sonarr_bootstrap:
    container_name: sonarr_bootstrap
    <<: *common
    restart: 'no'
    entrypoint: bash
    command: /asystem/etc/bootstrap.sh
    depends_on:
      - sonarr