x-common: &common
  image: sonarr:${SERVICE_VERSION_ABSOLUTE}
  init: true
  environment:
    - TZ=Australia/Perth
    - PUID=0
    - PGID=0
    - SONARR_SERVICE_PROD
    - SONARR_HTTP_PORT
    - SONARR_API_KEY
    - SABNZBD_SERVICE_PROD
    - SABNZBD_HTTP_PORT
    - SABNZBD_API_KEY
    - GEEK_KEY
  volumes:
    - ${SERVICE_DATA_DIR}:/config
    - ${SERVICE_DATA_DIR}/downloads:/tv
    - ${SERVICE_DATA_DIR}/downloads:/downloads
  logging:
    driver: "json-file"
    options:
      max-file: "5"
      max-size: "100m"
services:
  sonarr:
    container_name: sonarr
    <<: *common
    restart: ${SERVICE_RESTART}
    ports:
      - ${SONARR_HTTP_PORT}:8989
    healthcheck:
      test: /asystem/etc/checkready.sh
      interval: 2m
      timeout: 10s
      retries: 3
      start_period: 1m
      start_interval: 10s
    deploy:
      resources:
        limits:
          memory: 512M
  sonarr_bootstrap:
    container_name: sonarr_bootstrap
    <<: *common
    image: bash:5.2
    restart: 'no'
    volumes:
      - ${SERVICE_DATA_DIR}/bootstrap.sh:/asystem/etc/bootstrap.sh
    command:
      - /asystem/etc/bootstrap.sh
    depends_on:
      - sonarr