#default_config:
config:
logbook:
history:

frontend:
  themes: !include_dir_merge_named themes

#hacs:
#  token: 257aa3791d1689796ea269a01946d710e4160201
#  theme: true
#  python_script: true

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

tts:
  - platform: google_translate

#netatmo:
#  api_key: 58366a1ca467a330048cfb3b
#  secret_key: qccbuGbMJdFnw2la68MFs7TrGtYtgA3aK
#  username: graham.gear@gmail.com
#  password: 122Bubbles
#  discovery: true

weather:
  - platform: darksky_m
    api_key: fd02f0c75b26923e31ccc08e5b7e1022
    units: si
    mode: daily

homeassistant:
  customize: !include customize.yaml
  customize_glob: !include customize_glob.yaml

recorder:
  db_url: postgresql://postgres:docker@localhost/haas
  purge_keep_days: 1
  purge_interval: 1
#  exclude:
#    domains:
#      - sensor

influxdb:
  database: home_assistant
  ssl: false
  verify_ssl: false
  max_retries: 3
  default_measurement: state
  tags:
    instance: production
    source: home_assistant
  include:
    domains:
      - sensor

mqtt:
  broker: 192.168.2.5
  port: 1883
  client_id: 'hass'
  discovery: true
  discovery_prefix: 'haas/sensor/config'
  birth_message:
    topic: 'hass/status'
    payload: 'online'
  will_message:
    topic: 'hass/status'
    payload: 'offline'

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

logger:
  default: warning
  logs:
    homeassistant.components.mqtt: warning

