cname=zigbee2mqtt.proxy.janeandgraham.com,macmini-meg
cname=zigbee2mqtt,zigbee2mqtt.local.janeandgraham.com,raspbpi-jen
cname=weewx.proxy.janeandgraham.com,macmini-meg
cname=weewx,weewx.local.janeandgraham.com,raspbpi-jen
cname=udmutilities,udmutilities.local.janeandgraham.com,udm-dar
cname=photos,photos.local.janeandgraham.com,macbook-rue
cname=storage,storage.local.janeandgraham.com,udm-dar
cname=supervisor,supervisor.local.janeandgraham.com,udm-dar
cname=media,media.local.janeandgraham.com,udm-dar
cname=homeassistant.proxy.janeandgraham.com,macmini-meg
cname=homeassistant,homeassistant.local.janeandgraham.com,macmini-meg
cname=mariadb,mariadb.local.janeandgraham.com,macmini-meg
cname=vernemq.proxy.janeandgraham.com,macmini-meg
cname=vernemq,vernemq.local.janeandgraham.com,macmini-meg
cname=tasmota.proxy.janeandgraham.com,macmini-meg
cname=tasmota,tasmota.local.janeandgraham.com,macmini-meg
cname=nginx.proxy.janeandgraham.com,macmini-meg
cname=nginx,nginx.local.janeandgraham.com,macmini-meg
cname=openra,openra.local.janeandgraham.com,macmini-max
cname=mlflow.proxy.janeandgraham.com,macmini-meg
cname=mlflow,mlflow.local.janeandgraham.com,macmini-max
cname=mlserver.proxy.janeandgraham.com,macmini-meg
cname=mlserver,mlserver.local.janeandgraham.com,macmini-max
cname=influxdb3,influxdb3.local.janeandgraham.com,macmini-max
cname=network,network.local.janeandgraham.com,macmini-mad
cname=sabnzbd.proxy.janeandgraham.com,macmini-meg
cname=sabnzbd,sabnzbd.local.janeandgraham.com,macmini-mad
cname=wrangle.proxy.janeandgraham.com,macmini-meg
cname=prices.data.janeandgraham.com,macmini-meg
cname=wrangle,wrangle.local.janeandgraham.com,macmini-mad
cname=postgres,postgres.local.janeandgraham.com,macmini-mad
cname=plex.proxy.janeandgraham.com,macmini-meg
cname=plex,plex.local.janeandgraham.com,macmini-mad
cname=tempstat,tempstat.local.janeandgraham.com,macmini-may
cname=letsencrypt,letsencrypt.local.janeandgraham.com,macmini-may
cname=cloudflare,cloudflare.local.janeandgraham.com,macmini-may
cname=grafana.proxy.janeandgraham.com,macmini-meg
cname=grafana,grafana.local.janeandgraham.com,macmini-may
cname=sonarr.proxy.janeandgraham.com,macmini-meg
cname=sonarr,sonarr.local.janeandgraham.com,macmini-may
