permit_join: false
frontend:
  port: $ZIGBEE2MQTT_PORT
  url: 'http://$ZIGBEE2MQTT_IP:$ZIGBEE2MQTT_PORT'
mqtt:
  base_topic: zigbee
  server: 'mqtt://$VERNEMQ_IP:$VERNEMQ_PORT'
homeassistant:
  discovery_topic: 'haas/entity'
  status_topic: 'haas/status'
  legacy_entity_attributes: false
  legacy_triggers: true
availability:
  active:
    timeout: 10
  passive:
    timeout: 1500
device_options:
  retain: true
  qos: 1
  debounce: 0.5
  optimistic: true
devices: devices.yaml
groups: groups.yaml
serial:
  port: /dev/ttyACM0
advanced:
  channel: 11
  last_seen: ISO_8601_local
  log_level: warn
