APP_VERSION = "10.100.1000-SNAPSHOT" if "$" in "$SERVICE_VERSION_ABSOLUTE" else "$SERVICE_VERSION_ABSOLUTE"
APP_VERSION_COMPACT = 0 if "$" in "$SERVICE_VERSION_ABSOLUTE" else int("$SERVICE_VERSION_COMPACT")
APP_VERSION_NUMERIC = 101001000 if "$" in "$SERVICE_VERSION_ABSOLUTE" else int("$SERVICE_VERSION_NUMERIC")

# TODO: Swap model versions to use above versions, there is only one version, if the model changes it will be published with above
APP_MODEL_VERSION = "1001"
APP_MODEL_ENERGYFORECAST_INTERDAY_PROD_VERSION = "1006"
APP_MODEL_ENERGYFORECAST_INTRADAY_PROD_VERSION = "1003"
APP_MODEL_ENERGYFORECAST_INTERDAY_BUILD_VERSION = "1007"
APP_MODEL_ENERGYFORECAST_INTRADAY_BUILD_VERSION = "1003"
