version: '3.7'
services:
  unifipoller:
    container_name: unifipoller
    image: golift/unifi-poller:2.0.1
    init: true
    restart: ${RESTART}
    environment:
      - TZ=Australia/Perth
      - UNFI_USER
      - UNFI_PASSWORD
      - INFLUXDB_HOST
      - INFLUXDB_PORT
      - INFLUXDB_USER
      - INFLUXDB_TOKEN
    volumes:
      - ${DATA_DIR}:/config
