version: '3.7'
services:
  grafana:
    container_name: unifipoller
    image: golift/unifi-poller:2.0.1
    init: true
    restart: ${RESTART}
    environment:
      - TZ=Australia/Perth
    volumes:
      - ${DATA_DIR}:/config
    # ports:
    #   - 3000:3000
