x-common: &common
  image: appdaemon:${SERVICE_VERSION_ABSOLUTE}
  init: true
  environment:
    - TZ=Australia/Perth
    - APPDAEMON_SERVICE
    - APPDAEMON_HTTP_PORT
    - APPDAEMON_TOKEN
  volumes:
    - ${SERVICE_DATA_DIR}:/conf
  logging:
    driver: "json-file"
    options:
      max-file: "5"
      max-size: "100m"
services:
  appdaemon:
    container_name: appdaemon
    <<: *common
    restart: ${SERVICE_RESTART}
    ports:
      - ${APPDAEMON_HTTP_PORT}:${APPDAEMON_HTTP_PORT}
    healthcheck:
      test: /asystem/etc/healthcheck.sh
      interval: 2m
      timeout: 10s
      retries: 3
      start_period: 1m
      start_interval: 10s
    deploy:
      resources:
        limits:
          memory: 2G
  appdaemon_bootstrap:
    container_name: appdaemon_bootstrap
    <<: *common
    restart: 'no'
    entrypoint: /bin/bash
    command:
      - /asystem/etc/bootstrap.sh
    depends_on:
      - appdaemon