services:
  cloudflare:
    # NOTES: https://github.com/cloudflare/cloudflared/releases
    image: cloudflare:${SERVICE_VERSION_ABSOLUTE}
    container_name: cloudflare
    init: true
    environment:
      - CLOUDFLARE_METRICS_PORT
      - CLOUDFLARE_HOSTNAME
    command: tunnel --no-autoupdate --config /asystem/etc/config.yml --metrics 0.0.0.0:${CLOUDFLARE_METRICS_PORT} run
    restart: ${SERVICE_RESTART}
    volumes:
      - ${SERVICE_DATA_DIR}/config.yml:/asystem/etc/config.yml
      - ${SERVICE_DATA_DIR}/.credentials.json:/asystem/etc/.credentials.json
      - ${SERVICE_DATA_DIR}/checkalive.sh:/asystem/etc/checkalive.sh
      - ${SERVICE_DATA_DIR}/checkexecuting.sh:/asystem/etc/checkexecuting.sh
      - ${SERVICE_DATA_DIR}/checkhealthy.sh:/asystem/etc/checkhealthy.sh
    working_dir: /asystem/etc
    healthcheck:
      test: /asystem/etc/checkhealthy.sh
      interval: 2m
      timeout: 30s
      retries: 3
      start_period: 1m
      start_interval: 10s
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "100m"
    deploy:
      resources:
        limits:
          memory: 256M
