version: '3.7'
services:
  homeassistant:
    container_name: homeassistant
    image: homeassistant/home-assistant:0.116.4
    init: true
    restart: ${RESTART}
    environment:
      - TZ=Australia/Perth
      - POSTGRES_URL
      - VERNEMQ_HOST
      - VERNEMQ_PORT
      - INFLUXDB_TOKEN
    volumes:
      - ${DATA_DIR}:/config
    network_mode: host
    deploy:
      resources:
        limits:
          memory: 5G