version: '3.7'
services:
  homeassistant:
    container_name: homeassistant
    image: homeassistant/home-assistant:0.115.0
    init: true
    restart: ${RESTART}
    environment:
      - TZ=Australia/Perth
      - DB_URL
      - MQTT_HOST
      - MQTT_PORT
      - INFLUXDB_TOKEN
    volumes:
      - ${DATA_DIR}:/config
    network_mode: host
