x-common: &common
  image: tempstat:${SERVICE_VERSION_ABSOLUTE}
  init: true
  environment:
    - TZ=Australia/Perth
    - TEMPSTAT_HOST
    - TEMPSTAT_MOCK
    - TEMPSTAT_MOCK_ADAPTER
    - TEMPSTAT_POLL_PERIOD
    - TEMPSTAT_LOG_LEVEL
    - SERVICE_VERSION_ABSOLUTE
    - BROKER_HOST
    - BROKER_PORT
    - BROKER_TOKEN
  volumes:
    - ${SERVICE_DATA_DIR}:/asystem/mnt
  devices:
    - ${TEMPSTAT_DEVICE_MAP}
  logging:
    driver: "json-file"
    options:
      max-file: "5"
      max-size: "100m"
services:
  tempstat:
    container_name: tempstat
    <<: *common
    restart: ${SERVICE_RESTART}
    healthcheck:
      test: /asystem/etc/checkhealthy.sh
      interval: 2m
      timeout: 30s
      retries: 3
      start_period: 1m
      start_interval: 10s
    deploy:
      resources:
        limits:
          memory: 16M
