version: '3.7'
services:
  zookeeper:
    container_name: zookeeper
    image: confluentinc/cp-zookeeper:6.0.0
    init: true
    restart: ${SERVICE_RESTART}
    environment:
      - TZ=Australia/Perth
      - ZOOKEEPER_CLIENT_PORT=2181
      - ZOOKEEPER_TICK_TIME=2000
    ports:
      - ${ZOOKEEPER_PORT}:${ZOOKEEPER_PORT}
    deploy:
      resources:
        limits:
          memory: 5G