version: '3.7'
services:
  network:
    container_name: network
    image: network:${SERVICE_VERSION_ABSOLUTE}
    init: true
    restart: ${SERVICE_RESTART}
    environment:
      - TZ=Australia/Perth
    volumes:
      - ${SERVICE_DATA_DIR}:/data
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "100m"
    deploy:
      resources:
        limits:
          memory: 5G