draft: true
acme:
  email_account: graham.gear@gmail.com
  staging: true
profiles:
- name: namecheap_profile
  provider: namecheap
  provider_options:
    auth_token: ${USER}
    auth_username: ${PASSWD}
    auth_client_ip: ${IP}
    auth_sandbox: true
certificates:
- domains:
  - "*.janeandgraham.com"
  - janeandgraham.com
  profile: namecheap_profile
  deploy_hook: python /home/user/local_deploy.py