- type: entities
  title: Lights
  entities:
    - light.ada
    - light.ada_light
    - light.bathroom
    - light.dining
    - light.edwin
    - light.edwin_light
    - light.ensuite
    - light.hallway
    - light.kitchen
    - light.laundry
    - light.lounge
    - light.lounge_light
    - light.office
    - light.pantry
    - light.parents
    - light.wardrobe

- type: entities
  title: Fans
  entities:
    - fan.ada
    - fan.edwin
    - fan.lounge

- type: entities
  title: Switches
  entities:
    - switch.office
    - switch.towelrails
