- type: custom:mini-graph-card
  name: Temperature
  font_size_header: 19
  aggregate_func: max
  hours_to_show: 24
  points_per_hour: 6
  line_width: 2
  tap_action: none
  show_state: true
  show_indicator: true
  show:
    extrema: true
    fill: false
  entities:
    - sensor.ada_temperature
    - sensor.basement_temperature
    - sensor.deck_temperature
    - sensor.dining_temperature
    - sensor.edwin_temperature
    - sensor.kitchen_temperature
    - sensor.laundry_temperature
    - sensor.lounge_temperature
    - sensor.office_temperature
    - sensor.pantry_temperature
    - sensor.parents_temperature
- type: entities
  show_header_toggle: false
  entities:
    - entity: sensor.ada_temperature
    - entity: sensor.basement_temperature
    - entity: sensor.deck_temperature
    - entity: sensor.dining_temperature
    - entity: sensor.edwin_temperature
    - entity: sensor.kitchen_temperature
    - entity: sensor.laundry_temperature
    - entity: sensor.lounge_temperature
    - entity: sensor.office_temperature
    - entity: sensor.pantry_temperature
    - entity: sensor.parents_temperature
- type: custom:mini-graph-card
  name: Carbon Dioxide
  font_size_header: 19
  aggregate_func: max
  hours_to_show: 24
  points_per_hour: 6
  line_width: 2
  tap_action: none
  show_state: true
  show_indicator: true
  show:
    extrema: true
    fill: false
  entities:
    - sensor.ada_carbon_dioxide
    - sensor.dining_carbon_dioxide
    - sensor.edwin_carbon_dioxide
    - sensor.kitchen_carbon_dioxide
    - sensor.laundry_carbon_dioxide
    - sensor.lounge_carbon_dioxide
    - sensor.office_carbon_dioxide
    - sensor.pantry_carbon_dioxide
    - sensor.parents_carbon_dioxide
- type: entities
  show_header_toggle: false
  entities:
    - entity: sensor.ada_carbon_dioxide
    - entity: sensor.dining_carbon_dioxide
    - entity: sensor.edwin_carbon_dioxide
    - entity: sensor.kitchen_carbon_dioxide
    - entity: sensor.laundry_carbon_dioxide
    - entity: sensor.lounge_carbon_dioxide
    - entity: sensor.office_carbon_dioxide
    - entity: sensor.pantry_carbon_dioxide
    - entity: sensor.parents_carbon_dioxide
- type: custom:mini-graph-card
  name: Noise
  font_size_header: 19
  aggregate_func: max
  hours_to_show: 24
  points_per_hour: 6
  line_width: 2
  tap_action: none
  show_state: true
  show_indicator: true
  show:
    extrema: true
    fill: false
  entities:
    - sensor.ada_noise
    - sensor.edwin_noise
    - sensor.kitchen_noise
    - sensor.laundry_noise
    - sensor.office_noise
    - sensor.parents_noise
- type: entities
  show_header_toggle: false
  entities:
    - entity: sensor.ada_noise
    - entity: sensor.edwin_noise
    - entity: sensor.kitchen_noise
    - entity: sensor.laundry_noise
    - entity: sensor.office_noise
    - entity: sensor.parents_noise
- type: custom:mini-graph-card
  name: Power Consumption
  font_size_header: 19
  aggregate_func: max
  hours_to_show: 24
  points_per_hour: 6
  line_width: 2
  tap_action: none
  show_state: true
  show_indicator: true
  show:
    extrema: true
    fill: false
  entities:
    - sensor.servers_power_consumption
    - sensor.office_power_consumption
    - sensor.towelrails_power_consumption
- type: entities
  show_header_toggle: false
  entities:
    - entity: sensor.servers_power_consumption
    - entity: sensor.office_power_consumption
    - entity: sensor.towelrails_power_consumption
