- type: custom:bom-weather-card
  title: Perth Weather Detailed
  entity_current_conditions: sensor.bom_perth_icon_0
  entity_temperature: sensor.bom_perth_air_temp_c
  entity_forecast_high_temp_1: sensor.bom_perth_max_temp_c_1
  entity_forecast_high_temp_2: sensor.bom_perth_max_temp_c_2
  entity_forecast_high_temp_3: sensor.bom_perth_max_temp_c_3
  entity_forecast_high_temp_4: sensor.bom_perth_max_temp_c_4
  entity_forecast_high_temp_5: sensor.bom_perth_max_temp_c_5
  entity_forecast_icon_1: sensor.bom_perth_icon_1
  entity_forecast_icon_2: sensor.bom_perth_icon_2
  entity_forecast_icon_3: sensor.bom_perth_icon_3
  entity_forecast_icon_4: sensor.bom_perth_icon_4
  entity_forecast_icon_5: sensor.bom_perth_icon_5
  entity_forecast_low_temp_1: sensor.bom_perth_min_temp_c_1
  entity_forecast_low_temp_2: sensor.bom_perth_min_temp_c_2
  entity_forecast_low_temp_3: sensor.bom_perth_min_temp_c_3
  entity_forecast_low_temp_4: sensor.bom_perth_min_temp_c_4
  entity_forecast_low_temp_5: sensor.bom_perth_min_temp_c_5
  entity_summary_1: sensor.bom_perth_summary_1
  entity_summary_2: sensor.bom_perth_summary_2
  entity_summary_3: sensor.bom_perth_summary_3
  entity_summary_4: sensor.bom_perth_summary_4
  entity_summary_5: sensor.bom_perth_summary_5
  entity_sun: sun.sun
  entity_daytime_high: sensor.bom_today_max
  entity_daytime_low: sensor.bom_today_min
  entity_wind_bearing: sensor.bom_perth_wind_direction
  entity_wind_speed: sensor.bom_perth_wind_speed_kmh
  entity_wind_gust: sensor.bom_perth_wind_gust_kmh
  entity_wind_speed_kt: sensor.bom_perth_wind_speed_kt
  entity_wind_gust_kt: sensor.bom_perth_wind_gust_kt
  entity_humidity: sensor.bom_perth_relative_humidity
  entity_apparent_temp: sensor.bom_perth_feels_like_c
  entity_daily_summary: sensor.bom_today_detailed_summary
  entity_pop: sensor.bom_perth_chance_of_rain_0
  entity_pop_intensity: sensor.bom_perth_possible_rainfall_0
  entity_possible_today: sensor.bom_perth_possible_rainfall_0
  entity_pos_1: sensor.bom_perth_possible_rainfall_1
  entity_pos_2: sensor.bom_perth_possible_rainfall_2
  entity_pos_3: sensor.bom_perth_possible_rainfall_3
  entity_pos_4: sensor.bom_perth_possible_rainfall_4
  entity_pos_5: sensor.bom_perth_possible_rainfall_5
  entity_pop_1: sensor.bom_perth_chance_of_rain_1
  entity_pop_2: sensor.bom_perth_chance_of_rain_2
  entity_pop_3: sensor.bom_perth_chance_of_rain_3
  entity_pop_4: sensor.bom_perth_chance_of_rain_4
  entity_pop_5: sensor.bom_perth_chance_of_rain_5
  entity_current_text: sensor.bom_current_text
  entity_uv_alert: sensor.bom_uv_alert
  entity_fire_danger: sensor.bom_fire_danger
  entity_uv_alert_summary: sensor.bom_uv_alert_summary
  entity_fire_danger_summary: sensor.bom_fire_danger_summary
  locale: en
  sunset: true
  static_icons: false
  tooltip_bg_color: 'rgb( 75,155,239)'
  tooltip_border_color: 'rgb(255,161,0)'
  tooltip_border_width: 1
  tooltip_caret_size: 5
  tooltip_fg_color: '#fff'
  tooltip_left_offset: 3
  tooltip_width: 80
  tooltips: true
  old_daily_format: false
  time_format: 12
  show_beaufort: false
  show_decimals: false
  refresh_interval: 60
  show_separator: false

  # TODO: Fix the ordering of this, pressure does not show? Try and get two columns on my iphone?
#  slot_l1: daytime_high
#  slot_l2: daytime_low
#  slot_l3: wind
#  slot_l4: sun_next
#  slot_l5: sun_following
#  slot_r1: pop
#  slot_r2: humidity
#  slot_r3: uv_alert
#  slot_r4: fire_danger
#  slot_r5: empty

  slot_l1: daytime_high
  slot_l2: daytime_low
  slot_l3: humidity
  slot_l4: pop
  slot_l5: wind
  slot_r1: uv_summary
  slot_r2: fire_summary
  slot_r3: sun_next
  slot_r4: sun_following
  slot_r5: empty

- type: picture-entity
  name: Perth (last hour)
  show_name: false
  show_state: false
  entity: camera.bom_radar_loop_perth
  tap_action:
    action: none
  hold_action:
    action: none
  double_tap_action:
    action: none
