#######################################################################################
# WARNING: This file is written to by the build process, any manual edits will be lost!
################################################################################
- type: custom:mini-graph-card
  name: Current Power Consumption
  icon: mdi:home-lightning-bolt
  font_size_header: 19
  aggregate_func: max
  hours_to_show: 24
  points_per_hour: 6
  line_width: 2
  tap_action: none
  show_state: true
  show_indicator: true
  show:
    extrema: true
    fill: false
  entities:
    - entity: sensor.home_power
      name: Home Load
    - entity: sensor.home_base_power
      name: Base Load
    - entity: sensor.home_peak_power
      name: Peak Load
################################################################################
- type: entities
  entities:
    - entity: sensor.home_power
      name: Home Load
      icon: mdi:home-lightning-bolt
    - entity: sensor.home_base_power
      name: Base Load
      icon: mdi:home-lightning-bolt
    - entity: sensor.home_peak_power
      name: Peak Load
      icon: mdi:home-lightning-bolt
################################################################################
- type: entities
  entities:
    - entity: sensor.lights_power
      name: All Lights
      icon: mdi:home-lightning-bolt
    - entity: sensor.fans_power
      name: All Fans
      icon: mdi:home-lightning-bolt
    - entity: sensor.all_standby_power
      name: All Standby
      icon: mdi:home-lightning-bolt
    - entity: sensor.coffee_machine_power
      name: Coffee Machine
      icon: mdi:home-lightning-bolt
    - entity: sensor.battery_charger_power
      name: Battery Charger
      icon: mdi:home-lightning-bolt
    - entity: sensor.vacuum_charger_power
      name: Vacuum Charger
      icon: mdi:home-lightning-bolt
    - entity: sensor.pool_filter_power
      name: Pool Filter
      icon: mdi:home-lightning-bolt
    - entity: sensor.water_booster_power
      name: Hot Water Booster
      icon: mdi:home-lightning-bolt
    - entity: sensor.dish_washer_power
      name: Dish Washer
      icon: mdi:home-lightning-bolt
    - entity: sensor.clothes_dryer_power
      name: Clothes Dryer
      icon: mdi:home-lightning-bolt
    - entity: sensor.washing_machine_power
      name: Washing Machine
      icon: mdi:home-lightning-bolt
    - entity: sensor.kitchen_fridge_power
      name: Kitchen Fridge
      icon: mdi:home-lightning-bolt
    - entity: sensor.deck_freezer_power
      name: Deck Freezer
      icon: mdi:home-lightning-bolt
    - entity: sensor.towel_rails_power
      name: Towel Rails
      icon: mdi:home-lightning-bolt
    - entity: sensor.study_outlet_power
      name: Study Outlet
      icon: mdi:home-lightning-bolt
    - entity: sensor.audio_visual_devices_power
      name: Audio/Visual Devices
      icon: mdi:home-lightning-bolt
    - entity: sensor.servers_network_power
      name: Servers & Network
      icon: mdi:home-lightning-bolt
################################################################################
- type: custom:layout-break
################################################################################
- type: custom:mini-graph-card
  name: Daily Energy Consumption
  icon: mdi:battery-charging
  font_size_header: 19
  aggregate_func: max
  hours_to_show: 24
  points_per_hour: 6
  line_width: 2
  tap_action: none
  show_state: true
  show_indicator: true
  show:
    extrema: true
    fill: false
  entities:
    - entity: sensor.home_energy_daily
      name: Home Load
    - entity: sensor.home_base_energy_daily
      name: Base Load
    - entity: sensor.home_peak_energy_daily
      name: Peak Load
################################################################################
- type: entities
  entities:
    - entity: sensor.home_energy_daily
      name: Home Load
      icon: mdi:battery-charging
    - entity: sensor.home_base_energy_daily
      name: Base Load
      icon: mdi:battery-charging
    - entity: sensor.home_peak_energy_daily
      name: Peak Load
      icon: mdi:battery-charging
################################################################################
- type: entities
  entities:
    - entity: sensor.lights_energy_daily
      name: All Lights
      icon: mdi:battery-charging
    - entity: sensor.fans_energy_daily
      name: All Fans
      icon: mdi:battery-charging
    - entity: sensor.all_standby_energy_daily
      name: All Standby
      icon: mdi:battery-charging
    - entity: sensor.coffee_machine_energy_daily
      name: Coffee Machine
      icon: mdi:battery-charging
    - entity: sensor.battery_charger_energy_daily
      name: Battery Charger
      icon: mdi:battery-charging
    - entity: sensor.vacuum_charger_energy_daily
      name: Vacuum Charger
      icon: mdi:battery-charging
    - entity: sensor.pool_filter_energy_daily
      name: Pool Filter
      icon: mdi:battery-charging
    - entity: sensor.water_booster_energy_daily
      name: Hot Water Booster
      icon: mdi:battery-charging
    - entity: sensor.dish_washer_energy_daily
      name: Dish Washer
      icon: mdi:battery-charging
    - entity: sensor.clothes_dryer_energy_daily
      name: Clothes Dryer
      icon: mdi:battery-charging
    - entity: sensor.washing_machine_energy_daily
      name: Washing Machine
      icon: mdi:battery-charging
    - entity: sensor.kitchen_fridge_energy_daily
      name: Kitchen Fridge
      icon: mdi:battery-charging
    - entity: sensor.deck_freezer_energy_daily
      name: Deck Freezer
      icon: mdi:battery-charging
    - entity: sensor.towel_rails_energy_daily
      name: Towel Rails
      icon: mdi:battery-charging
    - entity: sensor.study_outlet_energy_daily
      name: Study Outlet
      icon: mdi:battery-charging
    - entity: sensor.audio_visual_devices_energy_daily
      name: Audio/Visual Devices
      icon: mdi:battery-charging
    - entity: sensor.servers_network_energy_daily
      name: Servers & Network
      icon: mdi:battery-charging
################################################################################
- type: custom:layout-break
################################################################################
