#######################################################################################
# WARNING: This file is written to by the build process, any manual edits will be lost!
################################################################################
- type: media-control
  entity: media_player.ada_home
################################################################################
- type: media-control
  entity: media_player.edwin_home
################################################################################
- type: media-control
  entity: media_player.parents_home
################################################################################
- type: media-control
  entity: media_player.kitchen_home
################################################################################
- type: media-control
  entity: media_player.office_home
################################################################################
- type: media-control
  entity: media_player.lounge_home
################################################################################
- type: media-control
  entity: media_player.ada_tablet
################################################################################
- type: custom:layout-break
################################################################################
- type: media-control
  entity: media_player.lg_webos_smart_tv
################################################################################
- type: media-control
  entity: media_player.edwin_tablet
################################################################################
- type: custom:layout-break
################################################################################
- type: media-control
  entity: media_player.lounge_arc
################################################################################
- type: media-control
  entity: media_player.kitchen_move
################################################################################
- type: media-control
  entity: media_player.kitchen_five
################################################################################
- type: media-control
  entity: media_player.parents_move
################################################################################
