[package]

name = "gateway"
version = "0.0.0-SNAPSHOT"

[dependencies]
chrono = "0.4"

[[bin]]
name = "gateway"
path = "src/main/rust/main.rs"

[[test]]
name = "gateway_test"
path = "src/test/rust/unit_tests.rs"
