#######################################################################################
# WARNING: This file is written to by the build process, any manual edits will be lost!
################################################################################
- type: entities
  title: Routines
  show_header_toggle: false
  entities:
    - entity: input_boolean.home_security
      name: Secure
      icon: mdi:shield-home
    - entity: input_boolean.home_movie
      name: Movie
      icon: mdi:youtube-tv
    - entity: input_boolean.home_sleep
      name: Sleep
      icon: mdi:chat-sleep
    - entity: input_boolean.home_reset
      name: Reset
      icon: mdi:refresh-circle
################################################################################
- type: custom:layout-break
################################################################################
- type: entities
  title: Fans
  entities:
    - entity: fan.ada_fan
      name: Ada
      icon: mdi:fan
    - entity: fan.edwin_fan
      name: Edwin
      icon: mdi:fan
    - entity: fan.parents_fan
      name: Parents
      icon: mdi:fan
    - entity: switch.kitchen_fan_plug
      name: Kitchen
      icon: mdi:fan
    - entity: fan.lounge_fan
      name: Lounge
      icon: mdi:fan
    - entity: fan.deck_fan
      name: Deck
      icon: mdi:fan
################################################################################
- type: custom:layout-break
################################################################################
- type: entities
  title: Lights
  entities:
    - entity: light.ada_fan
      name: Ada Main
      icon: mdi:lightbulb-group
    - entity: light.ada_lamp
      name: Ada Lamp
      icon: mdi:lightbulb-group
    - entity: light.edwin_lamp
      name: Edwin Lamp
      icon: mdi:lightbulb-group
    - entity: light.edwin_fan
      name: Edwin Main
      icon: mdi:lightbulb-group
    - entity: light.edwin_night_light
      name: Edwin Night Light
      icon: mdi:lightbulb-group
    - entity: light.hallway_main
      name: Hallway Main
      icon: mdi:lightbulb-group
    - entity: light.hallway_sconces
      name: Hallway Sconces
      icon: mdi:lightbulb-group
    - entity: light.dining_main
      name: Dining Main
      icon: mdi:lightbulb-group
    - entity: light.lounge_main
      name: Lounge Main
      icon: mdi:lightbulb-group
    - entity: light.lounge_fan
      name: Lounge Fan
      icon: mdi:lightbulb-group
    - entity: light.lounge_lamp
      name: Lounge Lamp
      icon: mdi:lightbulb-group
    - entity: light.parents_main
      name: Parents Main
      icon: mdi:lightbulb-group
    - entity: light.parents_sconces
      name: Parents Sconces
      icon: mdi:lightbulb-group
    - entity: light.study_lamp
      name: Study Lamp
      icon: mdi:lightbulb-group
    - entity: light.kitchen_main
      name: Kitchen Main
      icon: mdi:lightbulb-group
    - entity: switch.kitchen_downlights_plug
      name: Kitchen Downlights
      icon: mdi:lightbulb-group
    - entity: light.laundry_main
      name: Laundry Main
      icon: mdi:lightbulb-group
    - entity: light.pantry_main
      name: Pantry Main
      icon: mdi:lightbulb-group
    - entity: light.office_main
      name: Office Main
      icon: mdi:lightbulb-group
    - entity: light.bathroom_main
      name: Bathroom Main
      icon: mdi:lightbulb-group
    - entity: light.bathroom_sconces
      name: Bathroom Sconces
      icon: mdi:lightbulb-group
    - entity: light.ensuite_main
      name: Ensuite Main
      icon: mdi:lightbulb-group
    - entity: light.ensuite_sconces
      name: Ensuite Sconces
      icon: mdi:lightbulb-group
    - entity: light.wardrobe_main
      name: Wardrobe Main
      icon: mdi:lightbulb-group
    - entity: switch.deck_festoons_plug
      name: Deck Festoons
      icon: mdi:lightbulb-group
    - entity: switch.landing_festoons_plug
      name: Landing Festoons
      icon: mdi:lightbulb-group
################################################################################
- type: custom:layout-break
################################################################################
- type: entities
  title: Heating & Cooling
  show_header_toggle: false
  entities:
    - entity: switch.bathroom_rails_plug
      name: Towel Rails
      icon: mdi:radiator
################################################################################
- type: entities
  title: Air Purifiers
  entities:
    - entity: fan.lounge_air_purifier
      name: Lounge
      icon: mdi:air-purifier
    - entity: fan.dining_air_purifier
      name: Dining
      icon: mdi:air-purifier
################################################################################
