host: ${ANODE_HOST}
port: ${ANODE_PORT}
publish_host: ${MQTT_HOST}
publish_port: ${MQTT_PORT}
publish_batch_seconds: 10
publish_status_topic: 'anode/status'
publish_push_data_topic: 'haas/sensor/state'
publish_push_metadata_topic: 'haas/sensor/config'
#publish_batch_datum_topic: 'asystem/anode'

# TODO: Re-enable once model building and deployment updated
#model_pull_seconds: 30
#model_pull_region: 'ap-southeast-2'
#model_pull_bucket: '0-asystem-amodel'
#model_pull_bucket_snapshot: '-staging'

save_on_exit: True
save_seconds: 600
plugin:

  # TODO: Diable until energy meter is moved to Wootoona
  #  fronius:
  #    poll_seconds: 1
  #    buffer_ticks: 120
  #    history_partitions: 15
  #    history_ticks: 10500000
  #    history_partition_seconds: 86400
  #    repeat_seconds: 99
  #    repeat_partition: True
  #    publish_ticks: -1

  kasa:
    poll_seconds: 1
    buffer_ticks: 110
    history_partitions: 15
    history_ticks: 10500000
    history_partition_seconds: 86400
    repeat_seconds: 101
    repeat_partition: True
    publish_ticks: -1
  davis:
    poll_seconds: -1
    buffer_ticks: 30
    history_partitions: 15
    history_ticks: 1800000
    history_partition_seconds: 86400
    repeat_seconds: 103
    repeat_partition: True
    publish_ticks: -1
    darksky:
      poll_seconds: 300
      buffer_ticks: 5
      history_partitions: 15
      history_ticks: 1500000
      history_partition_seconds: 86400
      repeat_seconds: 111
      repeat_partition: True
      publish_ticks: -1
  netatmo:
    poll_seconds: 50
    buffer_ticks: 10
    history_partitions: 15
    history_ticks: 2100000
    history_partition_seconds: 86400
    repeat_seconds: 107
    repeat_partition: True
    publish_ticks: -1
  speedtest:
    poll_seconds: -1
    buffer_ticks: 30
    history_partitions: 15
    history_ticks: 450000
    history_partition_seconds: 86400
    repeat_seconds: 113
    repeat_partition: True
    publish_ticks: -1
  hue:
    poll_seconds: 1
    buffer_ticks: 110
    history_partitions: 15
    history_ticks: 10500000
    history_partition_seconds: 86400
    repeat_seconds: 117
    repeat_partition: True
    publish_ticks: -1

# TODO: Disable until models retrained with new darksky features
#  energyforecast:
#    poll_seconds: 15
#    buffer_ticks: 5
#    history_partitions: 15
#    history_ticks: 300000
#    history_partition_seconds: 86400
#    repeat_seconds: 115
#    repeat_partition: True
#    publish_ticks: -1