version: '3.7'
x-common: &common
  image: mariadb:${SERVICE_VERSION_ABSOLUTE}
  init: true
  user: root
  environment:
    - TZ=Australia/Perth
    - MARIADB_IP
    - MARIADB_HOST
    - MARIADB_PORT
    - MARIADB_ROOT_PASSWORD=${MARIADB_KEY}
    - MARIADB_DATABASE=${MARIADB_DATABASE_WEEWX}
    - MARIADB_USER=${MARIADB_USER_WEEWX}
    - MARIADB_PASSWORD=${MARIADB_KEY_WEEWX}
  logging:
    driver: "json-file"
    options:
      max-file: "5"
      max-size: "100m"
services:
  mariadb:
    container_name: mariadb
    <<: *common
    restart: ${SERVICE_RESTART}
    volumes:
      - ${SERVICE_DATA_DIR}/bootstrap.sh:/bootstrap/bootstrap.sh
      - ${SERVICE_DATA_DIR}:/var/lib/mysql
    ports:
      - ${MARIADB_PORT}:${MARIADB_PORT}
    deploy:
      resources:
        limits:
          memory: 1024M
  mariadb_bootstrap:
    container_name: mariadb_bootstrap
    <<: *common
    restart: 'no'
    volumes:
      - ${SERVICE_DATA_DIR}/bootstrap.sh:/bootstrap/bootstrap.sh
      - ${SERVICE_DATA_DIR}:/var/lib/mysql
    entrypoint: /bin/bash
    command:
      - /bootstrap/bootstrap.sh
    depends_on:
      - mariadb
