version: '3.7'
services:
  influxdb:
    container_name: influxdb
    image: quay.io/influxdb/influxdb:2.0.0-beta
    init: true
    restart: ${RESTART}
    environment:
      - TZ=Australia/Perth
      - INFLUXDB_USER
      - INFLUXDB_PASSWORD=${INFLUXDB_KEY}

      # TODO: Update to 'Home' once InfluxDB-2-Beta-17 comes out and database format reverts to 1.8 format
      - INFLUXDB_ORG=asystem

      - INFLUXDB_BUCKET=asystem
    volumes:
      - ${DATA_DIR}:/root/.influxdbv2
    ports:
      - 9999:9999
