version: '3.7'
services:
  influxdb:
    container_name: influxdb_${HOST_NAME}
    image: quay.io/influxdb/influxdb:v2.0.1
    init: true
    restart: ${RESTART}
    environment:
      - TZ=Australia/Perth

      # TODO: Automate setup as per https://github.com/influxdata/influxdb/pull/17946/commits/996ba9a65c68005ab1f8f64377af97be7550d010#diff-c43edca80239cb76564c11e503856bc9
      - INFLUXDB_USER
      - INFLUXDB_PASSWORD=${INFLUXDB_KEY}
      - INFLUXDB_ORG=home
      - INFLUXDB_BUCKET=asystem

    volumes:
      - ${DATA_DIR}:/root/.influxdbv2
    ports:
      - 8086:8086
    deploy:
      resources:
        limits:
          memory: 4G