version: '3.7'
services:
  influxdb:
    container_name: influxdb
    image: quay.io/influxdb/influxdb:2.0.0-beta
    init: true
    restart: ${RESTART}
    environment:
      - TZ=Australia/Perth
    volumes:
      - ${DATA_DIR}:/root/.influxdbv2
    ports:
      - 9999:9999
