version: '3.7'
services:
  influxdb:
    container_name: influxdb
    image: quay.io/influxdb/influxdb:v2.0.6
    init: true
    restart: ${SERVICE_RESTART}
    environment:
      - TZ=Australia/Perth
      - INFLUXD_CONFIG_PATH=/root/.influxdbv2/config.yml
      - INFLUXDB_IP
      - INFLUXDB_PORT
      - INFLUXDB_ORG
      - INFLUXDB_BUCKET_HOME_PUBLIC
      - INFLUXDB_BUCKET_HOME_PRIVATE
      - INFLUXDB_BUCKET_HOST_PRIVATE
      - INFLUXDB_USER
      - INFLUXDB_USER_ALL
      - INFLUXDB_USER_PUBLIC
      - INFLUXDB_KEY
      - INFLUXDB_TOKEN
      - INFLUXDB_TOKEN_PUBLIC_V1
      - INFLUXDB_TOKEN_PUBLIC_V2
    volumes:
      - ${SERVICE_DATA_DIR}:/root/.influxdbv2
    ports:
      - ${INFLUXDB_PORT}:${INFLUXDB_PORT}
    deploy:
      resources:
        limits:
          memory: 5G
  influxdb_setup:
    container_name: influxdb_setup
    image: quay.io/influxdb/influxdb:v2.0.6
    environment:
      - INFLUXDB_IP
      - INFLUXDB_PORT
      - INFLUXDB_ORG
      - INFLUXDB_BUCKET_HOME_PUBLIC
      - INFLUXDB_BUCKET_HOME_PRIVATE
      - INFLUXDB_BUCKET_HOST_PRIVATE
      - INFLUXDB_USER
      - INFLUXDB_USER_ALL
      - INFLUXDB_USER_PUBLIC
      - INFLUXDB_KEY
      - INFLUXDB_TOKEN
      - INFLUXDB_TOKEN_PUBLIC_V1
      - INFLUXDB_TOKEN_PUBLIC_V2
    volumes:
      - ${SERVICE_DATA_DIR}:/root/.influxdbv2
      - ${SERVICE_DATA_DIR}/setup.sh:/setup.sh
    command:
      - /setup.sh
    depends_on:
      - influxdb