version: '3.7'
services:
  influxdb:
    container_name: influxdb
    image: quay.io/influxdb/influxdb:v2.0.6
    init: true
    restart: ${RESTART}
    environment:
      - TZ=Australia/Perth
      - INFLUXD_CONFIG_PATH=/root/.influxdbv2/config.yml
    volumes:
      - ${DATA_DIR}:/root/.influxdbv2
    ports:
      - 8086:8086
    deploy:
      resources:
        limits:
          memory: 5G
  influxdb_setup:
    container_name: influxdb_setup
    image: quay.io/influxdb/influxdb:v2.0.6
    environment:
      - INFLUXDB_HOST
      - INFLUXDB_PORT
    volumes:
      - ${DATA_DIR}:/root/.influxdbv2
      - ${DATA_DIR}/setup.sh:/setup.sh
    command:
      - /setup.sh
    depends_on:
      - influxdb