services:
  weewx:
    image: weewx:${SERVICE_VERSION_ABSOLUTE}
    container_name: weewx
    init: true
    restart: ${SERVICE_RESTART}
    environment:
      - TZ=Australia/Perth
      - WEEWX_UID=weewx
      - WEEWX_GID=dialout
      - WEEWX_SERVICE
      - WEEWX_HTTP_PORT
      - MARIADB_SERVICE
      - MARIADB_USER_WEEWX
      - MARIADB_DATABASE_WEEWX
      - VERNEMQ_SERVICE
      - VERNEMQ_API_PORT
    ports:
      - ${WEEWX_HTTP_PORT}:80
    volumes:
      - ${SERVICE_DATA_DIR}:/asystem/mnt
    healthcheck:
      test: /asystem/etc/checkhealthy.sh
      interval: 2m
      timeout: 30s
      retries: 3
      start_period: 1m
      start_interval: 10s
    devices:
      - ${WEEWX_DEV}:/dev/ttyUSB0
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "100m"
    deploy:
      resources:
        limits:
          memory: 256M