######################################################################################
compensation:
  weatherstation_console_battery_percent:
    unique_id: weatherstation_console_battery_percent
    source: sensor.weatherstation_console_battery_voltage
    precision: 1
    unit_of_measurement: "%"
    data_points:
      - [ 4.5, 100 ]
      - [ 3.0, 0 ]
######################################################################################
template:
  - sensor:
      - unique_id: weatherstation_console_battery_percent_int
        device_class: battery
        state_class: measurement
        unit_of_measurement: "%"
        state: >-
          {{ states('sensor.compensation_sensor_weatherstation_console_battery_voltage') | float(0) | int }}
######################################################################################
