#######################################################################################
# WARNING: This file is written to by the build process, any manual edits will be lost!
#######################################################################################
compensation:
  #####################################################################################
  weatherstation_console_battery_percent:
    unique_id: weatherstation_console_battery_percent
    source: sensor.weatherstation_console_battery_voltage
    precision: 1
    unit_of_measurement: "%"
    data_points:
      - [ 4.5, 100 ]
      - [ 3.0, 0 ]
#######################################################################################
template:
  #####################################################################################
  - sensor:
      #################################################################################
      - unique_id: weatherstation_console_battery_percent_int
        device_class: battery
        state_class: measurement
        unit_of_measurement: "%"
        state: >-
          {{ states('sensor.compensation_sensor_weatherstation_console_battery_voltage') | float(0) | int }}
      #################################################################################
      - unique_id: weatherstation_coms_signal_quality_percentage
        device_class: signal_strength
        state_class: measurement
        unit_of_measurement: "%"
        state: >-
          {{ states('sensor.weatherstation_coms_signal_quality') | int(0) }}
      #################################################################################
      - unique_id: driveway_repeater_linkquality_percentage
        device_class: signal_strength
        state_class: measurement
        unit_of_measurement: "%"
        state: >-
          {{ ((states('sensor.driveway_repeater_linkquality') | float(0)) / 255 * 100) | int(0) }}
      #################################################################################
      - unique_id: landing_repeater_linkquality_percentage
        device_class: signal_strength
        state_class: measurement
        unit_of_measurement: "%"
        state: >-
          {{ ((states('sensor.landing_repeater_linkquality') | float(0)) / 255 * 100) | int(0) }}
      #################################################################################
      - unique_id: garden_repeater_linkquality_percentage
        device_class: signal_strength
        state_class: measurement
        unit_of_measurement: "%"
        state: >-
          {{ ((states('sensor.garden_repeater_linkquality') | float(0)) / 255 * 100) | int(0) }}
      #################################################################################
      - unique_id: deck_fans_outlet_linkquality_percentage
        device_class: signal_strength
        state_class: measurement
        unit_of_measurement: "%"
        state: >-
          {{ ((states('sensor.deck_fans_outlet_linkquality') | float(0)) / 255 * 100) | int(0) }}
      #################################################################################
      - unique_id: kitchen_fan_outlet_linkquality_percentage
        device_class: signal_strength
        state_class: measurement
        unit_of_measurement: "%"
        state: >-
          {{ ((states('sensor.kitchen_fan_outlet_linkquality') | float(0)) / 255 * 100) | int(0) }}
      #################################################################################
      - unique_id: edwin_wardrobe_outlet_linkquality_percentage
        device_class: signal_strength
        state_class: measurement
        unit_of_measurement: "%"
        state: >-
          {{ ((states('sensor.edwin_wardrobe_outlet_linkquality') | float(0)) / 255 * 100) | int(0) }}
#######################################################################################
