#######################################################################################
# WARNING: This file is written to by the build process, any manual edits will be lost!
#######################################################################################
# NOTE: Use for populating the Google Cast UI integration 'known_hosts' field 
# cast:
#  known_hosts: 10.0.4.50,10.0.4.51,10.0.4.54,10.0.4.52
#######################################################################################
wake_on_lan:
# webostv:
#   host: 10.0.4.49
#   name: Lounge TV
#   customize:
#     sources:
#       - livetv
#       - youtube
#       - netflix
#       - hdmi1
automation:
  - id: media_lounge_tv_on
    alias: "Media: Turn on lounge TV"
    trigger:
      - platform: webostv.turn_on
        entity_id: media_player.lounge_tv
    action:
      # wakeonlan -i 10.0.4.255 -p 9 4c:ba:d7:bf:94:d0 works!
      - service: wake_on_lan.send_magic_packet
        data:
          mac: 4c:ba:d7:bf:94:d0
          broadcast_address: 10.0.4.255
          broadcast_port: 9
sonos:
  media_player:
    hosts:
      - 10.0.4.40
      - 10.0.4.41
      - 10.0.4.42
      - 10.0.4.43
#######################################################################################
