services:
  redpanda:
    # https://github.com/redpanda-data/redpanda/releases
    image: redpandadata/redpanda:v24.3.6
    container_name: redpanda
    init: true
    restart: ${SERVICE_RESTART}
    environment:
      - TZ=Australia/Perth
    ports:
      - ${REDPANDA_PORT}:9092
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "100m"
    deploy:
      resources:
        limits:
          memory: 1G