version: '3.7'
services:
  nginx:
    container_name: nginx
    image: nginx:1.19.2-alpine
    init: true
    restart: ${RESTART}
    environment:
      - TZ=Australia/Perth
    ports:
      - 9443:9443
    volumes:
      - ${DATA_DIR}/nginx.conf:/etc/nginx/nginx.conf
      - ${DATA_DIR}/.key.pem:/etc/nginx/.key.pem
      - ${DATA_DIR}/certificate.pem:/etc/nginx/certificate.pem
