# https://nginx.org/en/CHANGES
version: '3.7'
services:
  nginx:
    container_name: nginx
    image: nginx:1.23.0-alpine
    init: true
    restart: ${SERVICE_RESTART}
    environment:
      - TZ=Australia/Perth
    ports:
      - ${NGINX_PORT_HTTP}:${NGINX_PORT_HTTP}
      - ${NGINX_PORT_HTTPS}:${NGINX_PORT_HTTPS}
    volumes:
      - ${SERVICE_DATA_DIR}/nginx.conf:/etc/nginx/nginx.conf
      - ${SERVICE_DATA_DIR}/.key.pem:/etc/nginx/.key.pem
      - ${SERVICE_DATA_DIR}/certificate.pem:/etc/nginx/certificate.pem
      - ${SERVICE_DATA_DIR}/html:/usr/share/nginx/html
    deploy:
      resources:
        limits:
          memory: 5G