services:
  digitemp:
    image: digitemp:${SERVICE_VERSION_ABSOLUTE}
    container_name: digitemp
    init: true
    restart: ${SERVICE_RESTART}
    environment:
      - TZ=Australia/Perth
      - VERNEMQ_SERVICE
      - VERNEMQ_API_PORT
    volumes:
      - ${SERVICE_DATA_DIR}:/asystem/mnt:rw
    devices:
      - /dev/ttyUSBTempProbe:/dev/ttyUSB0:rw
    healthcheck:
      test: /asystem/etc/checkhealthy.sh
      interval: 2m
      timeout: 30s
      retries: 3
      start_period: 1m
      start_interval: 10s
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "100m"
    deploy:
      resources:
        limits:
          memory: 128M
