x-common: &common
  image: supervisor:${SERVICE_VERSION_ABSOLUTE}
  init: true
  environment:
    - TZ=${TZ}
    - SERVICE_NAME
    - SUPERVISOR_HOST
    - SUPERVISOR_MOUNT
    - SUPERVISOR_LOG_LEVEL
    - BROKER_HOST
    - BROKER_PORT
    - DATABASE_HOST
    - DATABASE_PORT
    - DATABASE_NAME
    - DATABASE_TOKEN
    - BROKER_TOKEN
  cap_add:
    - SYSLOG
    - SYS_RAWIO
    - SYS_ADMIN
  device_cgroup_rules:
    - "c 1:11 r"
    - "b 8:* r"
    - "b 259:* r"
  security_opt:
    - apparmor=unconfined
  volumes:
    - ${SERVICE_DATA_DIR}:/asystem/mnt
    - /var/run/docker.sock:/var/run/docker.sock
    - ${SUPERVISOR_ROOT_SOURCE}:${SUPERVISOR_MOUNT}:ro
    - ${SUPERVISOR_FSTAB_SOURCE}:/etc/fstab:ro
    - ${SUPERVISOR_BTRFS_SOURCE}:/var/lib/btrfs:rw
    - ${SUPERVISOR_INSTALL_SOURCE}:/var/lib/asystem/install:ro
    - ${SUPERVISOR_DEV_SOURCE}:${SUPERVISOR_DEV_TARGET}
    - ${SUPERVISOR_HOME_SOURCE}:/home/asystem:rw
    - type: bind
      source: ${SUPERVISOR_SHARE_SOURCE}
      target: /share
      bind:
        propagation: ${SUPERVISOR_BIND_PROPAGATION}
        create_host_path: true
    - type: bind
      source: ${SUPERVISOR_BACKUP_SOURCE}
      target: /backup
      bind:
        propagation: ${SUPERVISOR_BIND_PROPAGATION}
        create_host_path: true
  logging:
    driver: "json-file"
    options:
      max-file: "5"
      max-size: "100m"
services:
  supervisor:
    container_name: supervisor
    <<: *common
    restart: ${SERVICE_RESTART}
    healthcheck:
      test: /asystem/etc/checkhealthy.sh
      interval: 2m
      timeout: 30s
      retries: 3
      start_period: 1m
      start_interval: 10s
    deploy:
      resources:
        limits:
          memory: 384M
