version: '3.7'
services:
  monitor:
    container_name: monitor
    image: monitor:${SERVICE_VERSION_ABSOLUTE}
    init: true
    restart: ${SERVICE_RESTART}
    environment:
      - TZ=Australia/Perth
      - HOST_IP
      - HOST_NAME
      - VERNEMQ_SERVICE
      - VERNEMQ_PORT
      - INFLUXDB_SERVICE
      - INFLUXDB_HTTP_PORT
      - HOST_ETC=/hostfs/etc
      - HOST_PROC=/hostfs/proc
      - HOST_SYS=/hostfs/sys
      - HOST_VAR=/hostfs/var
      - HOST_RUN=/hostfs/run
      - HOST_MOUNT_PREFIX=/hostfs
    volumes:
      - /:/hostfs:ro
      - /run/udev:/run/udev:ro
      - /run/utmp:/hostfs/var/run/utmp:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${SERVICE_DATA_DIR}/telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - ${SERVICE_DATA_DIR}:/asystem/runtime
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "100m"
    deploy:
      resources:
        limits:
          memory: 256M
