// Code generated by "stringer -type=ID -output=metric_string.go"; DO NOT EDIT.

package metric

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[MetricCluster-0]
	_ = x[MetricHost-1]
	_ = x[MetricHostUsedProcessor-2]
	_ = x[MetricHostUsedMemory-3]
	_ = x[MetricHostAllocatedMemory-4]
	_ = x[MetricHostFailedLogs-5]
	_ = x[MetricHostFailedShares-6]
	_ = x[MetricHostFailedBackupStages-7]
	_ = x[MetricHostWarnTemperature-8]
	_ = x[MetricHostSpinFanSpeed-9]
	_ = x[MetricHostUsedDriveLife-10]
	_ = x[MetricHostUsedHomeSpace-11]
	_ = x[MetricHostUsedShareSpace-12]
	_ = x[MetricHostUsedBackupSpace-13]
	_ = x[MetricHostUsedSwapSpace-14]
	_ = x[MetricHostUsedDiskTime-15]
	_ = x[MetricHostUsedNetwork-16]
	_ = x[MetricHostUpTime-17]
	_ = x[MetricHostTemperature-18]
	_ = x[MetricHostServicesStatus-19]
	_ = x[MetricHostServicesMaxMemory-20]
	_ = x[MetricService-21]
	_ = x[MetricServiceBackupStatus-22]
	_ = x[MetricServiceHealthStatus-23]
	_ = x[MetricServiceConfiguredStatus-24]
	_ = x[MetricServiceName-25]
	_ = x[MetricServiceVersion-26]
	_ = x[MetricServiceUsedProcessor-27]
	_ = x[MetricServiceUsedMemory-28]
	_ = x[MetricServiceUsedDiskRate-29]
	_ = x[MetricServiceUsedNetwork-30]
	_ = x[MetricServiceUpTime-31]
	_ = x[MetricServiceMaxMemory-32]
	_ = x[MetricServiceRestartCount-33]
	_ = x[MetricHostFailedDrives-34]
	_ = x[MetricHostHaltedBackupStages-35]
	_ = x[MetricMax-36]
	_ = x[Self - -1]
}

const _ID_name = "SelfMetricClusterMetricHostMetricHostUsedProcessorMetricHostUsedMemoryMetricHostAllocatedMemoryMetricHostFailedLogsMetricHostFailedSharesMetricHostFailedBackupStagesMetricHostWarnTemperatureMetricHostSpinFanSpeedMetricHostUsedDriveLifeMetricHostUsedHomeSpaceMetricHostUsedShareSpaceMetricHostUsedBackupSpaceMetricHostUsedSwapSpaceMetricHostUsedDiskTimeMetricHostUsedNetworkMetricHostUpTimeMetricHostTemperatureMetricHostServicesStatusMetricHostServicesMaxMemoryMetricServiceMetricServiceBackupStatusMetricServiceHealthStatusMetricServiceConfiguredStatusMetricServiceNameMetricServiceVersionMetricServiceUsedProcessorMetricServiceUsedMemoryMetricServiceUsedDiskRateMetricServiceUsedNetworkMetricServiceUpTimeMetricServiceMaxMemoryMetricServiceRestartCountMetricHostFailedDrivesMetricHostHaltedBackupStagesMetricMax"

var _ID_index = [...]uint16{0, 4, 17, 27, 50, 70, 95, 115, 137, 165, 190, 212, 235, 258, 282, 307, 330, 352, 373, 389, 410, 434, 461, 474, 499, 524, 553, 570, 590, 616, 639, 664, 688, 707, 729, 754, 776, 804, 813}

func (i ID) String() string {
	idx := int(i) - -1
	if i < -1 || idx >= len(_ID_index)-1 {
		return "ID(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ID_name[_ID_index[idx]:_ID_index[idx+1]]
}
