// Code generated by "stringer -type=ID -output=metric_string.go"; DO NOT EDIT.

package metric

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[MetricHost-0]
	_ = x[MetricHostUsedProcessor-1]
	_ = x[MetricHostUsedMemory-2]
	_ = x[MetricHostAllocatedMemory-3]
	_ = x[MetricHostFailedLogs-4]
	_ = x[MetricHostFailedShares-5]
	_ = x[MetricHostFailedBackupStages-6]
	_ = x[MetricHostWarnTemperature-7]
	_ = x[MetricHostSpinFanSpeed-8]
	_ = x[MetricHostUsedDriveLife-9]
	_ = x[MetricHostUsedHomeSpace-10]
	_ = x[MetricHostUsedShareSpace-11]
	_ = x[MetricHostUsedBackupSpace-12]
	_ = x[MetricHostUsedSwapSpace-13]
	_ = x[MetricHostUsedDiskTime-14]
	_ = x[MetricHostUsedNetwork-15]
	_ = x[MetricHostUpTime-16]
	_ = x[MetricHostTemperature-17]
	_ = x[MetricHostServicesStatus-18]
	_ = x[MetricHostServicesMaxMemory-19]
	_ = x[MetricService-20]
	_ = x[MetricServiceBackupStatus-21]
	_ = x[MetricServiceHealthStatus-22]
	_ = x[MetricServiceConfiguredStatus-23]
	_ = x[MetricServiceName-24]
	_ = x[MetricServiceVersion-25]
	_ = x[MetricServiceUsedProcessor-26]
	_ = x[MetricServiceUsedMemory-27]
	_ = x[MetricServiceUsedDiskRate-28]
	_ = x[MetricServiceUsedNetwork-29]
	_ = x[MetricServiceUpTime-30]
	_ = x[MetricServiceMaxMemory-31]
	_ = x[MetricServiceRestartCount-32]
	_ = x[MetricHostFailedDrives-33]
	_ = x[MetricMax-34]
	_ = x[Self - -1]
}

const _ID_name = "SelfMetricHostMetricHostUsedProcessorMetricHostUsedMemoryMetricHostAllocatedMemoryMetricHostFailedLogsMetricHostFailedSharesMetricHostFailedBackupStagesMetricHostWarnTemperatureMetricHostSpinFanSpeedMetricHostUsedDriveLifeMetricHostUsedHomeSpaceMetricHostUsedShareSpaceMetricHostUsedBackupSpaceMetricHostUsedSwapSpaceMetricHostUsedDiskTimeMetricHostUsedNetworkMetricHostUpTimeMetricHostTemperatureMetricHostServicesStatusMetricHostServicesMaxMemoryMetricServiceMetricServiceBackupStatusMetricServiceHealthStatusMetricServiceConfiguredStatusMetricServiceNameMetricServiceVersionMetricServiceUsedProcessorMetricServiceUsedMemoryMetricServiceUsedDiskRateMetricServiceUsedNetworkMetricServiceUpTimeMetricServiceMaxMemoryMetricServiceRestartCountMetricHostFailedDrivesMetricMax"

var _ID_index = [...]uint16{0, 4, 14, 37, 57, 82, 102, 124, 152, 177, 199, 222, 245, 269, 294, 317, 339, 360, 376, 397, 421, 448, 461, 486, 511, 540, 557, 577, 603, 626, 651, 675, 694, 716, 741, 763, 772}

func (i ID) String() string {
	idx := int(i) - -1
	if i < -1 || idx >= len(_ID_index)-1 {
		return "ID(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ID_name[_ID_index[idx]:_ID_index[idx+1]]
}
