// Code generated by "stringer -type=ID -output=metric_string.go"; DO NOT EDIT.

package metric

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[MetricHost-0]
	_ = x[MetricHostUsedProcessor-1]
	_ = x[MetricHostUsedMemory-2]
	_ = x[MetricHostAllocatedMemory-3]
	_ = x[MetricHostFailedLogs-4]
	_ = x[MetricHostFailedShares-5]
	_ = x[MetricHostFailedBackups-6]
	_ = x[MetricHostWarnTemperature-7]
	_ = x[MetricHostSpinFanSpeed-8]
	_ = x[MetricHostLifeUsedDrives-9]
	_ = x[MetricHostUsedSystemSpace-10]
	_ = x[MetricHostUsedShareSpace-11]
	_ = x[MetricHostUsedBackupSpace-12]
	_ = x[MetricHostUsedSwapSpace-13]
	_ = x[MetricHostUsedDiskOps-14]
	_ = x[MetricHostUsedNetwork-15]
	_ = x[MetricHostRunningTime-16]
	_ = x[MetricHostTemperature-17]
	_ = x[MetricHostServices-18]
	_ = x[MetricHostServicesMaxMemory-19]
	_ = x[MetricService-20]
	_ = x[MetricServiceBackupStatus-21]
	_ = x[MetricServiceHealthStatus-22]
	_ = x[MetricServiceConfiguredStatus-23]
	_ = x[MetricServiceName-24]
	_ = x[MetricServiceVersion-25]
	_ = x[MetricServiceUsedProcessor-26]
	_ = x[MetricServiceUsedMemory-27]
	_ = x[MetricServiceUsedDiskOps-28]
	_ = x[MetricServiceUsedNetwork-29]
	_ = x[MetricServiceUpTime-30]
	_ = x[MetricServiceMaxMemory-31]
	_ = x[MetricServiceRestartCount-32]
	_ = x[MetricHostFailedDrives-33]
	_ = x[MetricMax-34]
	_ = x[Self - -1]
}

const _ID_name = "SelfMetricHostMetricHostUsedProcessorMetricHostUsedMemoryMetricHostAllocatedMemoryMetricHostFailedLogsMetricHostFailedSharesMetricHostFailedBackupsMetricHostWarnTemperatureMetricHostSpinFanSpeedMetricHostLifeUsedDrivesMetricHostUsedSystemSpaceMetricHostUsedShareSpaceMetricHostUsedBackupSpaceMetricHostUsedSwapSpaceMetricHostUsedDiskOpsMetricHostUsedNetworkMetricHostRunningTimeMetricHostTemperatureMetricHostServicesMetricHostServicesMaxMemoryMetricServiceMetricServiceBackupStatusMetricServiceHealthStatusMetricServiceConfiguredStatusMetricServiceNameMetricServiceVersionMetricServiceUsedProcessorMetricServiceUsedMemoryMetricServiceUsedDiskOpsMetricServiceUsedNetworkMetricServiceUpTimeMetricServiceMaxMemoryMetricServiceRestartCountMetricHostFailedDrivesMetricMax"

var _ID_index = [...]uint16{0, 4, 14, 37, 57, 82, 102, 124, 147, 172, 194, 218, 243, 267, 292, 315, 336, 357, 378, 399, 417, 444, 457, 482, 507, 536, 553, 573, 599, 622, 646, 670, 689, 711, 736, 758, 767}

func (i ID) String() string {
	idx := int(i) - -1
	if i < -1 || idx >= len(_ID_index)-1 {
		return "ID(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ID_name[_ID_index[idx]:_ID_index[idx+1]]
}
