x-common: &common
  # Defined: [/asystem/.env_fab](https://github.com/ggear/asystem/blob/master/.env_fab)
  image: mlflow:${SERVICE_VERSION_ABSOLUTE}
  init: true
  environment:
    - TZ=Australia/Perth
    - MLFLOW_SERVICE
    - MLFLOW_HTTP_PORT
    - MLFLOW_BACKEND_STORE_URI
    - MLFLOW_DEFAULT_ARTIFACT_ROOT
    - MLFLOW_TRACKING_URI
    - MLFLOW_REPOSITORY_URI
  volumes:
    - ${SERVICE_DATA_DIR}/bootstrap.sh:/bootstrap/bootstrap.sh
    - ${MLFLOW_DEFAULT_ARTIFACT_ROOT_SERVER}:${MLFLOW_DEFAULT_ARTIFACT_ROOT}
  logging:
    driver: "json-file"
    options:
      max-file: "5"
      max-size: "100m"
services:
  mlflow:
    container_name: mlflow
    <<: *common
    restart: ${SERVICE_RESTART}
    ports:
      - ${MLFLOW_HTTP_PORT}:5000
    healthcheck:
      test: /asystem/etc/healthcheck.sh
      interval: 2m
      timeout: 10s
      retries: 3
      start_period: 1m
      start_interval: 10s
    deploy:
      resources:
        limits:
          memory: 2G
  mlflow_bootstrap:
    container_name: mlflow_bootstrap
    <<: *common
    restart: 'no'
    entrypoint: /bin/bash
    command:
      - /bootstrap/bootstrap.sh
    depends_on:
      - mlflow