# https://github.com/adferrand/dnsrobocert/releases
version: '3.7'
services:
  letsencrypt:
    container_name: letsencrypt
    image: adferrand/dnsrobocert:3.24.1
    init: true
    environment:
      - TZ=Australia/Perth
      - CLOUDFLARE_TOKEN
      - LETSENCRYPT_STAGING
      - NGINX_SERVICE
      - UDMUTILITIES_SERVICE
    restart: ${SERVICE_RESTART}
    volumes:
      - ${SERVICE_DATA_DIR}/letsencrypt:/etc/letsencrypt
      - ${SERVICE_DATA_DIR}/dnsrobocert:/etc/dnsrobocert
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "100m"
    deploy:
      resources:
        limits:
          memory: 256M
