services:
  internet:
    image: internet:${SERVICE_VERSION_ABSOLUTE}
    container_name: internet
    init: true
    restart: ${SERVICE_RESTART}
    environment:
      - TZ=Australia/Perth
      - VERNEMQ_SERVICE
      - VERNEMQ_PORT
      - INFLUXDB_SERVICE
      - INFLUXDB_HTTP_PORT
      - INFLUXDB_ORG
      - INFLUXDB_BUCKET_HOST_PRIVATE
      - INFLUXDB_TOKEN
    volumes:
      - ${SERVICE_DATA_DIR}/telegraf.conf:/etc/telegraf/telegraf.conf
      - ${SERVICE_DATA_DIR}:/asystem/runtime
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "100m"
    deploy:
      resources:
        limits:
          memory: 256M