services:
  internet:
    image: internet:${SERVICE_VERSION_ABSOLUTE}
    container_name: internet
    init: true
    restart: ${SERVICE_RESTART}
    environment:
      - TZ=Australia/Perth
      - VERNEMQ_SERVICE
      - VERNEMQ_API_PORT
      - INFLUXDB_SERVICE
      - INFLUXDB_HTTP_PORT
      - INFLUXDB_ORG
      - INFLUXDB_BUCKET_HOST_PRIVATE
      - INFLUXDB_TOKEN
    volumes:
      - ${SERVICE_DATA_DIR}:/asystem/mnt:rw
    healthcheck:
      test: /asystem/etc/checkhealthy.sh
      interval: 2m
      timeout: 30s
      retries: 3
      start_period: 1m
      start_interval: 10s
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "100m"
    deploy:
      resources:
        limits:
          memory: 256M