#######################################################################################
# WARNING: This file is written to by the build process, any manual edits will be lost!
#######################################################################################
compensation:
  #####################################################################################
  compensation_sensor_roof_temperature:
    unique_id: compensation_sensor_roof_temperature
    source: sensor.roof_temperature
    precision: 1
    data_points:
      - [ 1, 1 ]
      - [ 2, 2 ]
  #####################################################################################
  compensation_sensor_ada_temperature:
    unique_id: compensation_sensor_ada_temperature
    source: sensor.ada_temperature
    precision: 1
    data_points:
      - [ 1, 1 ]
      - [ 2, 2 ]
  #####################################################################################
  compensation_sensor_edwin_temperature:
    unique_id: compensation_sensor_edwin_temperature
    source: sensor.edwin_temperature
    precision: 1
    data_points:
      - [ 1, 1 ]
      - [ 2, 2 ]
  #####################################################################################
  compensation_sensor_bertram_2_office_lounge_temperature:
    unique_id: compensation_sensor_bertram_2_office_lounge_temperature
    source: sensor.bertram_2_office_lounge_temperature
    precision: 1
    data_points:
      - [ 1, 1 ]
      - [ 2, 2 ]
  #####################################################################################
  compensation_sensor_parents_temperature:
    unique_id: compensation_sensor_parents_temperature
    source: sensor.parents_temperature
    precision: 1
    data_points:
      - [ 1, 1 ]
      - [ 2, 2 ]
  #####################################################################################
  compensation_sensor_bertram_2_office_temperature:
    unique_id: compensation_sensor_bertram_2_office_temperature
    source: sensor.bertram_2_office_temperature
    precision: 1
    data_points:
      - [ 1, 1 ]
      - [ 2, 2 ]
  #####################################################################################
  compensation_sensor_bertram_2_kitchen_temperature:
    unique_id: compensation_sensor_bertram_2_kitchen_temperature
    source: sensor.bertram_2_kitchen_temperature
    precision: 1
    data_points:
      - [ 1, 1 ]
      - [ 2, 2 ]
  #####################################################################################
  compensation_sensor_bertram_2_office_pantry_temperature:
    unique_id: compensation_sensor_bertram_2_office_pantry_temperature
    source: sensor.bertram_2_office_pantry_temperature
    precision: 1
    data_points:
      - [ 1, 1 ]
      - [ 2, 2 ]
  #####################################################################################
  compensation_sensor_bertram_2_office_dining_temperature:
    unique_id: compensation_sensor_bertram_2_office_dining_temperature
    source: sensor.bertram_2_office_dining_temperature
    precision: 1
    data_points:
      - [ 1, 1 ]
      - [ 2, 2 ]
  #####################################################################################
  compensation_sensor_laundry_temperature:
    unique_id: compensation_sensor_laundry_temperature
    source: sensor.laundry_temperature
    precision: 1
    data_points:
      - [ 1, 1 ]
      - [ 2, 2 ]
  #####################################################################################
  compensation_sensor_deck_festoons_plug_temperature:
    unique_id: compensation_sensor_deck_festoons_plug_temperature
    source: sensor.deck_festoons_plug_temperature
    precision: 1
    data_points:
      - [ 1, 1 ]
      - [ 2, 2 ]
  #####################################################################################
  compensation_sensor_bertram_2_office_basement_temperature:
    unique_id: compensation_sensor_bertram_2_office_basement_temperature
    source: sensor.bertram_2_office_basement_temperature
    precision: 1
    data_points:
      - [ 1, 1 ]
      - [ 2, 2 ]
  #####################################################################################
  compensation_sensor_rack_top_temperature:
    unique_id: compensation_sensor_rack_top_temperature
    source: sensor.rack_top_temperature
    precision: 1
    data_points:
      - [ 1, 1 ]
      - [ 2, 2 ]
  #####################################################################################
  compensation_sensor_rack_bottom_temperature:
    unique_id: compensation_sensor_rack_bottom_temperature
    source: sensor.rack_bottom_temperature
    precision: 1
    data_points:
      - [ 1, 1 ]
      - [ 2, 2 ]
  #####################################################################################
  compensation_sensor_rack_external_temperature:
    unique_id: compensation_sensor_rack_external_temperature
    source: sensor.rack_external_temperature
    precision: 1
    data_points:
      - [ 1, 1 ]
      - [ 2, 2 ]
  #####################################################################################
  compensation_sensor_rack_temperature:
    unique_id: compensation_sensor_rack_temperature
    source: sensor.rack_temperature
    precision: 1
    data_points:
      - [ 1, 1 ]
      - [ 2, 2 ]
  #####################################################################################
  compensation_sensor_landing_festoons_plug_temperature:
    unique_id: compensation_sensor_landing_festoons_plug_temperature
    source: sensor.landing_festoons_plug_temperature
    precision: 1
    data_points:
      - [ 1, 1 ]
      - [ 2, 2 ]
  #####################################################################################
