#######################################################################################
# WARNING: This file is written to by the build process, any manual edits will be lost!
#######################################################################################
compensation:
  #####################################################################################
  compensation_sensor_roof_temperature:
    unique_id: compensation_sensor_roof_temperature
    source: sensor.roof_temperature
    precision: 1
    data_points:
      - [ 1, 1 ]
      - [ 2, 2 ]
  #####################################################################################
  compensation_sensor_ada_temperature:
    unique_id: compensation_sensor_ada_temperature
    source: sensor.ada_temperature
    precision: 1
    data_points:
      - [ 7.9, 8.7 ]
      - [ 16.9, 18 ]
  #####################################################################################
  compensation_sensor_edwin_temperature:
    unique_id: compensation_sensor_edwin_temperature
    source: sensor.edwin_temperature
    precision: 1
    data_points:
      - [ 9, 8.7 ]
      - [ 18.1, 18 ]
  #####################################################################################
  compensation_sensor_bertram_2_office_lounge_temperature:
    unique_id: compensation_sensor_bertram_2_office_lounge_temperature
    source: sensor.bertram_2_office_lounge_temperature
    precision: 1
    data_points:
      - [ 8.7, 8.7 ]
      - [ 18, 18 ]
  #####################################################################################
  compensation_sensor_parents_temperature:
    unique_id: compensation_sensor_parents_temperature
    source: sensor.parents_temperature
    precision: 1
    data_points:
      - [ 8.7, 8.7 ]
      - [ 17.8, 18 ]
  #####################################################################################
  compensation_sensor_bertram_2_office_temperature:
    unique_id: compensation_sensor_bertram_2_office_temperature
    source: sensor.bertram_2_office_temperature
    precision: 1
    data_points:
      - [ 9.1, 8.7 ]
      - [ 18.2, 18 ]
  #####################################################################################
  compensation_sensor_bertram_2_kitchen_temperature:
    unique_id: compensation_sensor_bertram_2_kitchen_temperature
    source: sensor.bertram_2_kitchen_temperature
    precision: 1
    data_points:
      - [ 9.2, 8.7 ]
      - [ 18.1, 18 ]
  #####################################################################################
  compensation_sensor_bertram_2_office_pantry_temperature:
    unique_id: compensation_sensor_bertram_2_office_pantry_temperature
    source: sensor.bertram_2_office_pantry_temperature
    precision: 1
    data_points:
      - [ 8.5, 8.7 ]
      - [ 17.9, 18 ]
  #####################################################################################
  compensation_sensor_bertram_2_office_dining_temperature:
    unique_id: compensation_sensor_bertram_2_office_dining_temperature
    source: sensor.bertram_2_office_dining_temperature
    precision: 1
    data_points:
      - [ 8.7, 8.7 ]
      - [ 18, 18 ]
  #####################################################################################
  compensation_sensor_laundry_temperature:
    unique_id: compensation_sensor_laundry_temperature
    source: sensor.laundry_temperature
    precision: 1
    data_points:
      - [ 8.9, 8.7 ]
      - [ 18, 18 ]
  #####################################################################################
  compensation_sensor_wardrobe_temperature:
    unique_id: compensation_sensor_wardrobe_temperature
    source: sensor.wardrobe_temperature
    precision: 1
    data_points:
      - [ 9.2, 8.7 ]
      - [ 18.4, 18 ]
  #####################################################################################
  compensation_sensor_utility_temperature:
    unique_id: compensation_sensor_utility_temperature
    source: sensor.utility_temperature
    precision: 1
    data_points:
      - [ 8.4, 8.7 ]
      - [ 17.6, 18 ]
  #####################################################################################
  compensation_sensor_deck_festoons_plug_temperature:
    unique_id: compensation_sensor_deck_festoons_plug_temperature
    source: sensor.deck_festoons_plug_temperature
    precision: 1
    data_points:
      - [ 9, 8.7 ]
      - [ 18.2, 18 ]
  #####################################################################################
  compensation_sensor_bertram_2_office_basement_temperature:
    unique_id: compensation_sensor_bertram_2_office_basement_temperature
    source: sensor.bertram_2_office_basement_temperature
    precision: 1
    data_points:
      - [ 8.7, 8.7 ]
      - [ 18, 18 ]
  #####################################################################################
  compensation_sensor_landing_festoons_plug_temperature:
    unique_id: compensation_sensor_landing_festoons_plug_temperature
    source: sensor.landing_festoons_plug_temperature
    precision: 1
    data_points:
      - [ 8.4, 8.7 ]
      - [ 17.7, 18 ]
  #####################################################################################
  compensation_sensor_host_lia_temperature:
    unique_id: compensation_sensor_host_lia_temperature
    source: sensor.host_lia_temperature
    precision: 1
    data_points:
      - [ 1, 1 ]
      - [ 2, 2 ]
  #####################################################################################
  compensation_sensor_host_flo_temperature:
    unique_id: compensation_sensor_host_flo_temperature
    source: sensor.host_flo_temperature
    precision: 1
    data_points:
      - [ 1, 1 ]
      - [ 2, 2 ]
  #####################################################################################
  compensation_sensor_host_meg_temperature:
    unique_id: compensation_sensor_host_meg_temperature
    source: sensor.host_meg_temperature
    precision: 1
    data_points:
      - [ 1, 1 ]
      - [ 2, 2 ]
  #####################################################################################
  compensation_sensor_rack_top_temperature:
    unique_id: compensation_sensor_rack_top_temperature
    source: sensor.rack_top_temperature
    precision: 1
    data_points:
      - [ 8.4, 8.7 ]
      - [ 17.6, 18 ]
  #####################################################################################
  compensation_sensor_rack_bottom_temperature:
    unique_id: compensation_sensor_rack_bottom_temperature
    source: sensor.rack_bottom_temperature
    precision: 1
    data_points:
      - [ 8.4, 8.7 ]
      - [ 17.6, 18 ]
  #####################################################################################
