#######################################################################################
# WARNING: This file is written to by the build process, any manual edits will be lost!
#######################################################################################
fan:
  - platform: group
    name: Deck Fan
    unique_id: deck_fan
    entities:
      - fan.deck_east_fan
      - fan.deck_west_fan
#######################################################################################
tplink:
  discovery: false
  switch:
    - host: 10.0.6.70
    - host: 10.0.6.71
    - host: 10.0.6.72
    - host: 10.0.6.73
    - host: 10.0.6.74
    - host: 10.0.6.75
    - host: 10.0.6.76
    - host: 10.0.6.77
    - host: 10.0.6.78
    - host: 10.0.6.79
    - host: 10.0.6.80
    - host: 10.0.6.81
    - host: 10.0.6.82
    - host: 10.0.6.83
    - host: 10.0.6.84
    - host: 10.0.6.85
    - host: 10.0.6.86
    - host: 10.0.6.87
    - host: 10.0.6.88
    - host: 10.0.6.89
#######################################################################################
