#######################################################################################
# WARNING: This file is written to by the build process, any manual edits will be lost!
#######################################################################################
powercalc:
  force_update_frequency: 00:00:05
  enable_autodiscovery: false
  power_sensor_precision: 1
  energy_sensor_precision: 3
  power_sensor_naming: '{} Power'
  energy_sensor_naming: '{} Energy'
  create_utility_meters: true
  utility_meter_types:
    - daily
    - weekly
    - monthly
    - yearly
######################################################################################
sensor:
  ####################################################################################
  - platform: powercalc
    create_group: Home
    entities:
      ################################################################################
      - create_group: Home Base
        entities:
          ############################################################################
          - create_group: Fans
            entities:
              ########################################################################
              - create_group: Ada Fans
                entities:
                  - entity_id: fan.ada_fan
                    standby_power: 1.3
                    linear:
                      min_power: 2.5
                      max_power: 31.1
              ########################################################################
              - create_group: Edwin Fans
                entities:
                  - entity_id: fan.edwin_fan
                    standby_power: 1.3
                    linear:
                      min_power: 2.5
                      max_power: 31.1
              ########################################################################
              - create_group: Parents Fans
                entities:
                  - entity_id: fan.parents_fan
                    standby_power: 1.3
                    linear:
                      min_power: 2.5
                      max_power: 31.1
              ########################################################################
              - create_group: Lounge Fans
                entities:
                  - entity_id: fan.lounge_fan
                    standby_power: 1.3
                    linear:
                      min_power: 2.5
                      max_power: 31.1
              ########################################################################
              - create_group: Deck Fans
                entities:
                  - entity_id: fan.deck_east_fan
                    standby_power: 1.3
                    linear:
                      min_power: 2.5
                      max_power: 31.1
                  - entity_id: fan.deck_west_fan
                    standby_power: 1.3
                    linear:
                      min_power: 2.5
                      max_power: 31.1
          ############################################################################
          - create_group: Lights
            entities:
              ########################################################################
              - create_group: Ada Lights
                entities:
                  - entity_id: light.ada_fan
                    name: Ada Main Fan Light
                    unique_id: ada_main_light_fan
                    linear:
                      min_power: 0.5
                      max_power: 16.3
                  - entity_id: light.ada_lamp_bulb_1
              ########################################################################
              - create_group: Edwin Lights
                entities:
                  - entity_id: light.edwin_lamp_bulb_1
                  - entity_id: light.edwin_fan
                    name: Edwin Main Fan Light
                    unique_id: edwin_main_light_fan
                    linear:
                      min_power: 0.5
                      max_power: 16.3
                  - entity_id: light.edwin_night_light_bulb_1
              ########################################################################
              - create_group: Hallway Lights
                entities:
                  - entity_id: light.hallway_main_bulb_1
                  - entity_id: light.hallway_main_bulb_2
                  - entity_id: light.hallway_main_bulb_3
                  - entity_id: light.hallway_main_bulb_4
              ########################################################################
              - create_group: Dining Lights
                entities:
                  - entity_id: light.dining_main_bulb_1
                  - entity_id: light.dining_main_bulb_2
                  - entity_id: light.dining_main_bulb_3
                  - entity_id: light.dining_main_bulb_4
                  - entity_id: light.dining_main_bulb_5
                  - entity_id: light.dining_main_bulb_6
              ########################################################################
              - create_group: Lounge Lights
                entities:
                  - entity_id: light.lounge_main_bulb_1
                  - entity_id: light.lounge_main_bulb_2
                  - entity_id: light.lounge_main_bulb_3
                  - entity_id: light.lounge_fan
                    name: Lounge Fan Light
                    unique_id: lounge_light_fan
                    linear:
                      min_power: 0.5
                      max_power: 16.3
                  - entity_id: light.lounge_lamp_bulb_1
              ########################################################################
              - create_group: Parents Lights
                entities:
                  - entity_id: light.parents_main_bulb_1
                  - entity_id: light.parents_main_bulb_2
                  - entity_id: light.parents_main_bulb_3
              ########################################################################
              - create_group: Study Lights
                entities:
                  - entity_id: light.study_lamp_bulb_1
              ########################################################################
              - create_group: Kitchen Lights
                entities:
                  - entity_id: light.kitchen_main_bulb_1
                  - entity_id: light.kitchen_main_bulb_2
                  - entity_id: light.kitchen_main_bulb_3
                  - entity_id: light.kitchen_main_bulb_4
                  - entity_id: switch.kitchen_downlights
                    standby_power: 1.22
                    power_sensor_id: sensor.kitchen_downlights_current_consumption
                    energy_sensor_id: sensor.kitchen_downlights_total_consumption
              ########################################################################
              - create_group: Laundry Lights
                entities:
                  - entity_id: light.laundry_main_bulb_1
              ########################################################################
              - create_group: Pantry Lights
                entities:
                  - entity_id: light.pantry_main_bulb_1
              ########################################################################
              - create_group: Office Lights
                entities:
                  - entity_id: light.office_main_bulb_1
              ########################################################################
              - create_group: Bathroom Lights
                entities:
                  - entity_id: light.bathroom_main_bulb_1
              ########################################################################
              - create_group: Ensuite Lights
                entities:
                  - entity_id: light.ensuite_main_bulb_1
              ########################################################################
              - create_group: Wardrobe Lights
                entities:
                  - entity_id: light.wardrobe_main_bulb_1
              ########################################################################
              - create_group: Deck Lights
                entities:
                  - entity_id: switch.deck_festoons
              ########################################################################
              - create_group: Landing Lights
                entities:
                  - entity_id: switch.landing_festoons
          ############################################################################
          - create_group: Audio Visual Devices
            entities:
              ########################################################################
              - create_group: Lounge Audio Visual Devices
                entities:
                  - entity_id: switch.lounge_tv_outlet
                    standby_power: 1.22
                    power_sensor_id: sensor.lounge_tv_outlet_current_consumption
                    energy_sensor_id: sensor.lounge_tv_outlet_total_consumption
                  - entity_id: media_player.lounge_home
                    name: Lounge Home
              ########################################################################
              - create_group: Ada Audio Visual Devices
                entities:
                  - entity_id: media_player.ada_home
                    name: Ada Home
              ########################################################################
              - create_group: Edwin Audio Visual Devices
                entities:
                  - entity_id: media_player.edwin_home
                    name: Edwin Home
              ########################################################################
              - create_group: Parents Audio Visual Devices
                entities:
                  - entity_id: media_player.parents_home
                    model: Nest Hub 2gen
              ########################################################################
              - create_group: Kitchen Audio Visual Devices
                entities:
                  - entity_id: media_player.kitchen_home
                    model: Nest Hub 2gen
              ########################################################################
              - create_group: Office Audio Visual Devices
                entities:
                  - entity_id: media_player.office_home
                    name: Office Home
          ############################################################################
          - create_group: Power Plugs
            entities:
              ########################################################################
              - create_group: Study Power Plugs
                entities:
                  - entity_id: switch.study_outlet
                  - entity_id: switch.study_battery_charger
              ########################################################################
              - create_group: Office Power Plugs
                entities:
                  - entity_id: switch.office_outlet
              ########################################################################
              - create_group: Laundry Power Plugs
                entities:
                  - entity_id: switch.laundry_vacuum_charger
          ############################################################################
          - create_group: Whitegoods Continuous
            entities:
              ########################################################################
              - create_group: Kitchen Whitegoods Continuous
                entities:
                  - entity_id: switch.kitchen_fridge
                    standby_power: 1.22
                    power_sensor_id: sensor.kitchen_fridge_current_consumption
                    energy_sensor_id: sensor.kitchen_fridge_total_consumption
              ########################################################################
              - create_group: Deck Whitegoods Continuous
                entities:
                  - entity_id: switch.deck_freezer
                    standby_power: 1.22
                    power_sensor_id: sensor.deck_freezer_current_consumption
                    energy_sensor_id: sensor.deck_freezer_total_consumption
          ############################################################################
          - create_group: Servers & Network
            entities:
              ########################################################################
              - create_group: Rack Servers & Network
                entities:
                  - entity_id: switch.rack_outlet
                    standby_power: 1.22
                    power_sensor_id: sensor.rack_outlet_current_consumption
                    energy_sensor_id: sensor.rack_outlet_total_consumption
              ########################################################################
              - create_group: Roof Servers & Network
                entities:
                  - entity_id: switch.roof_network_switch
                    standby_power: 1.22
                    power_sensor_id: sensor.roof_network_switch_current_consumption
                    energy_sensor_id: sensor.roof_network_switch_total_consumption
      ################################################################################
      - create_group: Home Peak
        entities:
          ############################################################################
          - create_group: Heating & Cooling
            entities:
              ########################################################################
              - create_group: Bathroom Heating & Cooling
                entities:
                  - entity_id: switch.bathroom_rails
                    standby_power: 1.22
                    power_sensor_id: sensor.bathroom_rails_current_consumption
                    energy_sensor_id: sensor.bathroom_rails_total_consumption
          ############################################################################
          - create_group: Whitegoods Discretionary
            entities:
              ########################################################################
              - create_group: Kitchen Whitegoods Discretionary
                entities:
                  - entity_id: switch.kitchen_dish_washer
              ########################################################################
              - create_group: Laundry Whitegoods Discretionary
                entities:
                  - entity_id: switch.laundry_clothes_dryer
                  - entity_id: switch.laundry_washing_machine
  ####################################################################################
  - platform: powercalc
    create_group: Zombie
    entities:
      ################################################################################
      - create_group: Zombie Base
        entities:
          ############################################################################
          - create_group: Zombie Servers & Network
            entities:
              ########################################################################
              - create_group: Zombie Rack Servers & Network
                entities:
                  - entity_id: switch.rack_modem
  ####################################################################################
