#######################################################################################
# WARNING: This file is written to by the build process, any manual edits will be lost!
#######################################################################################
powercalc:
  force_update_frequency: 00:05:00
  create_utility_meters: false
  utility_meter_types:
    - daily
######################################################################################
sensor:
  ####################################################################################
  - platform: powercalc
    create_group: home
    entities:
      - create_group: home_base
        entities:
          - create_group: fans
            entities:
              - create_group: ada
                entities:
                  - entity_id: fan.ada_fan
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
