#######################################################################################
# WARNING: This file is written to by the build process, any manual edits will be lost!
#######################################################################################
powercalc:
  force_update_frequency: 00:05:00
  create_utility_meters: false
  utility_meter_types:
    - daily
######################################################################################
sensor:
  ####################################################################################
  - platform: powercalc
    create_group: home
    entities:
      ################################################################################
      - create_group: home_base
        entities:
          ############################################################################
          - create_group: fans
            entities:
              ########################################################################
              - create_group: ada_fans
                entities:
                  - entity_id: fan.ada_fan
                    standby_power: 1.3
                    linear:
                      min_power: 2.5
                      max_power: 31.1
              ########################################################################
              - create_group: edwin_fans
                entities:
                  - entity_id: fan.edwin_fan
                    standby_power: 1.3
                    linear:
                      min_power: 2.5
                      max_power: 31.1
              ########################################################################
              - create_group: parents_fans
                entities:
                  - entity_id: fan.parents_fan
                    standby_power: 1.3
                    linear:
                      min_power: 2.5
                      max_power: 31.1
              ########################################################################
              - create_group: kitchen_fans
                entities:
                  - entity_id: switch.kitchen_fan
              ########################################################################
              - create_group: lounge_fans
                entities:
                  - entity_id: fan.lounge_fan
                    standby_power: 1.3
                    linear:
                      min_power: 2.5
                      max_power: 31.1
              ########################################################################
              - create_group: deck_fans
                entities:
                  - entity_id: fan.deck_east_fan
                  - entity_id: fan.deck_west_fan
          ############################################################################
          - create_group: lights
            entities:
              ########################################################################
              - create_group: ada_lights
                entities:
                  - entity_id: light.ada_fan
                    linear:
                      min_power: 0.5
                      max_power: 16.3
                  - entity_id: light.ada_lamp_bulb_1
              ########################################################################
              - create_group: edwin_lights
                entities:
                  - entity_id: light.edwin_lamp_bulb_1
                  - entity_id: light.edwin_fan
                    linear:
                      min_power: 0.5
                      max_power: 16.3
                  - entity_id: light.edwin_night_light_bulb_1
              ########################################################################
              - create_group: hallway_lights
                entities:
                  - entity_id: light.hallway_main_bulb_1
                  - entity_id: light.hallway_main_bulb_2
                  - entity_id: light.hallway_main_bulb_3
                  - entity_id: light.hallway_main_bulb_4
              ########################################################################
              - create_group: dining_lights
                entities:
                  - entity_id: light.dining_main_bulb_1
                  - entity_id: light.dining_main_bulb_2
                  - entity_id: light.dining_main_bulb_3
                  - entity_id: light.dining_main_bulb_4
                  - entity_id: light.dining_main_bulb_5
                  - entity_id: light.dining_main_bulb_6
              ########################################################################
              - create_group: lounge_lights
                entities:
                  - entity_id: light.lounge_main_bulb_1
                  - entity_id: light.lounge_main_bulb_2
                  - entity_id: light.lounge_main_bulb_3
                  - entity_id: light.lounge_fan
                  - entity_id: light.lounge_lamp_bulb_1
              ########################################################################
              - create_group: parents_lights
                entities:
                  - entity_id: light.parents_main_bulb_1
                  - entity_id: light.parents_main_bulb_2
                  - entity_id: light.parents_main_bulb_3
              ########################################################################
              - create_group: study_lights
                entities:
                  - entity_id: light.study_lamp_bulb_1
              ########################################################################
              - create_group: kitchen_lights
                entities:
                  - entity_id: light.kitchen_main_bulb_1
                  - entity_id: light.kitchen_main_bulb_2
                  - entity_id: light.kitchen_main_bulb_3
                  - entity_id: light.kitchen_main_bulb_4
                  - entity_id: switch.kitchen_downlights
              ########################################################################
              - create_group: laundry_lights
                entities:
                  - entity_id: light.laundry_main_bulb_1
              ########################################################################
              - create_group: pantry_lights
                entities:
                  - entity_id: light.pantry_main_bulb_1
              ########################################################################
              - create_group: office_lights
                entities:
                  - entity_id: light.office_main_bulb_1
              ########################################################################
              - create_group: bathroom_lights
                entities:
                  - entity_id: light.bathroom_main_bulb_1
              ########################################################################
              - create_group: ensuite_lights
                entities:
                  - entity_id: light.ensuite_main_bulb_1
              ########################################################################
              - create_group: wardrobe_lights
                entities:
                  - entity_id: light.wardrobe_main_bulb_1
              ########################################################################
              - create_group: deck_lights
                entities:
                  - entity_id: switch.deck_festoons
              ########################################################################
              - create_group: landing_lights
                entities:
                  - entity_id: switch.landing_festoons
              ########################################################################
              - create_group: garden_lights
                entities:
                  - entity_id: light.garden_pedestals_bulb_1
                  - entity_id: light.garden_pedestals_bulb_2
                  - entity_id: light.garden_pedestals_bulb_3
                  - entity_id: light.garden_pedestals_bulb_4
              ########################################################################
              - create_group: tree_lights
                entities:
                  - entity_id: light.tree_spotlights_bulb_1
                  - entity_id: light.tree_spotlights_bulb_2
          ############################################################################
          - create_group: air_purifiers
            entities:
              ########################################################################
              - create_group: lounge_air_purifiers
                entities:
                  - entity_id: fan.lounge_air_purifier
              ########################################################################
              - create_group: dining_air_purifiers
                entities:
                  - entity_id: fan.dining_air_purifier
          ############################################################################
          - create_group: audio_visual_devices
            entities:
              ########################################################################
              - create_group: lounge_audio_visual_devices
                entities:
                  - entity_id: switch.lounge_tv_outlet
                  - entity_id: media_player.lounge_home
                  - entity_id: media_player.lg_webos_smart_tv
                  - entity_id: media_player.lounge_arc
              ########################################################################
              - create_group: ada_audio_visual_devices
                entities:
                  - entity_id: media_player.ada_home
              ########################################################################
              - create_group: edwin_audio_visual_devices
                entities:
                  - entity_id: media_player.edwin_home
              ########################################################################
              - create_group: parents_audio_visual_devices
                entities:
                  - entity_id: media_player.parents_home
                  - entity_id: media_player.parents_move
              ########################################################################
              - create_group: kitchen_audio_visual_devices
                entities:
                  - entity_id: media_player.kitchen_home
                  - entity_id: media_player.kitchen_move
                  - entity_id: media_player.kitchen_five
              ########################################################################
              - create_group: office_audio_visual_devices
                entities:
                  - entity_id: media_player.office_home
          ############################################################################
          - create_group: power plugs
            entities:
              ########################################################################
              - create_group: mobile_power plugs
                entities:
                  - entity_id: switch.various_adhoc_outlet
              ########################################################################
              - create_group: study_power plugs
                entities:
                  - entity_id: switch.study_outlet
                  - entity_id: switch.study_battery_charger
              ########################################################################
              - create_group: office_power plugs
                entities:
                  - entity_id: switch.office_outlet
              ########################################################################
              - create_group: laundry_power plugs
                entities:
                  - entity_id: switch.laundry_vacuum_charger
              ########################################################################
              - create_group: deck_power plugs
                entities:
                  - entity_id: switch.deck_fans_outlet
              ########################################################################
              - create_group: kitchen_power plugs
                entities:
                  - entity_id: switch.kitchen_fan_outlet
              ########################################################################
              - create_group: edwin_power plugs
                entities:
                  - entity_id: switch.edwin_wardrobe_outlet
          ############################################################################
          - create_group: whitegoods
            entities:
              ########################################################################
              - create_group: kitchen_whitegoods
                entities:
                  - entity_id: switch.kitchen_fridge
              ########################################################################
              - create_group: deck_whitegoods
                entities:
                  - entity_id: switch.deck_freezer
          ############################################################################
          - create_group: server_network
            entities:
              ########################################################################
              - create_group: rack_server_network
                entities:
                  - entity_id: switch.rack_fans
                  - entity_id: switch.rack_outlet
              ########################################################################
              - create_group: roof_server_network
                entities:
                  - entity_id: switch.roof_network_switch
      ################################################################################
      - create_group: home_peak
        entities:
          ############################################################################
          - create_group: heating_cooling
            entities:
              ########################################################################
              - create_group: bathroom_heating_cooling
                entities:
                  - entity_id: switch.bathroom_rails
          ############################################################################
          - create_group: whitegoods
            entities:
              ########################################################################
              - create_group: kitchen_whitegoods
                entities:
                  - entity_id: switch.kitchen_dish_washer
              ########################################################################
              - create_group: laundry_whitegoods
                entities:
                  - entity_id: switch.laundry_clothes_dryer
                  - entity_id: switch.laundry_washing_machine
  ####################################################################################
  - platform: powercalc
    create_group: zombie
    entities:
      ################################################################################
      - create_group: zombie_base
        entities:
          ############################################################################
          - create_group: zombie_server_network
            entities:
              ########################################################################
              - create_group: zombie_rack_server_network
                entities:
                  - entity_id: switch.rack_modem
  ####################################################################################
