#######################################################################################
# WARNING: This file is written to by the build process, any manual edits will be lost!
#######################################################################################
template:
  #####################################################################################
  - sensor:
      #################################################################################
      - unique_id: utility_temperature_proxy
        device_class: battery
        state_class: measurement
        unit_of_measurement: "%"
        state: >-
          { states('sensor.utility_temperature') }
#######################################################################################
