x-common: &common
  image: grafana:${SERVICE_VERSION_ABSOLUTE}
  init: true
  user: root
  environment:
    - TZ=Australia/Perth
    - GF_SECURITY_ADMIN_USER=${GRAFANA_USER}
    - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_TOKEN}
    - GRAFANA_SERVICE
    - GRAFANA_HTTP_PORT
    - GRAFANA_URL
    - GRAFANA_URL_PUBLIC
    - GRAFANA_URL_PRIVATE
    - GRAFANA_DOMAIN
    - GRAFANA_DOMAIN_URL
    - GRAFANA_USER
    - GRAFANA_USER_PUBLIC
    - GRAFANA_USER_PRIVATE
    - GRAFANA_TOKEN
    - GRAFANA_TOKEN_PUBLIC
    - GRAFANA_TOKEN_PRIVATE
    - INFLUXDB_SERVICE
    - INFLUXDB_HTTP_PORT
    - INFLUXDB_ORG
    - INFLUXDB_BUCKET_HOME_PUBLIC
    - INFLUXDB_BUCKET_HOME_PRIVATE
    - INFLUXDB_BUCKET_DATA_PUBLIC
    - INFLUXDB_BUCKET_DATA_PRIVATE
    - INFLUXDB_BUCKET_HOST_PRIVATE
    - INFLUXDB_USER_PRIVATE
    - INFLUXDB_USER_PUBLIC
    - INFLUXDB_TOKEN
    - INFLUXDB_TOKEN_PUBLIC_V1
    - INFLUXDB_TOKEN_PUBLIC_V2
  volumes:
    - ${SERVICE_DATA_DIR}:/asystem/mnt
    - ${SERVICE_DATA_DIR}/config/settings.yaml:/root/.config/grizzly/settings.yaml
  logging:
    driver: "json-file"
    options:
      max-file: "5"
      max-size: "100m"
services:
  grafana:
    container_name: grafana
    <<: *common
    restart: ${SERVICE_RESTART}
    ports:
      - ${GRAFANA_HTTP_PORT}:${GRAFANA_HTTP_PORT}
    healthcheck:
      test: /asystem/etc/checkready.sh
      interval: 2m
      timeout: 30s
      retries: 3
      start_period: 1m
      start_interval: 10s
    deploy:
      resources:
        limits:
          memory: 512M
  grafana_bootstrap:
    container_name: grafana_bootstrap
    <<: *common
    restart: 'no'
    entrypoint: bash
    command: /asystem/etc/bootstrap.sh
    depends_on:
      - grafana
