version: '3.7'
services:
  grafana:
    container_name: grafana
    image: grafana/grafana:7.1.3
    init: true
    restart: ${RESTART}
    environment:
      - TZ=Australia/Perth
      - GF_SECURITY_ADMIN_USER=asystem
      - GF_SECURITY_ADMIN_PASSWORD=asystem
    volumes:
      - ${DATA_DIR}:/var/lib/grafana
    ports:
      - 3000:3000
