version: '3.7'
services:
  grafana:
    container_name: grafana
    image: grafana/grafana:7.4.3
    init: true
    restart: ${RESTART}
    environment:
      - TZ=Australia/Perth
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_KEY}
    volumes:
      - ${DATA_DIR}/custom.ini:/etc/grafana/grafana.ini
      - ${DATA_DIR}/dashboards/dashboard_home.json:/etc/grafana/dashboard_home.json
    ports:
      - ${GRAFANA_PORT}:${GRAFANA_PORT}
    deploy:
      resources:
        limits:
          memory: 5G