version: '3.7'
services:
  grafana:
    container_name: grafana
    image: grafana:${SERVICE_VERSION_ABSOLUTE}
    init: true
    restart: ${SERVICE_RESTART}
    environment:
      - TZ=Australia/Perth
      - GRAFANA_HOST
      - GRAFANA_PORT
      - GRAFANA_URL
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_KEY}
      - INFLUXDB_HOST
      - INFLUXDB_PORT
      - INFLUXDB_ORG
      - INFLUXDB_BUCKET_HOME_PUBLIC
      - INFLUXDB_BUCKET_HOME_PRIVATE
      - INFLUXDB_BUCKET_DATA_PUBLIC
      - INFLUXDB_BUCKET_DATA_PRIVATE
      - INFLUXDB_BUCKET_HOST_PRIVATE
      - INFLUXDB_USER_ALL
      - INFLUXDB_USER_PUBLIC
      - INFLUXDB_TOKEN
      - INFLUXDB_TOKEN_PUBLIC_V1
      - INFLUXDB_TOKEN_PUBLIC_V2
    volumes:
      - ${SERVICE_DATA_DIR}/bootstrap.sh:/bootstrap/bootstrap.sh
      - ${SERVICE_DATA_DIR}/custom.ini:/etc/grafana/grafana.ini
      - ${SERVICE_DATA_DIR}/dashboards/dashboard_home.json:/etc/grafana/dashboard_home.json
    ports:
      - ${GRAFANA_PORT}:${GRAFANA_PORT}
    deploy:
      resources:
        limits:
          memory: 5G
  grafana_bootstrap:
    container_name: grafana_bootstrap
    image: grafana:${SERVICE_VERSION_ABSOLUTE}
    init: true
    restart: ${SERVICE_RESTART}
    user: root
    environment:
      - TZ=Australia/Perth
      - GRAFANA_HOST
      - GRAFANA_PORT
      - GRAFANA_URL
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_KEY}
      - INFLUXDB_HOST
      - INFLUXDB_PORT
      - INFLUXDB_ORG
      - INFLUXDB_BUCKET_HOME_PUBLIC
      - INFLUXDB_BUCKET_HOME_PRIVATE
      - INFLUXDB_BUCKET_DATA_PUBLIC
      - INFLUXDB_BUCKET_DATA_PRIVATE
      - INFLUXDB_BUCKET_HOST_PRIVATE
      - INFLUXDB_USER_ALL
      - INFLUXDB_USER_PUBLIC
      - INFLUXDB_TOKEN
      - INFLUXDB_TOKEN_PUBLIC_V1
      - INFLUXDB_TOKEN_PUBLIC_V2
    volumes:
      - ${SERVICE_DATA_DIR}/bootstrap.sh:/bootstrap/bootstrap.sh
    entrypoint: /bin/bash
    command:
      - /bootstrap/bootstrap.sh
    depends_on:
      - grafana