version: '3.7'
services:
  redpanda:
    container_name: redpanda
    image: docker.vectorized.io/vectorized/redpanda:v21.6.5
    init: true
    restart: ${SERVICE_RESTART}
    environment:
      - TZ=Australia/Perth
    ports:
      - ${REDPANDA_PORT}:${REDPANDA_PORT}
    deploy:
      resources:
        limits:
          memory: 5G