host: 0.0.0.0
port: 8091
save_on_exit: True
save_seconds: -1
model_pull_seconds: 1
plugin:
  fronius:
    poll_seconds: 1
    buffer_ticks: 60
    history_partitions: 14
    history_ticks: 3500000
    history_partition_seconds: 86400
    repeat_seconds: -1
    publish_ticks: -1
  kasa:
    poll_seconds: 1
    buffer_ticks: 30
    history_partitions: 14
    history_ticks: 3500000
    history_partition_seconds: 86400
    repeat_seconds: -1
    publish_ticks: -1
  davis:
    poll_seconds: -1
    buffer_ticks: 30
    history_partitions: 14
    history_ticks: 900000
    history_partition_seconds: 86400
    repeat_seconds: -1
    publish_ticks: -1
  netatmo:
    poll_seconds: 1
    buffer_ticks: 10
    history_partitions: 14
    history_ticks: 900000
    history_partition_seconds: 86400
    repeat_seconds: -1
    publish_ticks: -1
  darksky:
    poll_seconds: 1
    buffer_ticks: 10
    history_partitions: 14
    history_ticks: 20000
    history_partition_seconds: 86400
    repeat_seconds: -1
    publish_ticks: -1
  speedtest:
    poll_seconds: -1
    buffer_ticks: 30
    history_partitions: 14
    history_ticks: 900000
    history_partition_seconds: 86400
    repeat_seconds: -1
    publish_ticks: -1

  # TODO: Disable until models retrained with new darksky features
  #  energyforecast:
  #    poll_seconds: 1
  #    buffer_ticks: 10
  #    history_partitions: 14
  #    history_ticks: 20000
  #    history_partition_seconds: 86400
  #    repeat_seconds: -1
  #    publish_ticks: -1
