host: 0.0.0.0
port: 8091
publish_host: 5.196.95.208
publish_port: 1883
publish_batch_seconds: 10
publish_status_topic: 'anode/status'
publish_push_data_topic: 'haas/sensor/state'
publish_push_metadata_topic: 'haas/sensor/config'
publish_batch_datum_topic: 'asystem/anode/amodel'
plugin:
  fronius:
    poll_seconds: 100
    buffer_ticks: 10
    history_partitions: 100000000000000
    history_ticks: 100000000000000
    history_partition_seconds: 9999999999
    repeat_seconds: -1
    publish_ticks: -1
