version: '3.7'
services:
  telegraf:
    container_name: telegraf
    image: telegraf:1.15.3
    init: true
    restart: ${RESTART}
    environment:
      - TZ=Australia/Perth
      - HOST_ETC=/hostfs/etc
      - HOST_PROC=/hostfs/proc
      - HOST_SYS=/hostfs/sys
      - HOST_VAR=/hostfs/var
      - HOST_RUN=/hostfs/run
      - HOST_MOUNT_PREFIX=/hostfs
    volumes:
      - /:/hostfs:ro
      - ${DATA_DIR}/telegraf.conf:/etc/telegraf/telegraf.conf
