[package]

name = "solaredge"
version = "0.0.0-SNAPSHOT"

[dependencies]
chrono = "0.4"
tokio = { version = "1.5.0", features = ["full"] }

[[bin]]
name = "solaredge"
path = "src/main/rust/main.rs"

[[test]]
name = "solaredge_test"
path = "src/test/rust/unit/unit_tests.rs"
