# https://github.com/redpanda-data/redpanda/releases
version: '3.7'
services:
  redpanda:
    container_name: redpanda
    image: vectorized/redpanda:v21.10.1
    init: true
    restart: ${SERVICE_RESTART}
    environment:
      - TZ=Australia/Perth
    ports:
      - ${REDPANDA_PORT}:${REDPANDA_PORT}
    deploy:
      resources:
        limits:
          memory: 5G