version: '3.7'
x-common: &common
  image: grafana:${SERVICE_VERSION_ABSOLUTE}
  init: true
  user: root
  environment:
    - TZ=Australia/Perth
    - GF_SECURITY_ADMIN_USER=${GRAFANA_USER}
    - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_KEY}
    - GRAFANA_IP
    - GRAFANA_HTTP_PORT
    - GRAFANA_URL
    - GRAFANA_URL_PUBLIC
    - GRAFANA_URL_PRIVATE
    - GRAFANA_USER_PUBLIC
    - GRAFANA_USER_PRIVATE
    - GRAFANA_KEY_PUBLIC
    - GRAFANA_KEY_PRIVATE
    - INFLUXDB_IP
    - INFLUXDB_HTTP_PORT
    - INFLUXDB_ORG
    - INFLUXDB_BUCKET_HOME_PUBLIC
    - INFLUXDB_BUCKET_HOME_PRIVATE
    - INFLUXDB_BUCKET_DATA_PUBLIC
    - INFLUXDB_BUCKET_DATA_PRIVATE
    - INFLUXDB_BUCKET_HOST_PRIVATE
    - INFLUXDB_USER_PRIVATE
    - INFLUXDB_USER_PUBLIC
    - INFLUXDB_TOKEN
    - INFLUXDB_TOKEN_PUBLIC_V1
    - INFLUXDB_TOKEN_PUBLIC_V2
  logging:
    driver: "json-file"
    options:
      max-file: "5"
      max-size: "100m"
services:
  grafana:
    container_name: grafana
    <<: *common
    restart: ${SERVICE_RESTART}
    volumes:
      - ${SERVICE_DATA_DIR}/bootstrap.sh:/bootstrap/bootstrap.sh
      - ${SERVICE_DATA_DIR}/grafana.ini:/etc/grafana/grafana.ini
      - ${SERVICE_DATA_DIR}/dashboards/dashboard_home.json:/etc/grafana/dashboard_home.json
    ports:
      - ${GRAFANA_HTTP_PORT}:${GRAFANA_HTTP_PORT}
    deploy:
      resources:
        limits:
          memory: 1G
  grafana_bootstrap:
    container_name: grafana_bootstrap
    <<: *common
    restart: 'no'
    volumes:
      - ${SERVICE_DATA_DIR}/bootstrap.sh:/bootstrap/bootstrap.sh
    entrypoint: /bin/bash
    command:
      - /bootstrap/bootstrap.sh
    depends_on:
      - grafana
