x-common: &common
  image: supervisor:${SERVICE_VERSION_ABSOLUTE}
  init: true
  environment:
    - TZ=Australia/Perth
    - HOST_NAME
    - VERNEMQ_SERVICE
    - VERNEMQ_API_PORT
    - INFLUXDB_SERVICE
    - INFLUXDB_HTTP_PORT
  volumes:
    - ${SERVICE_DATA_DIR}:/asystem/mnt
    - /:/${SUPERVISOR_HOST_FS}:ro
    - /var/run/docker.sock:/var/run/docker.sock
  logging:
    driver: "json-file"
    options:
      max-file: "5"
      max-size: "100m"
services:
  supervisor:
    container_name: supervisor
    <<: *common
    restart: ${SERVICE_RESTART}
    healthcheck:
      test: /asystem/etc/checkhealthy.sh
      interval: 2m
      timeout: 30s
      retries: 3
      start_period: 1m
      start_interval: 10s
    deploy:
      resources:
        limits:
          memory: 256M
  supervisor_bootstrap:
    container_name: supervisor_bootstrap
    <<: *common
    restart: 'no'
    entrypoint: bash
    command: /asystem/etc/bootstrap.sh
    depends_on:
      - supervisor
