#######################################################################################
default_config:
#######################################################################################
homeassistant:
  name: 'Home'
  latitude: -31.92
  longitude: 116.08
  elevation: 430
  unit_system: 'metric'
  currency: 'AUD'
  country: 'AU'
  internal_url: !env_var HOMEASSISTANT_INTERNAL_URL
  external_url: !env_var HOMEASSISTANT_EXTERNAL_URL
  customize: !include customise.yaml
  packages: !include_dir_named custom_packages
#######################################################################################
http:
  server_port: !env_var HOMEASSISTANT_HTTP_PORT
  use_x_forwarded_for: true
  trusted_proxies:
    - '127.0.0.1'
    - '10.0.0.0/16'
  cors_allowed_origins:
    - 'https://janeandgraham.com'
    - 'https://home.janeandgraham.com'
  ip_ban_enabled: true
  login_attempts_threshold: 3
#######################################################################################
tts:
  - platform: 'google_translate'
#######################################################################################
recorder:
  db_url: !env_var HOMEASSISTANT_DB
  commit_interval: 120
  purge_keep_days: 1
  auto_purge: true
# TODO: Disabled all sensors in favour of redirecting to Grafana?
#  exclude:
#    entity_globs:
#      - sensor.*
#######################################################################################
influxdb:
  api_version: 2
  ssl: false
  host: !env_var INFLUXDB_HOST
  port: !env_var INFLUXDB_HTTP_PORT
  token: !env_var INFLUXDB_TOKEN
  organization: !env_var INFLUXDB_ORG
  bucket: !env_var INFLUXDB_BUCKET_HOME_PRIVATE
  precision: 's'
  measurement_attr: 'domain__device_class'
  default_measurement: 'sensor'
  tags:
    source: 'haas'
    version: !env_var SERVICE_VERSION_COMPACT
  tags_attributes:
    - 'state_class'
    - 'friendly_name'
    - 'unit_of_measurement'
  exclude:
    domains:
      - 'zone'
      - 'scene'
      - 'select'
    entity_globs:
      - '*_bass'
      - '*_treble'
      - '*_sim_*'
      - '*_microphone_level'
      - 'adaptive_lighting_bedroom_*'
      - 'roof_water_heater_booster_mqtt_connect_count'
      - 'roof_water_heater_booster_wifi_connect_count'
  ignore_attributes: !include influxdb-ignores.yaml
  #####################################################################################
mqtt:
# The UI is now used to configure MQTT
#  broker: !env_var VERNEMQ_HOST
#  port: !env_var VERNEMQ_PORT
#  client_id: 'hass'
#  discovery: true
#  discovery_prefix: 'haas/entity'
#  birth_message:
#    topic: 'hass/system/status'
#    payload: 'online'
#  will_message:
#    topic: 'hass/system/status'
#    payload: 'offline'
#######################################################################################
discovery:
  ignore:
    - 'homekit'
#######################################################################################
google_assistant:
  project_id: 'home-assistant-31854'
  service_account: !include .google_service_account.json
  report_state: false
  expose_by_default: false
  entity_config: !include haas-entities.yaml
#######################################################################################
automation: !include automations.yaml
#######################################################################################
panel_custom: !include ui-panel-custom.yaml
#######################################################################################
lovelace:
  mode: 'yaml'
  resources:
    - url: '/local/custom_ui/bom-weather-card.js?v=0.90a-HACKED'
      type: 'module'
    - url: '/local/custom_ui/layout-card/layout-card.js?v=2.4.1'
      type: 'module'
    - url: '/local/custom_ui/bom-radar-card/bom-radar-card.js?v=v1.5.0'
      type: 'module'
    - url: '/local/custom_ui/apexcharts-card/apexcharts-card.js?v=v1.10.0'
      type: 'module'
    - url: '/local/custom_ui/mini-graph-card/mini-graph-card-bundle.js?v=v0.10.0'
      type: 'module'
  dashboards:
    lovelace-generated:
      mode: 'yaml'
      filename: 'notexist.yaml'
      title: 'Generated'
      icon: 'mdi:tools'
      show_in_sidebar: true
      require_admin: true
#######################################################################################
logger:
  default: warn # critical/fatal/error/warning/warn/info/debug/notset
  logs:
    homeassistant.core: warn
    homeassistant.loader: error
    homeassistant.components.integration.sensor: error
    homeassistant.components.compensation.sensor: error
    homeassistant.components.websocket_api.http.connection: fatal
    homeassistant.components.recorder.migration: info
    homeassistant.components.sonos: error
    homeassistant.config_entries: error
    homeassistant.components.sensor: error
    custom_components.tplink: error

    homeassistant.components.google_assistant: debug
    homeassistant.components.google_assistant.http: debug
    google_assistant: debug

  #   custom_components.powercalc: info
  #   homeassistant.components.mqtt: info
  #   custom_components.adaptive_lighting: info
  #   custom_components.bureau_of_meteorology: info
  #   homeassistant.components.automation.electricity_smart_plug_polling: warn
  #####################################################################################
