#######################################################################################
# WARNING: This file is written to by the build process, any manual edits will be lost!
#######################################################################################
sensor.roof_temperature:
  name: Roof Temperature
  aliases: ['Roof Room Temperature', 'Temperature', 'Room Temperature']
  room: Roof
sensor.ada_temperature:
  name: Adas Temperature
  aliases: ['Adas Room Temperature', 'Temperature', 'Room Temperature']
  room: Ada
sensor.edwin_temperature:
  name: Edwins Temperature
  aliases: ['Edwins Room Temperature', 'Temperature', 'Room Temperature']
  room: Edwin
sensor.bertram_2_office_lounge_temperature:
  name: Lounge Temperature
  aliases: ['Lounge Room Temperature', 'Temperature', 'Room Temperature']
  room: Lounge
sensor.parents_temperature:
  name: Parents Temperature
  aliases: ['Parents Room Temperature', 'Temperature', 'Room Temperature']
  room: Parents
sensor.bertram_2_office_temperature:
  name: Office Temperature
  aliases: ['Office Room Temperature', 'Temperature', 'Room Temperature']
  room: Office
sensor.bertram_2_kitchen_temperature:
  name: Kitchen Temperature
  aliases: ['Kitchen Room Temperature', 'Temperature', 'Room Temperature']
  room: Kitchen
sensor.bertram_2_office_pantry_temperature:
  name: Pantry Temperature
  aliases: ['Pantry Room Temperature', 'Temperature', 'Room Temperature']
  room: Pantry
sensor.bertram_2_office_dining_temperature:
  name: Dining Temperature
  aliases: ['Dining Room Temperature', 'Temperature', 'Room Temperature']
  room: Dining
sensor.laundry_temperature:
  name: Laundry Temperature
  aliases: ['Laundry Room Temperature', 'Temperature', 'Room Temperature']
  room: Laundry
sensor.bertram_2_office_basement_temperature:
  name: Basement Temperature
  aliases: ['Basement Room Temperature', 'Temperature', 'Room Temperature']
  room: Basement
sensor.rack_temperature:
  name: Rack Temperature
  aliases: ['Rack Room Temperature', 'Temperature', 'Room Temperature']
  room: Rack
input_boolean.home_security:
  name: Home Secure
  aliases: ['Home Secure Mode', 'Secure', 'Secure Mode']
  room: Abode
input_boolean.home_movie:
  name: Home Movie
  aliases: ['Home Movie Mode', 'Movie', 'Movie Mode']
  room: Abode
input_boolean.home_sleep:
  name: Home Sleep
  aliases: ['Home Sleep Mode', 'Sleep', 'Sleep Mode']
  room: Abode
input_boolean.home_reset:
  name: Home Reset
  aliases: ['Home Reset Mode', 'Reset', 'Reset Mode']
  room: Abode
fan.ada_fan:
  name: Adas Fan
  aliases: ['Fan']
  room: Ada
fan.edwin_fan:
  name: Edwins Fan
  aliases: ['Fan']
  room: Edwin
fan.parents_fan:
  name: Parents Fan
  aliases: ['Fan']
  room: Parents
switch.kitchen_fan:
  name: Kitchen Fan
  aliases: ['Fan']
  room: Kitchen
fan.lounge_fan:
  name: Lounge Fan
  aliases: ['Fan']
  room: Lounge
fan.deck_fan:
  name: Deck Fans
  aliases: ['Fans']
  room: Deck
light.ada_fan_light:
  name: Adas Main Light
  aliases: ['Adas Main', 'Main Light', 'Main']
  room: Ada
light.ada_lamp:
  name: Ada Lamp
  aliases: ['Lamp']
  room: Zombie
light.edwin_lamp:
  name: Edwin Lamp
  aliases: ['Lamp']
  room: Zombie
light.edwin_fan_light:
  name: Edwins Main Light
  aliases: ['Edwins Main', 'Main Light', 'Main']
  room: Edwin
light.edwin_night_light:
  name: Edwin Night Light
  aliases: ['Night Light']
  room: Zombie
light.hallway_main:
  name: Hallway Main Light
  aliases: ['Hallway Main', 'Main Light', 'Main']
  room: Hallway
light.dining_main:
  name: Dining Main Light
  aliases: ['Dining Main', 'Main Light', 'Main']
  room: Dining
light.lounge_main:
  name: Lounge Main Light
  aliases: ['Lounge Main', 'Main Light', 'Main']
  room: Lounge
light.lounge_fan_light:
  name: Lounge Fan Light
  aliases: ['Lounge Fan', 'Fan Light', 'Fan']
  room: Zombie
light.lounge_lamp:
  name: Lounge Lamp
  aliases: ['Lamp']
  room: Zombie
light.parents_main:
  name: Parents Main Light
  aliases: ['Parents Main', 'Main Light', 'Main']
  room: Parents
light.kitchen_main:
  name: Kitchen Main Light
  aliases: ['Kitchen Main', 'Main Light', 'Main']
  room: Kitchen
switch.kitchen_downlights:
  name: Kitchen Downlights
  aliases: ['Downlights']
  room: Kitchen
light.laundry_main:
  name: Laundry Main Light
  aliases: ['Laundry Main', 'Main Light', 'Main']
  room: Laundry
light.pantry_main:
  name: Pantry Main Light
  aliases: ['Pantry Main', 'Main Light', 'Main']
  room: Pantry
light.office_main:
  name: Office Main Light
  aliases: ['Office Main', 'Main Light', 'Main']
  room: Office
light.bathroom_main:
  name: Bathroom Main Light
  aliases: ['Bathroom Main', 'Main Light', 'Main']
  room: Bathroom
light.ensuite_main:
  name: Ensuite Main Light
  aliases: ['Ensuite Main', 'Main Light', 'Main']
  room: Ensuite
light.wardrobe_main:
  name: Wardrobe Main Light
  aliases: ['Wardrobe Main', 'Main Light', 'Main']
  room: Wardrobe
switch.deck_festoons:
  name: Deck Lights
  aliases: ['Deck Festoons', 'Lights', 'Festoons']
  room: Deck
switch.landing_festoons:
  name: Landing Lights
  aliases: ['Landing Festoons', 'Lights', 'Festoons']
  room: Landing
light.garden_pedestals:
  name: Garden Lights
  aliases: ['Garden Pedestals', 'Lights', 'Pedestals']
  room: Garden
light.tree_spotlights:
  name: Tree Lights
  aliases: ['Tree Spotlights', 'Lights', 'Spotlights']
  room: Tree
switch.bathroom_rails:
  name: Bathroom Towel Rails
  aliases: ['Towel Rails']
  room: Bathroom
fan.lounge_air_purifier:
  name: Lounge Air Purifier
  aliases: ['Air Purifier']
  room: Lounge
fan.dining_air_purifier:
  name: Dining Air Purifier
  aliases: ['Air Purifier']
  room: Dining
input_boolean.lighting_reset_adaptive_lighting_ada_lamp:
  name: Ada Lamp Reset
  aliases: ['Lamp Reset']
  room: Zombie
input_boolean.lighting_reset_adaptive_lighting_edwin_lamp:
  name: Edwin Lamp Reset
  aliases: ['Lamp Reset']
  room: Zombie
input_boolean.lighting_reset_adaptive_lighting_edwin_night_light:
  name: Edwin Night Light Reset
  aliases: ['Night Light Reset']
  room: Zombie
input_boolean.lighting_reset_adaptive_lighting_hallway_main:
  name: Hallway Diagnostics
  aliases: ['Diagnostics']
  room: Hallway
input_boolean.lighting_reset_adaptive_lighting_dining_main:
  name: Dining Main Reset
  aliases: ['Main Reset']
  room: Dining
input_boolean.lighting_reset_adaptive_lighting_lounge_main:
  name: Lounge Main Reset
  aliases: ['Main Reset']
  room: Lounge
input_boolean.lighting_reset_adaptive_lighting_lounge_lamp:
  name: Home Lamp Reset
  aliases: ['Lamp Reset']
  room: Zombie
input_boolean.lighting_reset_adaptive_lighting_parents_main:
  name: Parents Main Reset
  aliases: ['Main Reset']
  room: Parents
input_boolean.lighting_reset_adaptive_lighting_kitchen_main:
  name: Kitchen Main Reset
  aliases: ['Main Reset']
  room: Kitchen
input_boolean.lighting_reset_adaptive_lighting_laundry_main:
  name: Laundry Main Reset
  aliases: ['Main Reset']
  room: Laundry
input_boolean.lighting_reset_adaptive_lighting_pantry_main:
  name: Pantry Main Reset
  aliases: ['Main Reset']
  room: Pantry
input_boolean.lighting_reset_adaptive_lighting_office_main:
  name: Office Main Reset
  aliases: ['Main Reset']
  room: Office
input_boolean.lighting_reset_adaptive_lighting_bathroom_main:
  name: Bathroom Main Reset
  aliases: ['Main Reset']
  room: Bathroom
input_boolean.lighting_reset_adaptive_lighting_ensuite_main:
  name: Ensuite Main Reset
  aliases: ['Main Reset']
  room: Ensuite
input_boolean.lighting_reset_adaptive_lighting_wardrobe_main:
  name: Wardrobe Main Reset
  aliases: ['Main Reset']
  room: Wardrobe
#######################################################################################
