- 'id'
- 'fps'
- 'end'
- 'icon'
- 'mode'
- 'model'
- 'start'
- 'count'
- 'total'
- 'types'
- 'zones'
- 'width'
- 'height'
- 'repeat'
- 'source'
- 'status'
- 'app_id'
- 'sources'
- 'user_id'
- 'shuffle'
- 'bitrate'
- 'current'
- 'is_group'
- 'dynamics'
- 'excludes'
- 'workdays'
- 'editable'
- 'entities'
- 'xy_color'
- 'hs_color'
- 'max_value'
- 'min_value'
- 'next_noon'
- 'entity_id'
- 'color_mode'
- 'last_reset'
- 'channel_id'
- 'queue_size'
- 'max_mireds'
- 'min_mireds'
- 'name_float'
- 'source_list'
- 'days_offset'
- 'attribution'
- 'integration'
- 'last_period'
- 'preset_mode'
- 'preset_modes'
- 'power_source'
- 'coefficients'
- 'access_token'
- 'cron_pattern'
- 'meter_period'
- 'next_dawn_str'
- 'next_dusk_str'
- 'next_midnight'
- 'group_members'
- 'source_domain'
- 'source_entity'
- 'count_sources'
- 'rgb_color_str'
- 'available_str'
- 'manual_control'
- 'queue_position'
- 'forecast_float'
- 'media_position'
- 'entity_picture'
- 'percentage_step'
- 'next_rising_str'
- 'next_dawn_float'
- 'next_dusk_float'
- 'color_temp_mired'
- 'calculation_mode'
- 'next_setting_str'
- 'media_content_id'
- 'areas_of_interest'
- 'color_temp_kelvin'
- 'postal_code_float'
- 'next_rising_float'
- 'available_sources'
- 'next_setting_float'
- 'supported_features'
- 'media_artist_float'
- 'last_triggered_str'
- 'media_channel_float'
- 'media_playlist_float'
- 'available_important'
- 'entity_picture_local'
- 'frontend_stream_type'
- 'last_triggered_float'
- 'postal_code_timestamp'
- 'supported_color_modes'
- 'media_album_name_float'
- 'available_opportunistic'
- 'media_series_title_float'
- 'media_position_updated_at'
