x-common: &common
  image: mlserver:${SERVICE_VERSION_ABSOLUTE}
  init: true
  environment:
    - TZ=Australia/Perth
    - MLSERVER_SERVICE
    - MLSERVER_HTTP_PORT
    - MLFLOW_BACKEND_STORE_URI
    - MLFLOW_DEFAULT_ARTIFACT_ROOT
    - MLFLOW_TRACKING_URI
    - MLFLOW_REPOSITORY_URI
  volumes:
    - ${MLFLOW_DEFAULT_ARTIFACT_ROOT_SERVER}:${MLFLOW_DEFAULT_ARTIFACT_ROOT}
  logging:
    driver: "json-file"
    options:
      max-file: "5"
      max-size: "100m"
services:
  mlserver:
    container_name: mlserver
    <<: *common
    restart: ${SERVICE_RESTART}
    ports:
      - ${MLSERVER_HTTP_PORT}:8080
      - ${MLSERVER_GRPC_PORT}:8081
    healthcheck:
      test: /asystem/etc/checkready.sh
      interval: 2m
      timeout: 30s
      retries: 3
      start_period: 1m
      start_interval: 10s
    deploy:
      resources:
        limits:
          memory: 2G
  mlserver_bootstrap:
    container_name: mlserver_bootstrap
    <<: *common
    restart: 'no'
    entrypoint: bash
    command: /asystem/etc/bootstrap.sh
    depends_on:
      - mlserver