#######################################################################################
compensation:
  #######################################################################################
  compensation_sensor_netatmo_parents_co2:
    unique_id: compensation_sensor_netatmo_parents_co2
    source: sensor.netatmo_parents_co2
    precision: 0
    data_points:
      - [ 999, 566 ]
      - [ 1407, 711 ]
  #######################################################################################
