#######################################################################################
# WARNING: This file is written to by the build process, any manual edits will be lost!
#######################################################################################
adaptive_lighting:
  ####################################################################################
  - name: night_light
    interval: 30
    min_brightness: 1
    max_brightness: 100
    min_color_temp: 2500
    max_color_temp: 5500
    only_once: false
    take_over_control: true
    detect_non_ha_changes: true
    lights:
      - light.ada_lamp
      - light.edwin_night_light
  ####################################################################################
  - name: default
    interval: 30
    min_brightness: 100
    max_brightness: 100
    min_color_temp: 2500
    max_color_temp: 5500
    only_once: false
    take_over_control: true
    detect_non_ha_changes: true
    lights:
      - light.edwin_lamp
      - light.dining_main
      - light.kitchen_main
      - light.laundry_main
      - light.pantry_main
  ####################################################################################
  - name: bedroom
    interval: 30
    min_brightness: 1
    max_brightness: 100
    min_color_temp: 2500
    max_color_temp: 5500
    only_once: false
    take_over_control: true
    detect_non_ha_changes: true
    lights:
      - light.hallway_main
      - light.parents_main
      - light.bathroom_main
      - light.ensuite_main
      - light.wardrobe_main
  ####################################################################################
  - name: lounge
    interval: 30
    min_brightness: 1
    max_brightness: 100
    min_color_temp: 2500
    max_color_temp: 5500
    only_once: false
    take_over_control: true
    detect_non_ha_changes: true
    lights:
      - light.lounge_main
  ####################################################################################
input_boolean:
  ####################################################################################
  lighting_reset_adaptive_lighting_ada_lamp:
    name: Ada Lamp
    initial: off
  ####################################################################################
  lighting_reset_adaptive_lighting_edwin_lamp:
    name: Edwin Lamp
    initial: off
  ####################################################################################
  lighting_reset_adaptive_lighting_edwin_night_light:
    name: Edwin Night Light
    initial: off
  ####################################################################################
  lighting_reset_adaptive_lighting_hallway_main:
    name: Hallway Main
    initial: off
  ####################################################################################
  lighting_reset_adaptive_lighting_dining_main:
    name: Dining Main
    initial: off
  ####################################################################################
  lighting_reset_adaptive_lighting_lounge_main:
    name: Lounge Main
    initial: off
  ####################################################################################
  lighting_reset_adaptive_lighting_parents_main:
    name: Parents Main
    initial: off
  ####################################################################################
  lighting_reset_adaptive_lighting_kitchen_main:
    name: Kitchen Main
    initial: off
  ####################################################################################
  lighting_reset_adaptive_lighting_laundry_main:
    name: Laundry Main
    initial: off
  ####################################################################################
  lighting_reset_adaptive_lighting_pantry_main:
    name: Pantry Main
    initial: off
  ####################################################################################
  lighting_reset_adaptive_lighting_bathroom_main:
    name: Bathroom Main
    initial: off
  ####################################################################################
  lighting_reset_adaptive_lighting_ensuite_main:
    name: Ensuite Main
    initial: off
  ####################################################################################
  lighting_reset_adaptive_lighting_wardrobe_main:
    name: Wardrobe Main
    initial: off
  ####################################################################################
automation:
  ####################################################################################
  - id: lighting_sleep_adaptive_lighting
    alias: "Lighting: Sleep Adaptive Lighting"
    mode: single
    trigger:
      - platform: time
        at: "01:00:00"
    condition: [ ]
    action:
      ################################################################################
      - service: switch.turn_on
        target:
          entity_id: switch.adaptive_lighting_default
      - service: switch.turn_on
        target:
          entity_id: switch.adaptive_lighting_sleep_mode_default
      - service: switch.turn_on
        target:
          entity_id: switch.adaptive_lighting_adapt_color_default
      - service: switch.turn_on
        target:
          entity_id: switch.adaptive_lighting_adapt_brightness_default
      - service: adaptive_lighting.set_manual_control
        data:
          entity_id: switch.adaptive_lighting_default
          manual_control: false
      ################################################################################
      - service: switch.turn_on
        target:
          entity_id: switch.adaptive_lighting_bedroom
      - service: switch.turn_on
        target:
          entity_id: switch.adaptive_lighting_sleep_mode_bedroom
      - service: switch.turn_on
        target:
          entity_id: switch.adaptive_lighting_adapt_color_bedroom
      - service: switch.turn_on
        target:
          entity_id: switch.adaptive_lighting_adapt_brightness_bedroom
      - service: adaptive_lighting.set_manual_control
        data:
          entity_id: switch.adaptive_lighting_bedroom
          manual_control: false
      ################################################################################
      - service: switch.turn_on
        target:
          entity_id: switch.adaptive_lighting_night_light
      - service: switch.turn_on
        target:
          entity_id: switch.adaptive_lighting_sleep_mode_night_light
      - service: switch.turn_on
        target:
          entity_id: switch.adaptive_lighting_adapt_color_night_light
      - service: switch.turn_on
        target:
          entity_id: switch.adaptive_lighting_adapt_brightness_night_light
      - service: adaptive_lighting.set_manual_control
        data:
          entity_id: switch.adaptive_lighting_night_light
          manual_control: false
      ################################################################################
  - id: lighting_reset_adaptive_lighting
    alias: "Lighting: Reset Adaptive Lighting"
    mode: single
    trigger:
      - platform: time
        at: "05:00:00"
    condition: [ ]
    action:
      ################################################################################
      - service: switch.turn_on
        target:
          entity_id: switch.adaptive_lighting_default
      - service: switch.turn_off
        target:
          entity_id: switch.adaptive_lighting_sleep_mode_default
      - service: switch.turn_on
        target:
          entity_id: switch.adaptive_lighting_adapt_color_default
      - service: switch.turn_on
        target:
          entity_id: switch.adaptive_lighting_adapt_brightness_default
      - service: adaptive_lighting.set_manual_control
        data:
          entity_id: switch.adaptive_lighting_default
          manual_control: false
      ################################################################################
      - service: switch.turn_on
        target:
          entity_id: switch.adaptive_lighting_bedroom
      - service: switch.turn_off
        target:
          entity_id: switch.adaptive_lighting_sleep_mode_bedroom
      - service: switch.turn_on
        target:
          entity_id: switch.adaptive_lighting_adapt_color_bedroom
      - service: switch.turn_on
        target:
          entity_id: switch.adaptive_lighting_adapt_brightness_bedroom
      - service: adaptive_lighting.set_manual_control
        data:
          entity_id: switch.adaptive_lighting_bedroom
          manual_control: false
      ################################################################################
      - service: switch.turn_on
        target:
          entity_id: switch.adaptive_lighting_night_light
      - service: switch.turn_on
        target:
          entity_id: switch.adaptive_lighting_sleep_mode_night_light
      - service: switch.turn_on
        target:
          entity_id: switch.adaptive_lighting_adapt_color_night_light
      - service: switch.turn_on
        target:
          entity_id: switch.adaptive_lighting_adapt_brightness_night_light
      - service: adaptive_lighting.set_manual_control
        data:
          entity_id: switch.adaptive_lighting_night_light
          manual_control: false
      ################################################################################
  - id: lighting_reset_adaptive_lighting_announce
    alias: 'Lighting: Reset Adaptive Lighting on bulb announce'
    mode: single
    trigger:
      - platform: mqtt
        topic: zigbee/bridge/event
    condition:
      - condition: template
        value_template: '{{ trigger.payload_json.data.friendly_name | regex_search(" Bulb 1$") }}'
    action:
      ################################################################################
      - variables:
          light: '{{ "light." + (trigger.payload_json.data.friendly_name | regex_replace(" Bulb 1$") | replace(" ", "_") | lower) }}'
          light_reset: '{{ "input_boolean.lighting_reset_adaptive_lighting_" + (light | replace("light.", "")) }}'
      ################################################################################
      - if:
          - condition: template
            value_template: '{{ is_state(light_reset, "off") }}'
        then:
          - service: input_boolean.turn_on
            data_template:
              entity_id: '{{ light_reset }}'
        else:
          - service: light.turn_on
            data_template:
              brightness_pct: 100
              entity_id: '{{ light }}'
  ####################################################################################
  - id: lighting_reset_adaptive_lighting_ada_lamp
    alias: "Lighting: Reset Adaptive Lighting on request of Ada Lamp"
    trigger:
      - platform: state
        entity_id: input_boolean.lighting_reset_adaptive_lighting_ada_lamp
        from: 'off'
        to: 'on'
    action:
      - service: adaptive_lighting.set_manual_control
        data:
          entity_id: switch.adaptive_lighting_night_light
          lights: light.ada_lamp
          manual_control: false
      - delay: '00:00:10'
      - service: input_boolean.turn_off
        entity_id: input_boolean.lighting_reset_adaptive_lighting_ada_lamp
  ####################################################################################
  - id: lighting_reset_adaptive_lighting_edwin_lamp
    alias: "Lighting: Reset Adaptive Lighting on request of Edwin Lamp"
    trigger:
      - platform: state
        entity_id: input_boolean.lighting_reset_adaptive_lighting_edwin_lamp
        from: 'off'
        to: 'on'
    action:
      - service: adaptive_lighting.set_manual_control
        data:
          entity_id: switch.adaptive_lighting_default
          lights: light.edwin_lamp
          manual_control: false
      - delay: '00:00:10'
      - service: input_boolean.turn_off
        entity_id: input_boolean.lighting_reset_adaptive_lighting_edwin_lamp
  ####################################################################################
  - id: lighting_reset_adaptive_lighting_edwin_night_light
    alias: "Lighting: Reset Adaptive Lighting on request of Edwin Night Light"
    trigger:
      - platform: state
        entity_id: input_boolean.lighting_reset_adaptive_lighting_edwin_night_light
        from: 'off'
        to: 'on'
    action:
      - service: adaptive_lighting.set_manual_control
        data:
          entity_id: switch.adaptive_lighting_night_light
          lights: light.edwin_night_light
          manual_control: false
      - delay: '00:00:10'
      - service: input_boolean.turn_off
        entity_id: input_boolean.lighting_reset_adaptive_lighting_edwin_night_light
  ####################################################################################
  - id: lighting_reset_adaptive_lighting_hallway_main
    alias: "Lighting: Reset Adaptive Lighting on request of Hallway Main"
    trigger:
      - platform: state
        entity_id: input_boolean.lighting_reset_adaptive_lighting_hallway_main
        from: 'off'
        to: 'on'
    action:
      - service: adaptive_lighting.set_manual_control
        data:
          entity_id: switch.adaptive_lighting_bedroom
          lights: light.hallway_main
          manual_control: false
      - delay: '00:00:10'
      - service: input_boolean.turn_off
        entity_id: input_boolean.lighting_reset_adaptive_lighting_hallway_main
  ####################################################################################
  - id: lighting_reset_adaptive_lighting_dining_main
    alias: "Lighting: Reset Adaptive Lighting on request of Dining Main"
    trigger:
      - platform: state
        entity_id: input_boolean.lighting_reset_adaptive_lighting_dining_main
        from: 'off'
        to: 'on'
    action:
      - service: adaptive_lighting.set_manual_control
        data:
          entity_id: switch.adaptive_lighting_default
          lights: light.dining_main
          manual_control: false
      - delay: '00:00:10'
      - service: input_boolean.turn_off
        entity_id: input_boolean.lighting_reset_adaptive_lighting_dining_main
  ####################################################################################
  - id: lighting_reset_adaptive_lighting_lounge_main
    alias: "Lighting: Reset Adaptive Lighting on request of Lounge Main"
    trigger:
      - platform: state
        entity_id: input_boolean.lighting_reset_adaptive_lighting_lounge_main
        from: 'off'
        to: 'on'
    action:
      - service: adaptive_lighting.set_manual_control
        data:
          entity_id: switch.adaptive_lighting_lounge
          lights: light.lounge_main
          manual_control: false
      - delay: '00:00:10'
      - service: input_boolean.turn_off
        entity_id: input_boolean.lighting_reset_adaptive_lighting_lounge_main
  ####################################################################################
  - id: lighting_reset_adaptive_lighting_parents_main
    alias: "Lighting: Reset Adaptive Lighting on request of Parents Main"
    trigger:
      - platform: state
        entity_id: input_boolean.lighting_reset_adaptive_lighting_parents_main
        from: 'off'
        to: 'on'
    action:
      - service: adaptive_lighting.set_manual_control
        data:
          entity_id: switch.adaptive_lighting_bedroom
          lights: light.parents_main
          manual_control: false
      - delay: '00:00:10'
      - service: input_boolean.turn_off
        entity_id: input_boolean.lighting_reset_adaptive_lighting_parents_main
  ####################################################################################
  - id: lighting_reset_adaptive_lighting_kitchen_main
    alias: "Lighting: Reset Adaptive Lighting on request of Kitchen Main"
    trigger:
      - platform: state
        entity_id: input_boolean.lighting_reset_adaptive_lighting_kitchen_main
        from: 'off'
        to: 'on'
    action:
      - service: adaptive_lighting.set_manual_control
        data:
          entity_id: switch.adaptive_lighting_default
          lights: light.kitchen_main
          manual_control: false
      - delay: '00:00:10'
      - service: input_boolean.turn_off
        entity_id: input_boolean.lighting_reset_adaptive_lighting_kitchen_main
  ####################################################################################
  - id: lighting_reset_adaptive_lighting_laundry_main
    alias: "Lighting: Reset Adaptive Lighting on request of Laundry Main"
    trigger:
      - platform: state
        entity_id: input_boolean.lighting_reset_adaptive_lighting_laundry_main
        from: 'off'
        to: 'on'
    action:
      - service: adaptive_lighting.set_manual_control
        data:
          entity_id: switch.adaptive_lighting_default
          lights: light.laundry_main
          manual_control: false
      - delay: '00:00:10'
      - service: input_boolean.turn_off
        entity_id: input_boolean.lighting_reset_adaptive_lighting_laundry_main
  ####################################################################################
  - id: lighting_reset_adaptive_lighting_pantry_main
    alias: "Lighting: Reset Adaptive Lighting on request of Pantry Main"
    trigger:
      - platform: state
        entity_id: input_boolean.lighting_reset_adaptive_lighting_pantry_main
        from: 'off'
        to: 'on'
    action:
      - service: adaptive_lighting.set_manual_control
        data:
          entity_id: switch.adaptive_lighting_default
          lights: light.pantry_main
          manual_control: false
      - delay: '00:00:10'
      - service: input_boolean.turn_off
        entity_id: input_boolean.lighting_reset_adaptive_lighting_pantry_main
  ####################################################################################
  - id: lighting_reset_adaptive_lighting_bathroom_main
    alias: "Lighting: Reset Adaptive Lighting on request of Bathroom Main"
    trigger:
      - platform: state
        entity_id: input_boolean.lighting_reset_adaptive_lighting_bathroom_main
        from: 'off'
        to: 'on'
    action:
      - service: adaptive_lighting.set_manual_control
        data:
          entity_id: switch.adaptive_lighting_bedroom
          lights: light.bathroom_main
          manual_control: false
      - delay: '00:00:10'
      - service: input_boolean.turn_off
        entity_id: input_boolean.lighting_reset_adaptive_lighting_bathroom_main
  ####################################################################################
  - id: lighting_reset_adaptive_lighting_ensuite_main
    alias: "Lighting: Reset Adaptive Lighting on request of Ensuite Main"
    trigger:
      - platform: state
        entity_id: input_boolean.lighting_reset_adaptive_lighting_ensuite_main
        from: 'off'
        to: 'on'
    action:
      - service: adaptive_lighting.set_manual_control
        data:
          entity_id: switch.adaptive_lighting_bedroom
          lights: light.ensuite_main
          manual_control: false
      - delay: '00:00:10'
      - service: input_boolean.turn_off
        entity_id: input_boolean.lighting_reset_adaptive_lighting_ensuite_main
  ####################################################################################
  - id: lighting_reset_adaptive_lighting_wardrobe_main
    alias: "Lighting: Reset Adaptive Lighting on request of Wardrobe Main"
    trigger:
      - platform: state
        entity_id: input_boolean.lighting_reset_adaptive_lighting_wardrobe_main
        from: 'off'
        to: 'on'
    action:
      - service: adaptive_lighting.set_manual_control
        data:
          entity_id: switch.adaptive_lighting_bedroom
          lights: light.wardrobe_main
          manual_control: false
      - delay: '00:00:10'
      - service: input_boolean.turn_off
        entity_id: input_boolean.lighting_reset_adaptive_lighting_wardrobe_main
  ####################################################################################
