adaptive_lighting:
  interval: 90
  only_once: false
  take_over_control: true
  detect_non_ha_changes: true
  lights:
    - light.dining
    - light.hallway
    - light.dining
    - light.lounge
    - light.parents
    - light.kitchen
    - light.laundry
    - light.pantry
    - light.bathroom
    - light.ensuite
    - light.wardrobe
    - light.ada
    - light.lamp

automation:
  - alias: "Lighting: Reset Adaptive lighting"
    mode: single
    trigger:
      - platform: time
        at: "04:00:00"
    condition: [ ]
    action:
      - service: switch.turn_off
        target:
          entity_id: switch.adaptive_lighting_default
      - service: switch.turn_on
        target:
          entity_id: switch.adaptive_lighting_default
