adaptive_lighting:
  interval: 5
  take_over_control: true
  detect_non_ha_changes: true
  lights:
    - light.dining
    - light.hallway
    - light.dining
    - light.lounge
    - light.parents
    - light.kitchen
    - light.laundry
    - light.pantry
    - light.bathroom
    - light.ensuite
    - light.wardrobe
    - light.edwin
    - light.ada
    - light.lamp
