#######################################################################################
# WARNING: This file is written to by the build process, any manual edits will be lost!
#######################################################################################
# TODO: Currently not being picked up, could not be wired in config_flow or using wrong keys, think the former
#sonos:
#  media_player:
#    hosts:
#      - X
#######################################################################################
# TODO: Currently not being picked up, could not be wired in config_flow or using wrong keys, think the former
#google:
#  media_player:
#    hosts: 10.0.4.50,10.0.4.51,10.0.4.52,10.0.4.53,10.0.4.54
#######################################################################################
