#######################################################################################
# WARNING: This file is written to by the build process, any manual edits will be lost!
#######################################################################################
cast:
 known_hosts: 10.0.4.50,10.0.4.51,10.0.4.52,10.0.4.53,10.0.4.54
#######################################################################################
sonos:
  media_player:
    hosts:
      - 10.0.4.40
      - 10.0.4.41
      - 10.0.4.42
#######################################################################################
