################################################################################
input_boolean:
  ################################################################################
  home_movie:
    name: Movie
    initial: off
  ################################################################################
  home_sleep:
    name: Sleep
    initial: off
  ################################################################################
  home_reset:
    name: Reset
    initial: off
  ################################################################################
automation:
  ################################################################################
  - id: routine_home_movie_on
    alias: "Routine: Put home into Movie mode"
    mode: single
    trigger:
      - platform: state
        entity_id: input_boolean.home_movie
        from: 'off'
        to: 'on'
    condition: [ ]
    action:
      - service: switch.turn_off
        target:
          entity_id: switch.adaptive_lighting_lounge
      - service: light.turn_on
        target:
          entity_id: light.lounge_main
        data:
          brightness: 125
          color_temp: 500
      - service: switch.turn_on
        target:
          entity_id: switch.lounge_tv
  ################################################################################
  - id: routine_home_movie_off
    alias: "Routine: Put home out of Movie mode"
    mode: single
    trigger:
      - platform: state
        entity_id: input_boolean.home_movie
        from: 'on'
        to: 'off'
    condition: [ ]
    action:
      - service: switch.turn_on
        target:
          entity_id: switch.adaptive_lighting_lounge
      - service: switch.turn_off
        target:
          entity_id: switch.lounge_tv
      - delay: '00:00:30'
      - service: light.turn_off
        target:
          entity_id: light.lounge_main
  ################################################################################
  - id: routine_home_sleep
    alias: "Routine: Put home to sleep"
    mode: single
    trigger:
      - platform: state
        entity_id: input_boolean.home_sleep
        from: 'off'
        to: 'on'
    condition: [ ]
    action:
      - service: automation.trigger
        data:
          entity_id: automation.lighting_sleep_adaptive_lighting
      - delay: '00:00:01'
      - service: input_boolean.turn_off
        entity_id: input_boolean.home_sleep
  ################################################################################
  - id: routine_home_reset
    alias: "Routine: Reset home to defaults"
    mode: single
    trigger:
      - platform: state
        entity_id: input_boolean.home_reset
        from: 'off'
        to: 'on'
    condition: [ ]
    action:
      - service: automation.trigger
        data:
          entity_id: automation.lighting_reset_adaptive_lighting
      - service: input_boolean.turn_off
        entity_id: input_boolean.home_movie
      - delay: '00:00:01'
      - service: input_boolean.turn_off
        entity_id: input_boolean.home_reset
  ################################################################################
  - id: routine_home_lights_off
    alias: "Routine: Turn night lights off"
    mode: single
    trigger:
      - platform: time
        at: "08:00:00"
    condition: [ ]
    action:
      - service: light.turn_off
        target:
          entity_id:
            - light.ada_lamp
            - light.edwin_lamp
            - light.edwin_night_light
      - service: switch.turn_on
        target:
          entity_id:
            - switch.ada_fan_light_motion
            - switch.edwin_fan_light_motion
      - service: light.turn_on
        target:
          entity_id:
            - light.ada_fan
            - light.edwin_fan
      - service: fan.turn_off
        target:
          entity_id:
            - fan.ada_fan
            - fan.edwin_fan
            - fan.parents_fan
            - fan.lounge_fan
            - fan.deck_fan
      - service: media_player.turn_off
        target:
          entity_id:
            - media_player.ada_home
            - media_player.edwin_home
            - media_player.parents_home
            - media_player.parents_tv
            - media_player.lounge_home
  ################################################################################
  - id: routine_home_lights_on
    alias: "Routine: Turn night lights on"
    mode: single
    trigger:
      - platform: time
        at: "17:45:00"
    condition: [ ]
    action:
      - service: light.turn_on
        target:
          entity_id:
            - light.edwin_night_light
      - service: switch.turn_off
        target:
          entity_id:
            - switch.ada_fan_light_motion
            - switch.edwin_fan_light_motion
      - service: light.turn_off
        target:
          entity_id:
            - light.ada_fan
            - light.ada_lamp
            - light.edwin_lamp
            - light.edwin_fan
  ################################################################################
  - id: routine_home_fans_off
    alias: "Routine: Turn fans off"
    mode: single
    trigger:
      - platform: time
        at: "03:00:00"
    condition: [ ]
    action:
      - service: fan.turn_off
        target:
          entity_id:
            - fan.ada_fan
            - fan.edwin_fan
            - fan.parents_fan
            - fan.lounge_fan
            - fan.deck_fan
  ################################################################################
