default_config:

http:
  ssl_certificate: /config/certificate.pem
  ssl_key: /config/privkey.pem

homeassistant:
  customize: !include customize.yaml
  customize_glob: !include customize_glob.yaml

tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
