default_config:

http:
  ssl_key: /config/.pem
  ssl_certificate: /config/certificate.pem
  cors_allowed_origins:
    - https://google.com
    - https://www.home-assistant.io
    - https://janeandgraham.com
    - https://home.janeandgraham.com

tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

homeassistant:
  customize: !include customize.yaml
  customize_glob: !include customize_glob.yaml

mqtt:
  broker: 192.168.1.10
  port: 1883
  client_id: 'hass'
  discovery: true
  discovery_prefix: 'haas/sensor/config'
  birth_message:
    topic: 'hass/status'
    payload: 'online'
  will_message:
    topic: 'hass/status'
    payload: 'offline'

lovelace:
  mode: yaml
  # Include external resources only add when mode is yaml, otherwise manage in the resources in the lovelace configuration panel.
  #  resources:
  #    - url: /local/my-custom-card.js
  #      type: module
  #    - url: /local/my-webfont.css
  #      type: css
  dashboards:
    lovelace-generated:
      mode: yaml
      filename: notexist.yaml
      title: Generated
      icon: mdi:tools
      show_in_sidebar: true
      require_admin: true
#    lovelace-hidden:
#      mode: yaml
#      title: hidden
#      show_in_sidebar: false
#      filename: hidden.yaml
