#TODO: Look at examples to structure, such as https://www.awesome-ha.com and https://isabellaalstrom.github.io

default_config:

homeassistant:
  customize: !include customize.yaml


http:
  ssl_key: /config/.pem
  ssl_certificate: /config/certificate.pem
  cors_allowed_origins:
    - https://google.com
    - https://www.home-assistant.io
    - https://janeandgraham.com
    - https://home.janeandgraham.com

tts:
  - platform: google_translate

recorder:
  db_url: !env_var DB_URL
  purge_keep_days: 3


influxdb:
  api_version: 2
  ssl: false
  host: macmini-liz
  port: 9999
  token: EDwkKCzUe5EFFgAhk7gMiDJ0vVLu_7gFzwMx3ysGiAKYfWaWhaUnljQoldNkAQWX--NtRTj3aXjhQoTlSvQ1Vg==

  # TODO: Update to 'Home' once InfluxDB-2-Beta-17 comes out and database format reverts to 1.8 format
  organization: asystem

  bucket: haas
  tags:
    instance: production
    source: home_assistant
  tags_attributes:
    - friendly_name
  default_measurement: units

mqtt:
  broker: !env_var MQTT_HOST
  port: !env_var MQTT_PORT
  client_id: 'hass'
  discovery: true
  discovery_prefix: 'haas/sensor/config'
  birth_message:
    topic: 'hass/status'
    payload: 'online'
  will_message:
    topic: 'hass/status'
    payload: 'offline'

sensor:
  !include_dir_merge_list config_sensors

weather:
  - platform: bom
    name: Perth Airport
    station: IDW60901.94610

camera:
  - platform: bom
    location: Perth

tplink:
  discovery: false
  switch:
    - host: 192.168.1.22
    - host: 192.168.1.25

automation:
  !include_dir_merge_list config_automations

lovelace:
  mode: yaml
  resources:
    - url: /local/custom_ui/mini-graph-card-bundle.js?v=0.9.4
      type: module
    - url: /local/custom_ui/bom-weather-card.js?v=0.78_HACKED_BY_ME
      type: module
  dashboards:
    lovelace-generated:
      mode: yaml
      filename: notexist.yaml
      title: Generated
      icon: mdi:tools
      show_in_sidebar: true
      require_admin: true

logger:
  default: warning
  logs:
    hacs: warning
    custom_components.hacs: warning
    custom_components.bom_forecast: warning
    homeassistant.components.bom: warning
    homeassistant.components.mqtt: warning
