default_config:

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

homeassistant:
  customize: !include customize.yaml
  customize_glob: !include customize_glob.yaml

http:
  ssl_key: /config/.pem
  ssl_certificate: /config/certificate.pem
  cors_allowed_origins:
    - https://google.com
    - https://www.home-assistant.io
    - https://janeandgraham.com
    - https://home.janeandgraham.com

tts:
  - platform: google_translate

recorder:
  db_url: !env_var DB_URL
  purge_keep_days: 1
#  exclude:
#    domains:
#      - sensor

mqtt:
  broker: !env_var MQTT_HOST
  port: !env_var MQTT_PORT
  client_id: 'hass'
  discovery: true
  discovery_prefix: 'haas/sensor/config'
  birth_message:
    topic: 'hass/status'
    payload: 'online'
  will_message:
    topic: 'hass/status'
    payload: 'offline'

#hacs:
#  token: 3f8f8d1288256d31683a7efaa9e533ea86e60b3d

#sensor:
#  - platform: bom_forecast
#    product_id: IDW12300
#    name: Perth
#    forecast_days: 6
#    rest_of_today: true
#    friendly: false
#    friendly_state_format: '{max}, {summary}'
#    monitored_conditions:
#      - 'max'
#      - 'min'
#      - 'chance_of_rain'
#      - 'possible_rainfall'
#      - 'summary'
#      - 'detailed_summary'
#      - 'icon'
#      - 'uv_alert'
#      - 'fire_danger'

lovelace:
  mode: yaml
#  resources:
#    - url: /local/custom_ui/bom-weather-card.js?v=0.1
#      type: module
  dashboards:
    lovelace-generated:
      mode: yaml
      filename: notexist.yaml
      title: Generated
      icon: mdi:tools
      show_in_sidebar: true
      require_admin: true
  #    lovelace-hidden:
  #      mode: yaml
  #      title: hidden
  #      show_in_sidebar: false
  #      filename: hidden.yaml

logger:
  default: warning
  logs:
    homeassistant.components.mqtt: warning
