sensor.roof_temperature:
  friendly_name: Roof
sensor.ada_temperature:
  friendly_name: Ada
sensor.basement_temperature:
  friendly_name: Basement
sensor.deck_temperature:
  friendly_name: Deck
sensor.dining_temperature:
  friendly_name: Dining
sensor.edwin_temperature:
  friendly_name: Edwin
sensor.kitchen_temperature:
  friendly_name: Kitchen
sensor.laundry_temperature:
  friendly_name: Laundry
sensor.lounge_temperature:
  friendly_name: Lounge
sensor.office_temperature:
  friendly_name: Office
sensor.pantry_temperature:
  friendly_name: Pantry
sensor.parents_temperature:
  friendly_name: Parents
sensor.utility_temperature:
  friendly_name: Utility
sensor.ada_carbon_dioxide:
  friendly_name: Ada
sensor.dining_carbon_dioxide:
  friendly_name: Dining
sensor.edwin_carbon_dioxide:
  friendly_name: Edwin
sensor.kitchen_carbon_dioxide:
  friendly_name: Kitchen
sensor.laundry_carbon_dioxide:
  friendly_name: Laundry
sensor.lounge_carbon_dioxide:
  friendly_name: Lounge
sensor.office_carbon_dioxide:
  friendly_name: Office
sensor.pantry_carbon_dioxide:
  friendly_name: Pantry
sensor.parents_carbon_dioxide:
  friendly_name: Parents
sensor.ada_noise:
  friendly_name: Ada
sensor.edwin_noise:
  friendly_name: Edwin
sensor.kitchen_noise:
  friendly_name: Kitchen
sensor.laundry_noise:
  friendly_name: Laundry
sensor.office_noise:
  friendly_name: Office
sensor.parents_noise:
  friendly_name: Parents
sensor.roof_pressure:
  friendly_name: Roof
sensor.ada_pressure:
  friendly_name: Ada
sensor.edwin_pressure:
  friendly_name: Edwin
sensor.kitchen_pressure:
  friendly_name: Kitchen
sensor.laundry_pressure:
  friendly_name: Laundry
sensor.office_pressure:
  friendly_name: Office
sensor.parents_pressure:
  friendly_name: Parents
sensor.roof_humidity:
  friendly_name: Roof
sensor.ada_humidity:
  friendly_name: Ada
sensor.basement_humidity:
  friendly_name: Basement
sensor.deck_humidity:
  friendly_name: Deck
sensor.dining_humidity:
  friendly_name: Dining
sensor.edwin_humidity:
  friendly_name: Edwin
sensor.kitchen_humidity:
  friendly_name: Kitchen
sensor.laundry_humidity:
  friendly_name: Laundry
sensor.lounge_humidity:
  friendly_name: Lounge
sensor.office_humidity:
  friendly_name: Office
sensor.pantry_humidity:
  friendly_name: Pantry
sensor.parents_humidity:
  friendly_name: Parents
sensor.utility_humidity:
  friendly_name: Utility
sensor.utility_dew_point:
  friendly_name: Utility
sensor.roof_dew_point:
  friendly_name: Roof
sensor.last_30_min_rain:
  friendly_name: Last 30 Min
sensor.office_power_consumption:
  friendly_name: Office
sensor.servers_power_consumption:
  friendly_name: Servers
sensor.towelrails_power_consumption:
  friendly_name: Towelrails
