sensor.ada_carbon_dioxide:
  friendly_name: Ada
sensor.dining_carbon_dioxide:
  friendly_name: Dining
sensor.edwin_carbon_dioxide:
  friendly_name: Edwin
sensor.kitchen_carbon_dioxide:
  friendly_name: Kitchen
sensor.lounge_carbon_dioxide:
  friendly_name: Lounge
sensor.office_carbon_dioxide:
  friendly_name: Office
sensor.pantry_carbon_dioxide:
  friendly_name: Pantry
sensor.parents_carbon_dioxide:
  friendly_name: Parents
sensor.hallway_lights_energy_consumption:
  friendly_name: Hallway Lights
sensor.office_lights_energy_consumption:
  friendly_name: Office Lights
sensor.dining_lights_energy_consumption:
  friendly_name: Dining Lights
sensor.kitchen_lights_energy_consumption:
  friendly_name: Kitchen Lights
sensor.pantry_lights_energy_consumption:
  friendly_name: Pantry Lights
sensor.servers_energy_consumption:
  friendly_name: Servers
sensor.ada_lights_energy_consumption:
  friendly_name: Ada Lights
sensor.laundry_lights_energy_consumption:
  friendly_name: Laundry Lights
sensor.bathroom_lights_energy_consumption:
  friendly_name: Bathroom Lights
sensor.lounge_lights_energy_consumption:
  friendly_name: Lounge Lights
sensor.towelrails_energy_consumption:
  friendly_name: Towelrails
sensor.parents_lights_energy_consumption:
  friendly_name: Parents Lights
sensor.ensuite_lights_energy_consumption:
  friendly_name: Ensuite Lights
sensor.edwin_lights_energy_consumption:
  friendly_name: Edwin Lights
sensor.wardrobe_lights_energy_consumption:
  friendly_name: Wardrobe Lights
sensor.office_energy_consumption:
  friendly_name: Office
sensor.ada_health_index:
  friendly_name: Ada
sensor.edwin_health_index:
  friendly_name: Edwin
sensor.parents_health_index:
  friendly_name: Parents
sensor.ada_humidity:
  friendly_name: Ada
sensor.basement_humidity:
  friendly_name: Basement
sensor.deck_humidity:
  friendly_name: Deck
sensor.dining_humidity:
  friendly_name: Dining
sensor.edwin_humidity:
  friendly_name: Edwin
sensor.kitchen_humidity:
  friendly_name: Kitchen
sensor.lounge_humidity:
  friendly_name: Lounge
sensor.office_humidity:
  friendly_name: Office
sensor.pantry_humidity:
  friendly_name: Pantry
sensor.parents_humidity:
  friendly_name: Parents
sensor.ada_noise:
  friendly_name: Ada
sensor.edwin_noise:
  friendly_name: Edwin
sensor.kitchen_noise:
  friendly_name: Kitchen
sensor.office_noise:
  friendly_name: Office
sensor.parents_noise:
  friendly_name: Parents
sensor.bathroom_lights_power_consumption:
  friendly_name: Bathroom Lights
sensor.ada_lights_power_consumption:
  friendly_name: Ada Lights
sensor.ensuite_lights_power_consumption:
  friendly_name: Ensuite Lights
sensor.edwin_lights_power_consumption:
  friendly_name: Edwin Lights
sensor.office_lights_power_consumption:
  friendly_name: Office Lights
sensor.kitchen_lights_power_consumption:
  friendly_name: Kitchen Lights
sensor.dining_lights_power_consumption:
  friendly_name: Dining Lights
sensor.pantry_lights_power_consumption:
  friendly_name: Pantry Lights
sensor.wardrobe_lights_power_consumption:
  friendly_name: Wardrobe Lights
sensor.lounge_lights_power_consumption:
  friendly_name: Lounge Lights
sensor.parents_lights_power_consumption:
  friendly_name: Parents Lights
sensor.servers_power_consumption:
  friendly_name: Servers
sensor.laundry_lights_power_consumption:
  friendly_name: Laundry Lights
sensor.hallway_lights_power_consumption:
  friendly_name: Hallway Lights
sensor.towelrails_power_consumption:
  friendly_name: Towelrails
sensor.office_power_consumption:
  friendly_name: Office
sensor.ada_pressure_absolute:
  friendly_name: Ada
sensor.edwin_pressure_absolute:
  friendly_name: Edwin
sensor.kitchen_pressure_absolute:
  friendly_name: Kitchen
sensor.office_pressure_absolute:
  friendly_name: Office
sensor.parents_pressure_absolute:
  friendly_name: Parents
sensor.ada_pressure:
  friendly_name: Ada
sensor.edwin_pressure:
  friendly_name: Edwin
sensor.kitchen_pressure:
  friendly_name: Kitchen
sensor.office_pressure:
  friendly_name: Office
sensor.parents_pressure:
  friendly_name: Parents
sensor.ada_temperature:
  friendly_name: Ada
sensor.basement_temperature:
  friendly_name: Basement
sensor.deck_temperature:
  friendly_name: Deck
sensor.dining_temperature:
  friendly_name: Dining
sensor.edwin_temperature:
  friendly_name: Edwin
sensor.kitchen_temperature:
  friendly_name: Kitchen
sensor.lounge_temperature:
  friendly_name: Lounge
sensor.office_temperature:
  friendly_name: Office
sensor.pantry_temperature:
  friendly_name: Pantry
sensor.parents_temperature:
  friendly_name: Parents
sensor.laundry_carbon_dioxide:
  friendly_name: Laundry
sensor.laundry_health_index:
  friendly_name: Laundry
sensor.laundry_humidity:
  friendly_name: Laundry
sensor.laundry_noise:
  friendly_name: Laundry
sensor.laundry_pressure_absolute:
  friendly_name: Laundry
sensor.laundry_pressure:
  friendly_name: Laundry
sensor.laundry_temperature:
  friendly_name: Laundry
