title: Home
views:

  - path: default_view
    title: WEATHER
    cards: !include lovelace/weather.yaml

  - path: control
    title: Control
    cards: !include lovelace/control.yaml

  - path: media
    title: Media
    cards: !include lovelace/media.yaml

  - path: monitor
    title: Monitor
    cards: !include lovelace/monitor.yaml

