title: Home
views:
  - path: default_view
    title: Home
    badges: [ ]
    cards:
      - type: custom:bom-weather-card
        title: BOM Weather
        entity_current_conditions: sensor.bom_midland_icon_0
        entity_temperature: sensor.bom_midland_air_temp_c
        entity_forecast_high_temp_1: sensor.bom_midland_max_temp_c_1
        entity_forecast_high_temp_2: sensor.bom_midland_max_temp_c_2
        entity_forecast_high_temp_3: sensor.bom_midland_max_temp_c_3
        entity_forecast_high_temp_4: sensor.bom_midland_max_temp_c_4
        entity_forecast_high_temp_5: sensor.bom_midland_max_temp_c_5
        entity_forecast_icon_1: sensor.bom_midland_icon_1
        entity_forecast_icon_2: sensor.bom_midland_icon_2
        entity_forecast_icon_3: sensor.bom_midland_icon_3
        entity_forecast_icon_4: sensor.bom_midland_icon_4
        entity_forecast_icon_5: sensor.bom_midland_icon_5
        entity_forecast_low_temp_1: sensor.bom_midland_min_temp_c_1
        entity_forecast_low_temp_2: sensor.bom_midland_min_temp_c_2
        entity_forecast_low_temp_3: sensor.bom_midland_min_temp_c_3
        entity_forecast_low_temp_4: sensor.bom_midland_min_temp_c_4
        entity_forecast_low_temp_5: sensor.bom_midland_min_temp_c_5
        entity_summary_1: sensor.bom_midland_summary_1
        entity_summary_2: sensor.bom_midland_summary_2
        entity_summary_3: sensor.bom_midland_summary_3
        entity_summary_4: sensor.bom_midland_summary_4
        entity_summary_5: sensor.bom_midland_summary_5
  - path: lights
    title: Lights
    badges: [ ]
    cards:
      - type: entities
        entities:
          - light.ada
          - light.bathroom
          - light.dining
          - light.edwin
          - light.ensuite
          - light.hallway
          - light.kitchen
          - light.laundry
          - light.lounge
          - light.office
          - light.pantry
          - light.parents
          - light.wardrobe
        title: Light
  - path: media
    title: Media
    badges: [ ]
    cards:
      - type: media-control
        entity: media_player.ada_home
      - type: media-control
        entity: media_player.edwin_home
      - type: media-control
        entity: media_player.kitchen_home
      - type: media-control
        entity: media_player.kitchen_speaker
      - type: media-control
        entity: media_player.parents_home
      - type: media-control
        entity: media_player.parents_speaker
      - type: media-control
        entity: media_player.office_tv
      - type: media-control
        entity: media_player.office_speaker
      - type: media-control
        entity: media_player.lounge_home
