title: Home
views:
  - path: default_view
    title: Home
    badges: [ ]
    cards:
      - type: weather-forecast
        entity: weather.home
  - path: lights
    title: Lights
    badges: [ ]
    cards:
      - type: entities
        entities:
          - light.ada
          - light.bathroom
          - light.dining
          - light.edwin
          - light.ensuite
          - light.hallway
          - light.kitchen
          - light.laundry
          - light.lounge
          - light.office
          - light.pantry
          - light.parents
          - light.wardrobe
        title: Light
  - path: media
    title: Media
    badges: [ ]
    cards:
      - type: media-control
        entity: media_player.ada_home
      - type: media-control
        entity: media_player.edwin_home
      - type: media-control
        entity: media_player.kitchen_home
      - type: media-control
        entity: media_player.kitchen_speaker
      - type: media-control
        entity: media_player.parents_home
      - type: media-control
        entity: media_player.parents_speaker
      - type: media-control
        entity: media_player.office_tv
      - type: media-control
        entity: media_player.office_speaker
      - type: media-control
        entity: media_player.lounge_home
