version: '3.7'
services:
  internet:
    container_name: internet
    image: telegraf:1.16.0
    init: true
    restart: ${RESTART}
    environment:
      - TZ=Australia/Perth
      - HOST_IP
      - HOST_NAME
      - INFLUXDB_PORT
      - INFLUXDB_HOST
    volumes:
      - ${DATA_DIR}/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    deploy:
      resources:
        limits:
          memory: 4G