version: '3.7'
services:
  prometheus:
    container_name: prometheus
    image: prom/prometheus:v2.22.0
    init: true
    restart: ${SERVICE_RESTART}
    environment:
      - TZ=Australia/Perth
    volumes:
      - ${SERVICE_DATA_DIR}/data:/prometheus
    deploy:
      resources:
        limits:
          memory: 5G