services:
  letsencrypt:
    # https://github.com/adferrand/dnsrobocert/releases
    image: adferrand/dnsrobocert:3.25.0
    container_name: letsencrypt
    init: true
    environment:
      - TZ=Australia/Perth
      - CLOUDFLARE_TOKEN
      - LETSENCRYPT_STAGING
      - NGINX_SERVICE
      - UDMUTILITIES_SERVICE
    restart: ${SERVICE_RESTART}
    volumes:
      - ${SERVICE_DATA_DIR}/letsencrypt:/etc/letsencrypt
      - ${SERVICE_DATA_DIR}/dnsrobocert:/etc/dnsrobocert
    healthcheck:
      test: /asystem/etc/healthcheck.sh
      interval: 2m
      timeout: 10s
      retries: 3
      start_period: 1m
      start_interval: 10s
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "100m"
    deploy:
      resources:
        limits:
          memory: 256M
