# https://github.com/home-assistant/core/releases
version: '3.7'
x-common: &common
  image: homeassistant/home-assistant:2023.3.1
  user: root
  environment:
    - TZ=Australia/Perth
    - SERVICE_VERSION_COMPACT
    - HOMEASSISTANT_DB
    - HOMEASSISTANT_INTERNAL_URL
    - HOMEASSISTANT_EXTERNAL_URL
    - VERNEMQ_HOST
    - VERNEMQ_PORT
    - INFLUXDB_HOST
    - INFLUXDB_PORT
    - INFLUXDB_ORG
    - INFLUXDB_TOKEN
    - INFLUXDB_BUCKET_HOME_PRIVATE
    - WITHINGS_CLIENTID
    - WITHINGS_CONSUMERSECRET
  logging:
    driver: "json-file"
    options:
      max-file: "5"
      max-size: "100m"
services:
  homeassistant:
    container_name: homeassistant
    <<: *common
    restart: ${SERVICE_RESTART}
    volumes:
      - ${SERVICE_DATA_DIR}/bootstrap.sh:/bootstrap/bootstrap.sh
      - ${SERVICE_DATA_DIR}:/config

    # TODO: Cant deploy with network_mode host, need to think how to run locally
    #    ports:
    #      - ${HOMEASSISTANT_PORT}:${HOMEASSISTANT_PORT}

    network_mode: host
    deploy:
      resources:
        limits:
          memory: 5G
  homeassistant_bootstrap:
    container_name: homeassistant_bootstrap
    <<: *common
    restart: 'no'
    volumes:
      - ${SERVICE_DATA_DIR}/bootstrap.sh:/bootstrap/bootstrap.sh
      - ${SERVICE_DATA_DIR}:/config
    entrypoint: /bin/bash
    command:
      - /bootstrap/bootstrap.sh
    depends_on:
      - homeassistant
