version: '3.7'
services:
  letsencrypt:
    container_name: letsencrypt
    image: adferrand/dnsrobocert:3.4.0
    init: true

    # TODO: Update to cloudflare to avoid the whitelisting in namecheap?
    environment:
      - NAMECHEAP_TOKEN
      - NAMECHEAP_USER
      - NAMECHEAP_IP
    volumes:
      - ${DATA_DIR}/letsencrypt:/etc/letsencrypt
      - ${DATA_DIR}/dnsrobocert:/etc/dnsrobocert
