version: '3.7'
services:
  letsencrypt:
    container_name: letsencrypt
    image: adferrand/dnsrobocert:3.7.0
    init: true
    environment:
      - LETSENCRYPT_STAGING
      - CLOUDFLARE_TOKEN
    volumes:
      - ${DATA_DIR}/letsencrypt:/etc/letsencrypt
      - ${DATA_DIR}/dnsrobocert:/etc/dnsrobocert
    deploy:
      resources:
        limits:
          memory: 4G