# https://github.com/home-assistant/core/releases
x-common: &common
  image: homeassistant/home-assistant:2024.7.4
  user: root
  environment:
    - TZ=Australia/Perth
    - SERVICE_VERSION_COMPACT
    - HOMEASSISTANT_HTTP_PORT
    - HOMEASSISTANT_DB
    - HOMEASSISTANT_INTERNAL_URL
    - HOMEASSISTANT_EXTERNAL_URL
    - VERNEMQ_SERVICE
    - VERNEMQ_PORT
    - INFLUXDB_SERVICE
    - INFLUXDB_HTTP_PORT
    - INFLUXDB_ORG
    - INFLUXDB_TOKEN
    - INFLUXDB_BUCKET_HOME_PRIVATE
    - WITHINGS_CLIENTID
    - WITHINGS_CONSUMERSECRET
  logging:
    driver: "json-file"
    options:
      max-file: "5"
      max-size: "100m"
services:
  homeassistant:
    container_name: homeassistant
    <<: *common
    # noinspection ComposeUnknownValues
    restart: ${SERVICE_RESTART}
    volumes:
      - ${SERVICE_DATA_DIR}/bootstrap.sh:/bootstrap/bootstrap.sh
      - ${SERVICE_DATA_DIR}:/config

    # TODO: Cant deploy with network_mode host, need to think how to run locally
    #    ports:
    #      - ${HOMEASSISTANT_HTTP_PORT}:${HOMEASSISTANT_HTTP_PORT}

    network_mode: host
    deploy:
      resources:
        limits:
          memory: 2G
  homeassistant_bootstrap:
    container_name: homeassistant_bootstrap
    <<: *common
    restart: 'no'
    volumes:
      - ${SERVICE_DATA_DIR}/bootstrap.sh:/bootstrap/bootstrap.sh
      - ${SERVICE_DATA_DIR}:/config
    entrypoint: /bin/bash
    command:
      - /bootstrap/bootstrap.sh
    depends_on:
      - homeassistant
