services:
  weewx:
    container_name: weewx
    image: weewx:${SERVICE_VERSION_ABSOLUTE}
    init: true
    restart: ${SERVICE_RESTART}
    environment:
      - TZ=Australia/Perth
      - WEEWX_UID=weewx
      - WEEWX_GID=dialout
      - MARIADB_SERVICE
      - MARIADB_USER_WEEWX
      - MARIADB_DATABASE_WEEWX
      - VERNEMQ_SERVICE
      - VERNEMQ_PORT
    ports:
      - ${WEEWX_HTTP_PORT}:80
    volumes:
      - ${SERVICE_DATA_DIR}:/data
      - ${SERVICE_DATA_DIR}/skins:/home/weewx/skins
      - ${SERVICE_DATA_DIR}/weewx.conf:/etc/weewx/weewx.conf
    devices:
      - ${WEEWX_DEV}:/dev/ttyUSB0
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "100m"
    deploy:
      resources:
        limits:
          memory: 256M