services:
  plex:
    image: plex:${SERVICE_VERSION_ABSOLUTE}
    container_name: plex
    init: false
    restart: ${SERVICE_RESTART}
    environment:
      - TZ=Australia/Perth
      - PUID=0
      - PGID=0
      - VERSION=docker
      - PLEX_SERVICE
      - PLEX_HTTP_PORT
      - PLEX_CLAIM
      - PLEX_TOKEN
    volumes:
      - ${SERVICE_DATA_DIR}/config:/config
      - ${SERVICE_DATA_DIR}/transcode:/transcode
      - ${PLEX_SHARE_DIR}:/share
    ports:
      - ${PLEX_HTTP_PORT}:${PLEX_HTTP_PORT}
#      - 32469:32469
#      - 1900:1900
      - 5353:5353
#      - 32410-32414:32410-32414
    healthcheck:
      test: /asystem/etc/checkhealthy.sh
      interval: 2m
      timeout: 30s
      retries: 3
      start_period: 60s
      start_interval: 10s
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "100m"
    deploy:
      resources:
        limits:
          memory: 4G
