#######################################################################################
# WARNING: This file is written to by the build process, any manual edits will be lost!
#######################################################################################
- type: entities
  title: Battery Charge Remaining
  entities:
    - entity: sensor.netatmo_bertram_2_office_pantry_battery_percent
      name: Netatmo Pantry
      icon: mdi:battery-30
    - entity: sensor.netatmo_bertram_2_office_lounge_battery_percent
      name: Netatmo Lounge
      icon: mdi:battery-30
    - entity: sensor.netatmo_bertram_2_office_dining_battery_percent
      name: Netatmo Dining
      icon: mdi:battery-30
    - entity: sensor.netatmo_bertram_2_office_basement_battery_percent
      name: Netatmo Basement
      icon: mdi:battery-30
    - entity: sensor.parents_speaker_battery
      name: Sonos Parents
      icon: mdi:battery-30
    - entity: sensor.kitchen_home_battery
      name: Sonos Kitchen
      icon: mdi:battery-30
