- type: custom:mini-graph-card
  name: Temperature
  font_size_header: 19
  aggregate_func: max
  hours_to_show: 24
  points_per_hour: 6
  line_width: 2
  tap_action: none
  show_state: true
  show_indicator: true
  show:
    extrema: true
    fill: false
  entities:
    - sensor.roof_temperature
    - sensor.ada_temperature
    - sensor.edwin_temperature
    - sensor.parents_temperature
- type: entities
  show_header_toggle: false
  entities:
    - entity: sensor.roof_temperature
    - entity: sensor.ada_temperature
    - entity: sensor.basement_temperature
    - entity: sensor.dining_temperature
    - entity: sensor.edwin_temperature
    - entity: sensor.kitchen_temperature
    - entity: sensor.laundry_temperature
    - entity: sensor.lounge_temperature
    - entity: sensor.office_temperature
    - entity: sensor.pantry_temperature
    - entity: sensor.parents_temperature
    - entity: sensor.rack_temperature
- type: custom:mini-graph-card
  name: Carbon Dioxide
  font_size_header: 19
  aggregate_func: max
  hours_to_show: 24
  points_per_hour: 6
  line_width: 2
  tap_action: none
  show_state: true
  show_indicator: true
  show:
    extrema: true
    fill: false
  entities:
    - sensor.edwin_carbon_dioxide
    - sensor.kitchen_carbon_dioxide
    - sensor.lounge_carbon_dioxide
    - sensor.office_carbon_dioxide
- type: entities
  show_header_toggle: false
  entities:
    - entity: sensor.dining_carbon_dioxide
    - entity: sensor.edwin_carbon_dioxide
    - entity: sensor.kitchen_carbon_dioxide
    - entity: sensor.lounge_carbon_dioxide
    - entity: sensor.office_carbon_dioxide
    - entity: sensor.pantry_carbon_dioxide
    - entity: sensor.parents_carbon_dioxide
- type: custom:mini-graph-card
  name: Humidity
  font_size_header: 19
  aggregate_func: max
  hours_to_show: 24
  points_per_hour: 6
  line_width: 2
  tap_action: none
  show_state: true
  show_indicator: true
  show:
    extrema: true
    fill: false
  entities:
    - sensor.roof_humidity
    - sensor.ada_humidity
    - sensor.edwin_humidity
    - sensor.parents_humidity
- type: entities
  show_header_toggle: false
  entities:
    - entity: sensor.roof_humidity
    - entity: sensor.ada_humidity
    - entity: sensor.basement_humidity
    - entity: sensor.dining_humidity
    - entity: sensor.edwin_humidity
    - entity: sensor.kitchen_humidity
    - entity: sensor.laundry_humidity
    - entity: sensor.lounge_humidity
    - entity: sensor.office_humidity
    - entity: sensor.pantry_humidity
    - entity: sensor.parents_humidity
    - entity: sensor.rack_humidity
- type: custom:mini-graph-card
  name: Noise
  font_size_header: 19
  aggregate_func: max
  hours_to_show: 24
  points_per_hour: 6
  line_width: 2
  tap_action: none
  show_state: true
  show_indicator: true
  show:
    extrema: true
    fill: false
  entities:
    - sensor.ada_noise
    - sensor.edwin_noise
    - sensor.kitchen_noise
    - sensor.laundry_noise
    - sensor.office_noise
    - sensor.parents_noise
- type: entities
  show_header_toggle: false
  entities:
    - entity: sensor.ada_noise
    - entity: sensor.edwin_noise
    - entity: sensor.kitchen_noise
    - entity: sensor.laundry_noise
    - entity: sensor.office_noise
    - entity: sensor.parents_noise
