#######################################################################################
# WARNING: This file is written to by the build process, any manual edits will be lost!
################################################################################
- type: custom:mini-graph-card
  name: Temperature
  icon: mdi:thermometer
  font_size_header: 19
  aggregate_func: max
  hours_to_show: 24
  points_per_hour: 6
  line_width: 2
  tap_action: none
  show_state: true
  show_indicator: true
  show:
    extrema: true
    fill: false
  entities:
    - entity: sensor.compensation_sensor_roof_temperature
      name: Roof
    - entity: sensor.compensation_sensor_netatmo_ada_temperature
      name: Ada
    - entity: sensor.compensation_sensor_netatmo_edwin_temperature
      name: Edwin
    - entity: sensor.compensation_sensor_netatmo_parents_temperature
      name: Parents
################################################################################
- type: entities
  entities:
    - entity: sensor.compensation_sensor_roof_temperature
      name: Roof
      icon: mdi:thermometer
    - entity: sensor.compensation_sensor_netatmo_ada_temperature
      name: Ada
      icon: mdi:thermometer
    - entity: sensor.compensation_sensor_netatmo_edwin_temperature
      name: Edwin
      icon: mdi:thermometer
    - entity: sensor.compensation_sensor_netatmo_parents_temperature
      name: Parents
      icon: mdi:thermometer
    - entity: sensor.compensation_sensor_netatmo_bertram_2_office_temperature
      name: Office
      icon: mdi:thermometer
    - entity: sensor.compensation_sensor_netatmo_bertram_2_kitchen_temperature
      name: Kitchen
      icon: mdi:thermometer
    - entity: sensor.compensation_sensor_netatmo_bertram_2_office_pantry_temperature
      name: Pantry
      icon: mdi:thermometer
    - entity: sensor.compensation_sensor_netatmo_bertram_2_office_lounge_temperature
      name: Lounge
      icon: mdi:thermometer
    - entity: sensor.compensation_sensor_netatmo_bertram_2_office_dining_temperature
      name: Dining
      icon: mdi:thermometer
    - entity: sensor.compensation_sensor_netatmo_laundry_temperature
      name: Laundry
      icon: mdi:thermometer
    - entity: sensor.compensation_sensor_netatmo_bertram_2_office_basement_temperature
      name: Basement
      icon: mdi:thermometer
    - entity: sensor.compensation_sensor_rack_temperature
      name: Rack
      icon: mdi:thermometer
################################################################################
- type: custom:mini-graph-card
  name: Carbon Dioxide
  icon: mdi:molecule-co2
  font_size_header: 19
  aggregate_func: max
  hours_to_show: 24
  points_per_hour: 6
  line_width: 2
  tap_action: none
  show_state: true
  show_indicator: true
  show:
    extrema: true
    fill: false
  entities:
    - entity: sensor.compensation_sensor_netatmo_edwin_co2
      name: Edwin
    - entity: sensor.compensation_sensor_netatmo_parents_co2
      name: Parents
    - entity: sensor.compensation_sensor_netatmo_bertram_2_kitchen_co2
      name: Kitchen
    - entity: sensor.compensation_sensor_netatmo_bertram_2_office_pantry_co2
      name: Pantry
################################################################################
- type: entities
  entities:
    - entity: sensor.compensation_sensor_netatmo_edwin_co2
      name: Edwin
      icon: mdi:molecule-co2
    - entity: sensor.compensation_sensor_netatmo_parents_co2
      name: Parents
      icon: mdi:molecule-co2
    - entity: sensor.compensation_sensor_netatmo_bertram_2_office_co2
      name: Office
      icon: mdi:molecule-co2
    - entity: sensor.compensation_sensor_netatmo_bertram_2_kitchen_co2
      name: Kitchen
      icon: mdi:molecule-co2
    - entity: sensor.compensation_sensor_netatmo_bertram_2_office_pantry_co2
      name: Pantry
      icon: mdi:molecule-co2
    - entity: sensor.compensation_sensor_netatmo_bertram_2_office_lounge_co2
      name: Lounge
      icon: mdi:molecule-co2
    - entity: sensor.compensation_sensor_netatmo_bertram_2_office_dining_co2
      name: Dining
      icon: mdi:molecule-co2
################################################################################
- type: custom:mini-graph-card
  name: Humidity
  icon: mdi:water-percent
  font_size_header: 19
  aggregate_func: max
  hours_to_show: 24
  points_per_hour: 6
  line_width: 2
  tap_action: none
  show_state: true
  show_indicator: true
  show:
    extrema: true
    fill: false
  entities:
    - entity: sensor.compensation_sensor_roof_humidity
      name: Roof
    - entity: sensor.compensation_sensor_netatmo_ada_humidity
      name: Ada
    - entity: sensor.compensation_sensor_netatmo_edwin_humidity
      name: Edwin
    - entity: sensor.compensation_sensor_netatmo_parents_humidity
      name: Parents
################################################################################
- type: entities
  entities:
    - entity: sensor.compensation_sensor_roof_humidity
      name: Roof
      icon: mdi:water-percent
    - entity: sensor.compensation_sensor_netatmo_ada_humidity
      name: Ada
      icon: mdi:water-percent
    - entity: sensor.compensation_sensor_netatmo_edwin_humidity
      name: Edwin
      icon: mdi:water-percent
    - entity: sensor.compensation_sensor_netatmo_parents_humidity
      name: Parents
      icon: mdi:water-percent
    - entity: sensor.compensation_sensor_netatmo_bertram_2_office_humidity
      name: Office
      icon: mdi:water-percent
    - entity: sensor.compensation_sensor_netatmo_bertram_2_kitchen_humidity
      name: Kitchen
      icon: mdi:water-percent
    - entity: sensor.compensation_sensor_netatmo_bertram_2_office_pantry_humidity
      name: Pantry
      icon: mdi:water-percent
    - entity: sensor.compensation_sensor_netatmo_bertram_2_office_lounge_humidity
      name: Lounge
      icon: mdi:water-percent
    - entity: sensor.compensation_sensor_netatmo_bertram_2_office_dining_humidity
      name: Dining
      icon: mdi:water-percent
    - entity: sensor.compensation_sensor_netatmo_laundry_humidity
      name: Laundry
      icon: mdi:water-percent
    - entity: sensor.compensation_sensor_netatmo_bertram_2_office_basement_humidity
      name: Basement
      icon: mdi:water-percent
    - entity: sensor.compensation_sensor_rack_humidity
      name: Rack
      icon: mdi:water-percent
################################################################################
- type: custom:mini-graph-card
  name: Noise
  icon: mdi:volume-high
  font_size_header: 19
  aggregate_func: max
  hours_to_show: 24
  points_per_hour: 6
  line_width: 2
  tap_action: none
  show_state: true
  show_indicator: true
  show:
    extrema: true
    fill: false
  entities:
    - entity: sensor.compensation_sensor_netatmo_ada_noise
      name: Ada
    - entity: sensor.compensation_sensor_netatmo_edwin_noise
      name: Edwin
    - entity: sensor.compensation_sensor_netatmo_parents_noise
      name: Parents
    - entity: sensor.compensation_sensor_netatmo_bertram_2_office_noise
      name: Office
################################################################################
- type: entities
  entities:
    - entity: sensor.compensation_sensor_netatmo_ada_noise
      name: Ada
      icon: mdi:volume-high
    - entity: sensor.compensation_sensor_netatmo_edwin_noise
      name: Edwin
      icon: mdi:volume-high
    - entity: sensor.compensation_sensor_netatmo_parents_noise
      name: Parents
      icon: mdi:volume-high
    - entity: sensor.compensation_sensor_netatmo_bertram_2_office_noise
      name: Office
      icon: mdi:volume-high
    - entity: sensor.compensation_sensor_netatmo_bertram_2_kitchen_noise
      name: Kitchen
      icon: mdi:volume-high
    - entity: sensor.compensation_sensor_netatmo_laundry_noise
      name: Laundry
      icon: mdi:volume-high
################################################################################
