#######################################################################################
# WARNING: This file is written to by the build process, any manual edits will be lost!
#######################################################################################
- type: custom:mini-graph-card
  name: Temperature
  font_size_header: 19
  aggregate_func: max
  hours_to_show: 24
  points_per_hour: 6
  line_width: 2
  tap_action: none
  show_state: true
  show_indicator: true
  show:
    extrema: true
    fill: false
  entities:
    - sensor.roof_temperature
    - sensor.netatmo_ada_temperature
    - sensor.netatmo_edwin_temperature
    - sensor.netatmo_parents_temperature
- type: entities
  show_header_toggle: false
  entities:
    - entity: sensor.roof_temperature
    - entity: sensor.netatmo_ada_temperature
    - entity: sensor.netatmo_edwin_temperature
    - entity: sensor.netatmo_parents_temperature
    - entity: sensor.netatmo_bertram_2_office_temperature
    - entity: sensor.netatmo_bertram_2_kitchen_temperature
    - entity: sensor.netatmo_bertram_2_office_pantry_temperature
    - entity: sensor.netatmo_bertram_2_office_lounge_temperature
    - entity: sensor.netatmo_bertram_2_office_dining_temperature
    - entity: sensor.netatmo_laundry_temperature
    - entity: sensor.netatmo_bertram_2_office_basement_temperature
    - entity: sensor.rack_temperature
- type: custom:mini-graph-card
  name: Carbon Dioxide
  font_size_header: 19
  aggregate_func: max
  hours_to_show: 24
  points_per_hour: 6
  line_width: 2
  tap_action: none
  show_state: true
  show_indicator: true
  show:
    extrema: true
    fill: false
  entities:
    - sensor.netatmo_edwin_co2
    - sensor.netatmo_parents_co2
    - sensor.netatmo_bertram_2_kitchen_co2
    - sensor.netatmo_bertram_2_office_pantry_co2
- type: entities
  show_header_toggle: false
  entities:
    - entity: sensor.netatmo_edwin_co2
    - entity: sensor.netatmo_parents_co2
    - entity: sensor.netatmo_bertram_2_office_co2
    - entity: sensor.netatmo_bertram_2_kitchen_co2
    - entity: sensor.netatmo_bertram_2_office_pantry_co2
    - entity: sensor.netatmo_bertram_2_office_lounge_co2
    - entity: sensor.netatmo_bertram_2_office_dining_co2
- type: custom:mini-graph-card
  name: Humidity
  font_size_header: 19
  aggregate_func: max
  hours_to_show: 24
  points_per_hour: 6
  line_width: 2
  tap_action: none
  show_state: true
  show_indicator: true
  show:
    extrema: true
    fill: false
  entities:
    - sensor.roof_humidity
    - sensor.netatmo_ada_humidity
    - sensor.netatmo_edwin_humidity
    - sensor.netatmo_parents_humidity
- type: entities
  show_header_toggle: false
  entities:
    - entity: sensor.roof_humidity
    - entity: sensor.netatmo_ada_humidity
    - entity: sensor.netatmo_edwin_humidity
    - entity: sensor.netatmo_parents_humidity
    - entity: sensor.netatmo_bertram_2_office_humidity
    - entity: sensor.netatmo_bertram_2_kitchen_humidity
    - entity: sensor.netatmo_bertram_2_office_pantry_humidity
    - entity: sensor.netatmo_bertram_2_office_lounge_humidity
    - entity: sensor.netatmo_bertram_2_office_dining_humidity
    - entity: sensor.netatmo_laundry_humidity
    - entity: sensor.netatmo_bertram_2_office_basement_humidity
    - entity: sensor.rack_humidity
- type: custom:mini-graph-card
  name: Noise
  font_size_header: 19
  aggregate_func: max
  hours_to_show: 24
  points_per_hour: 6
  line_width: 2
  tap_action: none
  show_state: true
  show_indicator: true
  show:
    extrema: true
    fill: false
  entities:
    - sensor.netatmo_ada_noise
    - sensor.netatmo_edwin_noise
    - sensor.netatmo_parents_noise
    - sensor.netatmo_bertram_2_office_noise
- type: entities
  show_header_toggle: false
  entities:
    - entity: sensor.netatmo_ada_noise
    - entity: sensor.netatmo_edwin_noise
    - entity: sensor.netatmo_parents_noise
    - entity: sensor.netatmo_bertram_2_office_noise
    - entity: sensor.netatmo_bertram_2_kitchen_noise
    - entity: sensor.netatmo_laundry_noise
