#######################################################################################
# WARNING: This file is written to by the build process, any manual edits will be lost!
#######################################################################################
- type: custom:mini-graph-card
  name: Temperature
  font_size_header: 19
  aggregate_func: max
  hours_to_show: 24
  points_per_hour: 6
  line_width: 2
  tap_action: none
  show_state: true
  show_indicator: true
  show:
    extrema: true
    fill: false
  entities:
    - entity: sensor.roof_temperature
      name: Roof
    - entity: sensor.netatmo_ada_temperature
      name: Ada
    - entity: sensor.netatmo_edwin_temperature
      name: Edwin
    - entity: sensor.netatmo_parents_temperature
      name: Parents
- type: entities
  show_header_toggle: false
  entities:
    - entity: sensor.roof_temperature
      name: Roof
    - entity: sensor.netatmo_ada_temperature
      name: Ada
    - entity: sensor.netatmo_edwin_temperature
      name: Edwin
    - entity: sensor.netatmo_parents_temperature
      name: Parents
    - entity: sensor.netatmo_bertram_2_office_temperature
      name: Office
    - entity: sensor.netatmo_bertram_2_kitchen_temperature
      name: Kitchen
    - entity: sensor.netatmo_bertram_2_office_pantry_temperature
      name: Pantry
    - entity: sensor.netatmo_bertram_2_office_lounge_temperature
      name: Lounge
    - entity: sensor.netatmo_bertram_2_office_dining_temperature
      name: Dining
    - entity: sensor.netatmo_laundry_temperature
      name: Laundry
    - entity: sensor.netatmo_bertram_2_office_basement_temperature
      name: Basement
    - entity: sensor.rack_temperature
      name: Rack
- type: custom:mini-graph-card
  name: Carbon Dioxide
  font_size_header: 19
  aggregate_func: max
  hours_to_show: 24
  points_per_hour: 6
  line_width: 2
  tap_action: none
  show_state: true
  show_indicator: true
  show:
    extrema: true
    fill: false
  entities:
    - entity: sensor.netatmo_edwin_co2
      name: Edwin
    - entity: sensor.netatmo_parents_co2
      name: Parents
    - entity: sensor.netatmo_bertram_2_kitchen_co2
      name: Kitchen
    - entity: sensor.netatmo_bertram_2_office_pantry_co2
      name: Pantry
- type: entities
  show_header_toggle: false
  entities:
    - entity: sensor.netatmo_edwin_co2
      name: Edwin
    - entity: sensor.netatmo_parents_co2
      name: Parents
    - entity: sensor.netatmo_bertram_2_office_co2
      name: Office
    - entity: sensor.netatmo_bertram_2_kitchen_co2
      name: Kitchen
    - entity: sensor.netatmo_bertram_2_office_pantry_co2
      name: Pantry
    - entity: sensor.netatmo_bertram_2_office_lounge_co2
      name: Lounge
    - entity: sensor.netatmo_bertram_2_office_dining_co2
      name: Dining
- type: custom:mini-graph-card
  name: Humidity
  font_size_header: 19
  aggregate_func: max
  hours_to_show: 24
  points_per_hour: 6
  line_width: 2
  tap_action: none
  show_state: true
  show_indicator: true
  show:
    extrema: true
    fill: false
  entities:
    - entity: sensor.roof_humidity
      name: Roof
    - entity: sensor.netatmo_ada_humidity
      name: Ada
    - entity: sensor.netatmo_edwin_humidity
      name: Edwin
    - entity: sensor.netatmo_parents_humidity
      name: Parents
- type: entities
  show_header_toggle: false
  entities:
    - entity: sensor.roof_humidity
      name: Roof
    - entity: sensor.netatmo_ada_humidity
      name: Ada
    - entity: sensor.netatmo_edwin_humidity
      name: Edwin
    - entity: sensor.netatmo_parents_humidity
      name: Parents
    - entity: sensor.netatmo_bertram_2_office_humidity
      name: Office
    - entity: sensor.netatmo_bertram_2_kitchen_humidity
      name: Kitchen
    - entity: sensor.netatmo_bertram_2_office_pantry_humidity
      name: Pantry
    - entity: sensor.netatmo_bertram_2_office_lounge_humidity
      name: Lounge
    - entity: sensor.netatmo_bertram_2_office_dining_humidity
      name: Dining
    - entity: sensor.netatmo_laundry_humidity
      name: Laundry
    - entity: sensor.netatmo_bertram_2_office_basement_humidity
      name: Basement
    - entity: sensor.rack_humidity
      name: Rack
- type: custom:mini-graph-card
  name: Noise
  font_size_header: 19
  aggregate_func: max
  hours_to_show: 24
  points_per_hour: 6
  line_width: 2
  tap_action: none
  show_state: true
  show_indicator: true
  show:
    extrema: true
    fill: false
  entities:
    - entity: sensor.netatmo_ada_noise
      name: Ada
    - entity: sensor.netatmo_edwin_noise
      name: Edwin
    - entity: sensor.netatmo_parents_noise
      name: Parents
    - entity: sensor.netatmo_bertram_2_office_noise
      name: Office
- type: entities
  show_header_toggle: false
  entities:
    - entity: sensor.netatmo_ada_noise
      name: Ada
    - entity: sensor.netatmo_edwin_noise
      name: Edwin
    - entity: sensor.netatmo_parents_noise
      name: Parents
    - entity: sensor.netatmo_bertram_2_office_noise
      name: Office
    - entity: sensor.netatmo_bertram_2_kitchen_noise
      name: Kitchen
    - entity: sensor.netatmo_laundry_noise
      name: Laundry
