- type: entities
  title: Fans
  entities:
    - entity: fan.ada
      name: Ada Fan
    - entity: fan.edwin
      name: Edwin Fan
    - entity: fan.lounge
      name: Lounge Fan
    - entity: fan.parents
      name: Parents Fan
    - entity: switch.kitchen_fan
      name: Kitchen Fan
      icon: mdi:fan
    - entity: fan.deck1
      name: Deck East Fan
    - entity: fan.deck2
      name: Deck West Fan

- type: entities
  title: Switches
  entities:
    - entity: switch.kitchen_coffee
      name: Kitchen Coffee
      icon: mdi:coffee-outline
    - entity: switch.bathroom_towelrails
      name: Bathroom Towel Rails
      icon: mdi:radiator

- type: entities
  title: Lights
  entities:
    - entity: light.ada
      name: Ada Lamp
    - entity: light.ada_light
      name: Ada Main
      icon: mdi:lightbulb-group-outline
    - entity: light.bathroom
      name: Bathroom Main
    - entity: light.dining
      name: Dining Main
    - entity: light.edwin
      name: Edwin Lamp
    - entity: light.edwin_light
      name: Edwin Main
      icon: mdi:lightbulb-group-outline
    - entity: light.ensuite
      name: Ensuite Main
    - entity: light.hallway
      name: Hallyway Main
    - entity: light.kitchen
      name: Kitchen Main
    - entity: light.laundry
      name: Laundry Main
    - entity: light.lounge
      name: Lounge Main
      icon: mdi:lightbulb-group-outline
    - entity: light.lamp
      name: Lounge Lamp
    - entity: light.lounge_light
      name: Lounge Fan
      icon: mdi:lightbulb-group-outline
    - entity: light.office
      name: Office Main
    - entity: light.pantry
      name: Pantry Main
    - entity: light.parents
      name: Parents Main
    - entity: light.wardrobe
      name: Wardrobe Main
    - entity: switch.deck_festoons
      name: Deck Festoons
      icon: mdi:lightbulb-group-outline

- type: entities
  title: Resets - CAREFUL!
  show_header_toggle: false
  entities:
    - entity: switch.lounge_tv
      name: Lounge TV
      icon: mdi:youtube-tv
    - entity: switch.rack_modem
      name: Rack Modem
      icon: mdi:access-point-network