- type: entities
  title: Fans
  entities:
    - entity: fan.ada
    - entity: fan.edwin
    - entity: fan.lounge
    - entity: fan.parents
    - entity: fan.deck1
    - entity: fan.deck2

- type: entities
  title: Lights
  entities:
    - entity: light.ada
      name: Ada Lamp
    - entity: light.ada_light
      name: Ada Main
    - entity: light.bathroom
      name: Bathroom Main
    - entity: light.dining
      name: Dining Main
    - entity: light.edwin
      name: Edwin Lamp
    - entity: light.edwin_light
      name: Edwin Main
    - entity: light.ensuite
      name: Ensuite Main
    - entity: light.hallway
      name: Hallyway Main
    - entity: light.kitchen
      name: Kitchen Main
    - entity: light.laundry
      name: Laundry Main
    - entity: light.lounge
      name: Lounge Main
    - entity: light.lamp
      name: Lounge Lamp
    - entity: light.lounge_light
      name: Lounge Fan
    - entity: light.office
      name: Office Main
    - entity: light.pantry
      name: Pantry Main
    - entity: light.parents
      name: Parents Main
    - entity: light.wardrobe
      name: Wardrobe Main

- type: entities
  title: Switches
  entities:
    - entity: switch.kitchenfan
      name: Kitchen Fan
    - entity: switch.towelrails
      name: Bathroom Towel Rails