#######################################################################################
# WARNING: This file is written to by the build process, any manual edits will be lost!
#######################################################################################
- type: entities
  title: Fans
  entities:
    - entity: fan.ada
      name: Ada
      icon: mdi:fan
    - entity: fan.edwin
      name: Edwin
      icon: mdi:fan
    - entity: fan.parents
      name: Parents
      icon: mdi:fan
    - entity: switch.kitchen_fan
      name: Kitchen
      icon: mdi:fan
    - entity: fan.lounge
      name: Lounge
      icon: mdi:fan
    - entity: fan.deck_east
      name: Deck East
      icon: mdi:fan
    - entity: fan.deck_west
      name: Deck West
      icon: mdi:fan
- type: entities
  title: Lights
  entities:
    - entity: light.ada_light
      name: Ada Main
    - entity: light.edwin_light
      name: Edwin Main
    - entity: light.lounge_light
      name: Lounge Fan
    - entity: light.hallway
      name: Hallway Main
    - entity: light.dining
      name: Dining Main
    - entity: light.lounge
      name: Lounge Main
    - entity: light.parents
      name: Parents Main
    - entity: light.kitchen
      name: Kitchen Main
    - entity: light.laundry
      name: Laundry Main
    - entity: light.pantry
      name: Pantry Main
    - entity: light.office
      name: Office Main
    - entity: light.bathroom
      name: Bathroom Main
    - entity: light.ensuite
      name: Ensuite Main
    - entity: light.wardrobe
      name: Wardrobe Main
    - entity: light.edwin
      name: Edwin Lamp
    - entity: light.ada
      name: Ada Lamp
    - entity: light.lamp
      name: Lounge Lamp
- type: entities
  title: Switches
  entities:
    - entity: switch.kitchen_dish_washer
      name: Dish Washer
      icon: mdi:dishwasher
    - entity: switch.laundry_clothes_dryer
      name: Clothes Dryer
      icon: mdi:tumble-dryer
    - entity: switch.laundry_washing_machine
      name: Washing Machine
      icon: mdi:washing-machine
    - entity: switch.kitchen_coffee_machine
      name: Coffee Machine
      icon: mdi:coffee-maker
    - entity: switch.deck_lights
      name: Deck Lights
      icon: mdi:string-lights
    - entity: switch.bathroom_rails
      name: Bathroom Rails
      icon: mdi:radiator
    - entity: switch.study_battery_charger
      name: Battery Charger
      icon: mdi:battery-charging-30
    - entity: switch.laundry_vacuum_charger
      name: Vacuum Charger
      icon: mdi:battery-charging-30
    - entity: switch.various_adhoc_outlet
      name: Adhoc Outlet
      icon: mdi:power-plug-outline
- type: entities
  title: Resets - CAREFUL!
  show_header_toggle: false
  entities:
    - entity: switch.study_outlet
      name: Study Outlet
      icon: mdi:power-plug-outline
    - entity: switch.office_outlet
      name: Office Outlet
      icon: mdi:power-plug-outline
    - entity: switch.lounge_tv
      name: Lounge TV
      icon: mdi:television
    - entity: switch.rack_outlet
      name: Server Rack
      icon: mdi:server
    - entity: switch.roof_network_switch
      name: Network Switch
      icon: mdi:server-network
    - entity: switch.rack_internet_modem
      name: Internet Modem
      icon: mdi:router-wireless
