#######################################################################################
# WARNING: This file is written to by the build process, any manual edits will be lost!
################################################################################
- type: entities
  title: Routines
  show_header_toggle: false
  entities:
    - entity: input_boolean.home_sleep
      name: Sleep
      icon: mdi:chat-sleep
    - entity: input_boolean.home_wakeup
      name: Wakeup
      icon: mdi:white-balance-sunny
################################################################################
- type: custom:layout-break
################################################################################
- type: entities
  title: Fans
  entities:
    - entity: fan.ada
      name: Ada
      icon: mdi:fan
    - entity: fan.edwin
      name: Edwin
      icon: mdi:fan
    - entity: fan.parents
      name: Parents
      icon: mdi:fan
    - entity: switch.kitchen_fan
      name: Kitchen
      icon: mdi:fan
    - entity: fan.lounge
      name: Lounge
      icon: mdi:fan
    - entity: fan.deck_east
      name: Deck East
      icon: mdi:fan
    - entity: fan.deck_west
      name: Deck West
      icon: mdi:fan
################################################################################
- type: custom:layout-break
################################################################################
- type: entities
  title: Lights
  entities:
    - entity: light.ada_light
      name: Ada Main
      icon: mdi:lightbulb-group
    - entity: light.ada_lamp
      name: Ada Lamp
    - entity: light.edwin_light
      name: Edwin Main
      icon: mdi:lightbulb-group
    - entity: light.edwin_lamp
      name: Edwin Lamp
    - entity: light.hallway_main
      name: Hallway Main
    - entity: light.dining_main
      name: Dining Main
    - entity: light.lounge_main
      name: Lounge Main
    - entity: light.lounge_light
      name: Lounge Fan
      icon: mdi:lightbulb-group
    - entity: light.lounge_lamp
      name: Lounge Lamp
    - entity: light.parents_main
      name: Parents Main
    - entity: light.kitchen_main
      name: Kitchen Main
    - entity: light.laundry_main
      name: Laundry Main
    - entity: light.pantry_main
      name: Pantry Main
    - entity: light.office_main
      name: Office Main
    - entity: light.bathroom_main
      name: Bathroom Main
    - entity: light.ensuite_main
      name: Ensuite Main
    - entity: light.wardrobe_main
      name: Wardrobe Main
    - entity: switch.deck_lights
      name: Deck Festoons
      icon: mdi:lightbulb-group
################################################################################
- type: custom:layout-break
################################################################################
- type: entities
  title: Default Adaptive Lighting
  show_header_toggle: false
  entities:
    - entity: switch.adaptive_lighting_default
      name: Status
    - entity: switch.adaptive_lighting_sleep_mode_default
      name: Sleep
################################################################################
- type: entities
  title: Bedroom Adaptive Lighting
  show_header_toggle: false
  entities:
    - entity: switch.adaptive_lighting_bedroom
      name: Status
    - entity: switch.adaptive_lighting_sleep_mode_bedroom
      name: Sleep
################################################################################
- type: entities
  title: Night Light Adaptive Lighting
  show_header_toggle: false
  entities:
    - entity: switch.adaptive_lighting_night_light
      name: Status
    - entity: switch.adaptive_lighting_sleep_mode_night_light
      name: Sleep
################################################################################
