#######################################################################################
# WARNING: This file is written to by the build process, any manual edits will be lost!
################################################################################
- type: entities
  title: Routines
  show_header_toggle: false
  entities:
    - entity: input_boolean.home_movie
      name: Movie
      icon: mdi:youtube-tv
    - entity: input_boolean.home_sleep
      name: Sleep
      icon: mdi:chat-sleep
    - entity: input_boolean.home_reset
      name: Reset
      icon: mdi:refresh-circle
    - entity: switch.bathroom_rails
      name: Towel Rails
      icon: mdi:radiator
    - entity: switch.roof_water_heater_booster
      name: Water Booster
      icon: mdi:thermometer-water
################################################################################
- type: custom:layout-break
################################################################################
- type: entities
  title: Fans
  entities:
    - entity: fan.ada_fan
      name: Ada
      icon: mdi:fan
    - entity: fan.edwin_fan
      name: Edwin
      icon: mdi:fan
    - entity: fan.parents_fan
      name: Parents
      icon: mdi:fan
    - entity: switch.kitchen_fan
      name: Kitchen
      icon: mdi:fan
    - entity: fan.lounge_fan
      name: Lounge
      icon: mdi:fan
    - entity: fan.deck_fan
      name: Deck
      icon: mdi:fan
################################################################################
- type: entities
  title: Air Purifiers
  entities:
    - entity: fan.air_purifier
      name: Lounge
      icon: mdi:air-purifier
################################################################################
- type: custom:layout-break
################################################################################
- type: entities
  title: Lights
  entities:
    - entity: light.ada_fan
      name: Ada Main
      icon: mdi:lightbulb-group
    - entity: light.ada_lamp
      name: Ada Lamp
    - entity: light.edwin_lamp
      name: Edwin Lamp
    - entity: light.edwin_fan
      name: Edwin Main
      icon: mdi:lightbulb-group
    - entity: light.edwin_night_light
      name: Edwin Night Light
    - entity: light.hallway_main
      name: Hallway Main
    - entity: light.dining_main
      name: Dining Main
    - entity: light.lounge_main
      name: Lounge Main
    - entity: light.lounge_fan
      name: Lounge Fan
      icon: mdi:lightbulb-group
    - entity: light.parents_main
      name: Parents Main
    - entity: light.kitchen_main
      name: Kitchen Main
    - entity: light.laundry_main
      name: Laundry Main
    - entity: light.pantry_main
      name: Pantry Main
    - entity: light.office_main
      name: Office Main
    - entity: light.bathroom_main
      name: Bathroom Main
    - entity: light.ensuite_main
      name: Ensuite Main
    - entity: light.wardrobe_main
      name: Wardrobe Main
    - entity: switch.deck_festoons
      name: Deck Festoons
      icon: mdi:lightbulb-group
################################################################################
- type: custom:layout-break
################################################################################
- type: entities
  title: Default Adaptive Lighting
  show_header_toggle: false
  entities:
    - entity: switch.adaptive_lighting_default
      name: Status
    - entity: switch.adaptive_lighting_sleep_mode_default
      name: Sleep
################################################################################
- type: entities
  title: Bedroom Adaptive Lighting
  show_header_toggle: false
  entities:
    - entity: switch.adaptive_lighting_bedroom
      name: Status
    - entity: switch.adaptive_lighting_sleep_mode_bedroom
      name: Sleep
################################################################################
- type: entities
  title: Night Light Adaptive Lighting
  show_header_toggle: false
  entities:
    - entity: switch.adaptive_lighting_night_light
      name: Status
    - entity: switch.adaptive_lighting_sleep_mode_night_light
      name: Sleep
################################################################################
