- type: custom:mini-graph-card
  name: Power Consumption
  font_size_header: 19
  aggregate_func: max
  hours_to_show: 24
  points_per_hour: 6
  line_width: 2
  tap_action: none
  show_state: true
  show_indicator: true
  show:
    extrema: true
    fill: false
  entities:
- type: entities
  show_header_toggle: false
  entities:
    - entity: sensor.various_adhoc_power_consumption
    - entity: sensor.rack_modem_power_consumption
    - entity: sensor.rack_power_power_consumption
    - entity: sensor.roof_switch_power_consumption
    - entity: sensor.kitchen_fan_power_consumption
    - entity: sensor.kitchen_fridge_power_consumption
    - entity: sensor.kitchen_coffee_power_consumption
    - entity: sensor.deck_freezer_power_consumption
    - entity: sensor.deck_festoons_power_consumption
    - entity: sensor.office_power_power_consumption
    - entity: sensor.lounge_tv_power_consumption
    - entity: sensor.study_power_power_consumption
    - entity: sensor.bathroom_towelrails_power_consumption
- type: custom:mini-graph-card
  name: Energy Consumption
  font_size_header: 19
  aggregate_func: max
  hours_to_show: 24
  points_per_hour: 6
  line_width: 2
  tap_action: none
  show_state: true
  show_indicator: true
  show:
    extrema: true
    fill: false
  entities:
- type: entities
  show_header_toggle: false
  entities:
    - entity: sensor.various_adhoc_energy_consumption
    - entity: sensor.rack_modem_energy_consumption
    - entity: sensor.rack_power_energy_consumption
    - entity: sensor.roof_switch_energy_consumption
    - entity: sensor.kitchen_fan_energy_consumption
    - entity: sensor.kitchen_fridge_energy_consumption
    - entity: sensor.kitchen_coffee_energy_consumption
    - entity: sensor.deck_freezer_energy_consumption
    - entity: sensor.deck_festoons_energy_consumption
    - entity: sensor.lounge_tv_energy_consumption
    - entity: sensor.study_power_energy_consumption
    - entity: sensor.office_power_energy_consumption
    - entity: sensor.bathroom_towelrails_energy_consumption
