#######################################################################################
# WARNING: This file is written to by the build process, any manual edits will be lost!
#######################################################################################
- type: custom:mini-graph-card
  name: Power Consumption
  font_size_header: 19
  aggregate_func: max
  hours_to_show: 24
  points_per_hour: 6
  line_width: 2
  tap_action: none
  show_state: true
  show_indicator: true
  show:
    extrema: true
    fill: false
  entities:
    - sensor.rack_power_current_consumption
    - sensor.office_power_current_consumption
    - sensor.study_power_current_consumption
- type: entities
  show_header_toggle: false
  entities:
    - entity: sensor.various_adhoc_current_consumption
    - entity: sensor.rack_modem_current_consumption
    - entity: sensor.rack_power_current_consumption
    - entity: sensor.roof_switch_current_consumption
    - entity: sensor.kitchen_fan_current_consumption
    - entity: sensor.kitchen_fridge_current_consumption
    - entity: sensor.kitchen_coffee_current_consumption
    - entity: sensor.deck_freezer_current_consumption
    - entity: sensor.deck_festoons_current_consumption
    - entity: sensor.office_power_current_consumption
    - entity: sensor.lounge_tv_current_consumption
    - entity: sensor.study_power_current_consumption
    - entity: sensor.bathroom_towelrails_current_consumption
