#######################################################################################
# WARNING: This file is written to by the build process, any manual edits will be lost!
################################################################################
- type: custom:mini-graph-card
  name: Current Power Consumption
  icon: mdi:home-lightning-bolt
  font_size_header: 19
  aggregate_func: max
  hours_to_show: 24
  points_per_hour: 6
  line_width: 2
  tap_action: none
  show_state: true
  show_indicator: true
  show:
    extrema: true
    fill: false
  entities:
    - entity: sensor.home_peak_power
      name: Peak Load
    - entity: sensor.home_base_power
      name: Base Load
    - entity: sensor.home_power
      name: Home Load
################################################################################
- type: entities
  entities:
    - entity: sensor.home_peak_power
      name: Peak Load
      icon: mdi:home-lightning-bolt
    - entity: sensor.home_base_power
      name: Base Load
      icon: mdi:home-lightning-bolt
    - entity: sensor.home_power
      name: Home Load
      icon: mdi:home-lightning-bolt
################################################################################
- type: entities
  entities:
    - entity: sensor.various_adhoc_outlet_current_consumption
      name: Adhoc Outlet
      icon: mdi:home-lightning-bolt
    - entity: sensor.study_battery_charger_current_consumption
      name: Battery Charger
      icon: mdi:home-lightning-bolt
    - entity: sensor.laundry_vacuum_charger_current_consumption
      name: Vacuum Charger
      icon: mdi:home-lightning-bolt
    - entity: sensor.home_lights_power
      name: Home Lights
      icon: mdi:home-lightning-bolt
    - entity: sensor.home_fans_power
      name: Home Fans
      icon: mdi:home-lightning-bolt
    - entity: sensor.kitchen_dish_washer_current_consumption
      name: Dish Washer
      icon: mdi:home-lightning-bolt
    - entity: sensor.laundry_clothes_dryer_current_consumption
      name: Clothes Dryer
      icon: mdi:home-lightning-bolt
    - entity: sensor.laundry_washing_machine_current_consumption
      name: Washing Machine
      icon: mdi:home-lightning-bolt
    - entity: sensor.kitchen_coffee_machine_current_consumption
      name: Coffee Machine
      icon: mdi:home-lightning-bolt
    - entity: sensor.kitchen_fridge_current_consumption
      name: Kitchen Fridge
      icon: mdi:home-lightning-bolt
    - entity: sensor.deck_freezer_current_consumption
      name: Deck Freezer
      icon: mdi:home-lightning-bolt
    - entity: sensor.deck_festoons_current_consumption
      name: Deck Festoons
      icon: mdi:home-lightning-bolt
    - entity: sensor.lounge_tv_current_consumption
      name: Lounge TV
      icon: mdi:home-lightning-bolt
    - entity: sensor.bathroom_rails_current_consumption
      name: Bathroom Rails
      icon: mdi:home-lightning-bolt
    - entity: sensor.study_outlet_current_consumption
      name: Study Outlet
      icon: mdi:home-lightning-bolt
    - entity: sensor.office_outlet_current_consumption
      name: Office Outlet
      icon: mdi:home-lightning-bolt
    - entity: sensor.server_network_power
      name: Server & Network
      icon: mdi:home-lightning-bolt
################################################################################
- type: custom:layout-break
################################################################################
- type: custom:mini-graph-card
  name: Daily Energy Consumption
  icon: mdi:battery-charging
  font_size_header: 19
  aggregate_func: max
  hours_to_show: 24
  points_per_hour: 6
  line_width: 2
  tap_action: none
  show_state: true
  show_indicator: true
  show:
    extrema: true
    fill: false
  entities:
    - entity: sensor.home_peak_energy_daily
      name: Peak Load
    - entity: sensor.home_base_energy_daily
      name: Base Load
    - entity: sensor.home_energy_daily
      name: Home Load
################################################################################
- type: entities
  entities:
    - entity: sensor.home_peak_energy_daily
      name: Peak Load
      icon: mdi:battery-charging
    - entity: sensor.home_base_energy_daily
      name: Base Load
      icon: mdi:battery-charging
    - entity: sensor.home_energy_daily
      name: Home Load
      icon: mdi:battery-charging
################################################################################
- type: entities
  entities:
    - entity: sensor.various_adhoc_outlet_today_s_consumption
      name: Adhoc Outlet
      icon: mdi:battery-charging
    - entity: sensor.study_battery_charger_today_s_consumption
      name: Battery Charger
      icon: mdi:battery-charging
    - entity: sensor.laundry_vacuum_charger_today_s_consumption
      name: Vacuum Charger
      icon: mdi:battery-charging
    - entity: sensor.home_lights_energy_daily
      name: Home Lights
      icon: mdi:battery-charging
    - entity: sensor.home_fans_energy_daily
      name: Home Fans
      icon: mdi:battery-charging
    - entity: sensor.kitchen_dish_washer_today_s_consumption
      name: Dish Washer
      icon: mdi:battery-charging
    - entity: sensor.laundry_clothes_dryer_today_s_consumption
      name: Clothes Dryer
      icon: mdi:battery-charging
    - entity: sensor.laundry_washing_machine_today_s_consumption
      name: Washing Machine
      icon: mdi:battery-charging
    - entity: sensor.kitchen_coffee_machine_today_s_consumption
      name: Coffee Machine
      icon: mdi:battery-charging
    - entity: sensor.kitchen_fridge_today_s_consumption
      name: Kitchen Fridge
      icon: mdi:battery-charging
    - entity: sensor.deck_freezer_today_s_consumption
      name: Deck Freezer
      icon: mdi:battery-charging
    - entity: sensor.deck_festoons_today_s_consumption
      name: Deck Festoons
      icon: mdi:battery-charging
    - entity: sensor.lounge_tv_today_s_consumption
      name: Lounge TV
      icon: mdi:battery-charging
    - entity: sensor.bathroom_rails_today_s_consumption
      name: Bathroom Rails
      icon: mdi:battery-charging
    - entity: sensor.study_outlet_today_s_consumption
      name: Study Outlet
      icon: mdi:battery-charging
    - entity: sensor.office_outlet_today_s_consumption
      name: Office Outlet
      icon: mdi:battery-charging
    - entity: sensor.server_network_energy_daily
      name: Server & Network
      icon: mdi:battery-charging
################################################################################
- type: custom:layout-break
################################################################################
