- type: custom:mini-graph-card
  name: Power Consumption
  font_size_header: 19
  aggregate_func: max
  hours_to_show: 24
  points_per_hour: 6
  line_width: 2
  tap_action: none
  show_state: true
  show_indicator: true
  show:
    extrema: true
    fill: false
  entities:
    - sensor.kitchen_fridge_power_consumption
    - sensor.rack_power_power_consumption
    - sensor.office_power_power_consumption
    - sensor.kitchen_fan_power_consumption
    - sensor.bathroom_towelrails_power_consumption
- type: entities
  show_header_toggle: false
  entities:
    - entity: sensor.kitchen_fridge_power_consumption
    - entity: sensor.rack_power_power_consumption
    - entity: sensor.office_power_power_consumption
    - entity: sensor.kitchen_fan_power_consumption
    - entity: sensor.bathroom_towelrails_power_consumption
- type: custom:mini-graph-card
  name: Energy Consumption
  font_size_header: 19
  aggregate_func: max
  hours_to_show: 24
  points_per_hour: 6
  line_width: 2
  tap_action: none
  show_state: true
  show_indicator: true
  show:
    extrema: true
    fill: false
  entities:
    - sensor.kitchen_fridge_energy_consumption
    - sensor.rack_power_energy_consumption
    - sensor.office_energy_consumption
    - sensor.kitchen_fan_energy_consumption
    - sensor.bathroom_towelrails_energy_consumption
- type: entities
  show_header_toggle: false
  entities:
    - entity: sensor.kitchen_fridge_energy_consumption
    - entity: sensor.rack_power_energy_consumption
    - entity: sensor.office_energy_consumption
    - entity: sensor.kitchen_fan_energy_consumption
    - entity: sensor.bathroom_towelrails_energy_consumption
