#######################################################################################
# WARNING: This file is written to by the build process, any manual edits will be lost!
################################################################################
- type: custom:layout-break
################################################################################
- type: media-control
  entity: media_player.parents_speaker
################################################################################
- type: custom:layout-break
################################################################################
- type: media-control
  entity: media_player.kitchen_home
################################################################################
- type: media-control
  entity: media_player.kitchen_speaker
################################################################################
- type: custom:layout-break
################################################################################
- type: media-control
  entity: media_player.lounge_speaker
################################################################################
- type: media-control
  entity: media_player.lounge_tv
################################################################################
