#######################################################################################
# WARNING: This file is written to by the build process, any manual edits will be lost!
################################################################################
- type: picture-entity
  entity: camera.uvc_ada_medium
  camera_view: live
################################################################################
- type: picture-entity
  entity: camera.uvc_edwin_medium
  camera_view: live
################################################################################
- type: custom:layout-break
################################################################################
- type: entities
  title: Fan Motion
  entities:
    - entity: binary_sensor.ada_occupancy
      name: Ada
    - entity: binary_sensor.edwin_occupancy
      name: Edwin
    - entity: binary_sensor.parents_occupancy
      name: Parents
    - entity: binary_sensor.lounge_occupancy
      name: Lounge
    - entity: binary_sensor.deck_east_occupancy
      name: Deck East
    - entity: binary_sensor.deck_west_occupancy
      name: Deck West
################################################################################
- type: entities
  title: Camera Motion
  entities:
    - entity: binary_sensor.uvc_ada_motion
      name: Ada
    - entity: binary_sensor.uvc_edwin_motion
      name: Edwin
################################################################################
