#######################################################################################
# WARNING: This file is written to by the build process, any manual edits will be lost!
#######################################################################################
- type: picture-entity
  entity: camera.uvc_ada_medium
- type: picture-entity
  entity: camera.uvc_edwin_medium
