#######################################################################################
# WARNING: This file is written to by the build process, any manual edits will be lost!
#######################################################################################
- type: entities
  title: Netatmo Battery
  entities:
    - entity: sensor.netatmo_bertram_2_office_pantry_battery_percent
      name: Pantry
      icon: mdi:battery-30
    - entity: sensor.netatmo_bertram_2_office_lounge_battery_percent
      name: Lounge
      icon: mdi:battery-30
    - entity: sensor.netatmo_bertram_2_office_dining_battery_percent
      name: Dining
      icon: mdi:battery-30
    - entity: sensor.netatmo_bertram_2_office_basement_battery_percent
      name: Basement
      icon: mdi:battery-30
- type: entities
  title: Sonos Battery
  entities:
    - entity: sensor.parents_speaker_battery
      name: Parents
      icon: mdi:battery-30
    - entity: sensor.kitchen_home_battery
      name: Kitchen
      icon: mdi:battery-30
- type: entities
  title: Davis Battery
  entities:
    - entity: sensor.weatherstation_system_battery_status
      name: System Status
      icon: mdi:battery-30
    - entity: sensor.weatherstation_console_battery_voltage
      name: Console Voltage
      icon: mdi:battery-30
- type: entities
  title: Davis Telemetry
  entities:
    - entity: sensor.weatherstation_sample_period
      name: Sample Period
      icon: mdi:clipboard-clock-outline
    - entity: sensor.weatherstation_coms_signal_quality
      name: Coms Signal Quality
      icon: mdi:signal
