#######################################################################################
# WARNING: This file is written to by the build process, any manual edits will be lost!
#######################################################################################
- type: custom:mini-graph-card
  name: Rain
  font_size_header: 19
  aggregate_func: max
  hours_to_show: 24
  points_per_hour: 6
  line_width: 2
  tap_action: none
  show_state: true
  show_indicator: true
  show:
    extrema: true
    fill: false
  entities:
    - sensor.roof_rain_rate
- type: entities
  show_header_toggle: false
  entities:
    - entity: sensor.roof_rain_rate
    - entity: sensor.roof_hourly_rain
    - entity: sensor.roof_daily_rain
    - entity: sensor.roof_monthly_rain
    - entity: sensor.roof_yearly_rain
