x-common: &common
services:
  unpoller:
    image: unpoller:${SERVICE_VERSION_ABSOLUTE}
    container_name: unpoller
    init: true
    restart: ${SERVICE_RESTART}
    environment:
      - TZ=Australia/Perth
      - INFLUXDB_IP
      - INFLUXDB_HTTP_PORT
      - INFLUXDB_USER_PRIVATE
      - INFLUXDB_TOKEN
      - INFLUXDB_BUCKET_HOST_PRIVATE
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "100m"
    deploy:
      resources:
        limits:
          memory: 2G
