x-common: &common
services:
  unpoller:
    image: unpoller:${SERVICE_VERSION_ABSOLUTE}
    container_name: unpoller
    init: true
    restart: ${SERVICE_RESTART}
    environment:
      - TZ=Australia/Perth
    ports:
      - ${UNPOLLER_HTTP_PORT}:${UNPOLLER_HTTP_PORT}
    healthcheck:
      test: /asystem/etc/healthcheck.sh
      interval: 2m
      timeout: 10s
      retries: 3
      start_period: 1m
      start_interval: 10s
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "100m"
    deploy:
      resources:
        limits:
          memory: 2G
