version: '3.7'
services:
  wrangle:
    container_name: wrangle
    image: wrangle:${SERVICE_VERSION_ABSOLUTE}
    init: true
    restart: ${SERVICE_RESTART}
    environment:
      - TZ=Australia/Perth
      - INFLUXDB_PORT
      - INFLUXDB_HOST
      - DROPBOX_TOKEN
    volumes:
      - ${SERVICE_DATA_DIR}:/asystem/runtime
      - ${SERVICE_DATA_DIR}/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    deploy:
      resources:
        limits:
          memory: 5G