version: '3.7'
services:
  wrangle:
    container_name: wrangle
    image: telegraf:1.15.3
    init: true
    restart: ${RESTART}
    environment:
      - TZ=Australia/Perth
      - HOST_IP
      - HOST_NAME
    volumes:
      - ${DATA_DIR}/telegraf.conf:/etc/telegraf/telegraf.conf:ro
