version: '3.7'
services:
  wrangle:
    container_name: wrangle
    image: wrangle:${SERVICE_VERSION_ABSOLUTE}
    init: true
    restart: ${SERVICE_RESTART}
    environment:
      - TZ=Australia/Perth
      - INFLUXDB_HOST
      - INFLUXDB_PORT
      - INFLUXDB_ORG
      - INFLUXDB_BUCKET_DATA_PUBLIC
      - INFLUXDB_BUCKET_DATA_PRIVATE
      - INFLUXDB_TOKEN
      - DROPBOX_TOKEN
      - WRANGLE_ENABLE_LOG
      - WRANGLE_REPROCESS_ALL_FILES
      - WRANGLE_DISABLE_EXTERNAL_SERVICES
    volumes:
      - ${SERVICE_DATA_DIR}:/asystem/runtime
      - ${SERVICE_DATA_DIR}/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    deploy:
      resources:
        limits:
          memory: 5G
