draft: false
acme:
  email_account: graham.gear@gmail.com
  staging: false
profiles:
  - name: namecheap_profile
    provider: cloudflare
    provider_options:
      auth_username: graham.gear@gmail.com
      auth_token: ${CLOUDFLARE_TOKEN}
certificates:
  - domains:
      - "*.janeandgraham.com"
      - janeandgraham.com
    profile: namecheap_profile
#    deploy_hook: python /home/user/local_deploy.py
