version: '3.7'
services:
  assistantrelay:
    container_name: assistantrelay
    image: assistantrelay:${SERVICE_VERSION_ABSOLUTE}
    init: true
    restart: ${SERVICE_RESTART}
    environment:
      - TZ=Australia/Perth
    ports:
      - ${ASSISTANTRELAY_PORT}:3000
    volumes:
      - ${SERVICE_DATA_DIR}/config.json:/home/assistant-relay/bin/config.json
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "100m"
    deploy:
      resources:
        limits:
          memory: 5G