x-common: &common
  image: zigbee2mqtt:${SERVICE_VERSION_ABSOLUTE}
  init: true
  user: root
  environment:
    - TZ=Australia/Perth
    - ZIGBEE2MQTT_SERVICE
    - ZIGBEE2MQTT_HTTP_PORT
    - ZIGBEE2MQTT_CONFIG_FRONTEND_PORT=$ZIGBEE2MQTT_HTTP_PORT
    - ZIGBEE2MQTT_CONFIG_FRONTEND_URL=http://$ZIGBEE2MQTT_SERVICE:$ZIGBEE2MQTT_HTTP_PORT
    - ZIGBEE2MQTT_CONFIG_MQTT_SERVER=mqtt://$VERNEMQ_SERVICE:$VERNEMQ_API_PORT
    - VERNEMQ_SERVICE
    - VERNEMQ_API_PORT
  logging:
    driver: "json-file"
    options:
      max-file: "5"
      max-size: "100m"
services:
  zigbee2mqtt:
    container_name: zigbee2mqtt
    <<: *common
    restart: ${SERVICE_RESTART}
    volumes:
      - ${SERVICE_DATA_DIR}:/app/data
      - /run/udev:/run/udev:ro
    ports:
      - ${ZIGBEE2MQTT_HTTP_PORT}:${ZIGBEE2MQTT_HTTP_PORT}
    healthcheck:
      test: /asystem/etc/healthcheck.sh
      interval: 2m
      timeout: 10s
      retries: 3
      start_period: 1m
      start_interval: 10s
    devices:
      - /dev/ttyUSBZB3DongleP:/dev/ttyACM0
    deploy:
      resources:
        limits:
          memory: 256M
  zigbee2mqtt_bootstrap:
    container_name: zigbee2mqtt_bootstrap
    <<: *common
    restart: 'no'
    entrypoint: /bin/sh
    command:
      - /asystem/etc/bootstrap.sh
    depends_on:
      - zigbee2mqtt
