version: '3.7'
x-common: &common
  image: zigbee2mqtt:${SERVICE_VERSION_ABSOLUTE}
  init: true
  user: root
  environment:
    - TZ=Australia/Perth
#    - DEBUG=zigbee-herdsman*
    - ZIGBEE2MQTT_IP
    - ZIGBEE2MQTT_HTTP_PORT
    - ZIGBEE2MQTT_CONFIG_FRONTEND_PORT=$ZIGBEE2MQTT_HTTP_PORT
    - ZIGBEE2MQTT_CONFIG_FRONTEND_URL=http://$ZIGBEE2MQTT_IP:$ZIGBEE2MQTT_HTTP_PORT
    - ZIGBEE2MQTT_CONFIG_MQTT_SERVER=mqtt://$VERNEMQ_IP:$VERNEMQ_PORT
    - VERNEMQ_IP
    - VERNEMQ_PORT
  logging:
    driver: "json-file"
    options:
      max-file: "5"
      max-size: "100m"
services:
  zigbee2mqtt:
    container_name: zigbee2mqtt
    <<: *common
    restart: ${SERVICE_RESTART}
    volumes:
      - ${SERVICE_DATA_DIR}:/app/data
      - /run/udev:/run/udev:ro
    ports:
      - ${ZIGBEE2MQTT_HTTP_PORT}:${ZIGBEE2MQTT_HTTP_PORT}
    devices:
      - /dev/ttyUSBConbeeII:/dev/ttyACM0
    deploy:
      resources:
        limits:
          memory: 512M
  zigbee2mqtt_bootstrap:
    container_name: zigbee2mqtt_bootstrap
    <<: *common
    restart: 'no'
    volumes:
      - ${SERVICE_DATA_DIR}:/app/data
    entrypoint: /bin/sh
    command:
      - /app/data/bootstrap.sh
    depends_on:
      - zigbee2mqtt
