services:
  wrangle:
    image: wrangle:${SERVICE_VERSION_ABSOLUTE}
    container_name: wrangle
    init: true
    restart: ${SERVICE_RESTART}
    environment:
      - TZ=Australia/Perth
      - WRANGLE_HOST
      - WRANGLE_HTTP_PORT
      - WRANGLE_DATABASE_HOST
      - WRANGLE_DATABASE_PORT
      - WRANGLE_DATABASE_USER
      - WRANGLE_DATABASE_PASSWORD
      - WRANGLE_POLL_PERIOD
      - WRANGLE_CACHE_DIR
      - WRANGLE_FILTER_PLUGINS
      - WRANGLE_REPO_SCOPE
      - WRANGLE_LOG
      - WRANGLE_FORCE_REPROCESSING
      - WRANGLE_FORCE_DOWNLOADS
      - WRANGLE_ENABLE_DRIVE_UPLOADS
      - WRANGLE_ENABLE_SHEET_UPLOADS
      - WRANGLE_ENABLE_DATABASE_UPLOADS
      - WRANGLE_DISABLE_DRIVE_DOWNLOADS
      - WRANGLE_DISABLE_SOURCE_DOWNLOADS
      - WRANGLE_DISABLE_DATABASE_DOWNLOADS
      - WRANGLE_DISABLE_SHEET_DOWNLOADS
      - WRANGLE_DISABLE_LOOP
      - WRANGLE_RUN_TIMEOUT_SECONDS
      - WRANGLE_NETWORK_TIMEOUT_SECONDS
      - WRANGLE_STACK_DUMP_FILE
      - REDBARK_TOKEN
    ports:
      - ${WRANGLE_HTTP_PORT}:${WRANGLE_HTTP_PORT}
    volumes:
      - ${SERVICE_DATA_DIR}:/asystem/mnt
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "100m"
    deploy:
      resources:
        limits:
          memory: 2G
