services:
  wrangle:
    image: wrangle:${SERVICE_VERSION_ABSOLUTE}
    container_name: wrangle
    init: true
    restart: ${SERVICE_RESTART}
    environment:
      - TZ=Australia/Perth
      - WRANGLE_HOST
      - WRANGLE_HTTP_PORT
      - POSTGRES_HOST
      - POSTGRES_API_PORT
      - REDBARK_TOKEN
    volumes:
      - ${SERVICE_DATA_DIR}:/asystem/mnt
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "100m"
    deploy:
      resources:
        limits:
          memory: 2G
