# TODO: Hook into build versioning system

APP_NAME = "asystem-anode"
APP_NAME_ESCAPED = "ASYSTEM_ANODE"
APP_VERSION = "10.000.0142-SNAPSHOT"
APP_VERSION_NUMERIC = -143

APP_MODEL_VERSION = "1001"
APP_MODEL_ENERGYFORECAST_INTERDAY_PROD_VERSION = "1006"
APP_MODEL_ENERGYFORECAST_INTRADAY_PROD_VERSION = "1003"
APP_MODEL_ENERGYFORECAST_INTERDAY_BUILD_VERSION = "1007"
APP_MODEL_ENERGYFORECAST_INTRADAY_BUILD_VERSION = "1003"
