# https://forums.plex.tv/t/plex-media-server/30447/630
services:
  plex:
    container_name: plex
    image: linuxserver/plex:1.40.4
    init: false
    restart: ${SERVICE_RESTART}
    environment:
      - TZ=Australia/Perth
      - PUID=0
      - PGID=0
      - VERSION=docker
      - PLEX_CLAIM
      - PLEX_TOKEN
    volumes:
      - ${SERVICE_DATA_DIR}/config:/config
      - ${SERVICE_DATA_DIR}/transcode:/transcode
      - /share:/share
    network_mode: host
    deploy:
      resources:
        limits:
          memory: 5G