# https://hub.docker.com/r/linuxserver/plex/tags
version: '3.7'
services:
  plex:
    container_name: plex
    image: linuxserver/plex:1.32.8
    init: false
    restart: ${SERVICE_RESTART}
    environment:
      - TZ=Australia/Perth
      - PUID=0
      - PGID=0
      - VERSION=docker
      - PLEX_CLAIM=${PLEX_CLAIM}
    volumes:
      - ${SERVICE_DATA_DIR}/config:/config
      - ${SERVICE_DATA_DIR}/transcode:/transcode
      - /data/media:/data/media
    network_mode: host
    deploy:
      resources:
        limits:
          memory: 5G