# https://github.com/linuxserver/docker-plex/tags
version: '3.7'
services:
  plex:
    container_name: plex
    image: plexinc/pms-docker:1.32.3.7192-7aa441827
    init: true
    restart: ${SERVICE_RESTART}
    environment:
      - TZ=Australia/Perth
      - PLEX_CLAIM=${PLEX_CLAIM}
    volumes:
      - ${SERVICE_DATA_DIR}/config:/config
      - ${SERVICE_DATA_DIR}/transcode:/transcode
      - /data/media/series:/media/series
      - /data/media/movies:/media/movies
    network_mode: host
    deploy:
      resources:
        limits:
          memory: 5G