x-common: &common
  image: grafana:${SERVICE_VERSION_ABSOLUTE}
  init: true
  user: root
  environment:
    - TZ=Australia/Perth
    - GF_SECURITY_ADMIN_USER=${GRAFANA_USER}
    - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_TOKEN}
    - GF_SERVER_HTTP_PORT=${GRAFANA_HTTP_PORT}
    - GF_SERVER_DOMAIN=${GRAFANA_DOMAIN}
    - GF_SERVER_ROOT_URL=${GRAFANA_DOMAIN_URL}
    - GF_USERS_ALLOW_SIGN_UP=false
    - GF_USERS_ALLOW_ORG_CREATE=false
    - GF_USERS_DEFAULT_TIMEZONE=browser
    - GF_AUTH_LOGIN_MAXIMUM_INACTIVE_LIFETIME_DURATION=90d
    - GF_AUTH_LOGIN_MAXIMUM_LIFETIME_DURATION=365d
    - GF_LOG_LEVEL=warn
    - GF_PATHS_PROVISIONING=/asystem/mnt/dashboards/config
    - GF_RECORDING_RULES_ENABLED=false
    - GF_ANALYTICS_REPORTING_ENABLED=false
    - GF_ANALYTICS_CHECK_FOR_UPDATES=false
    - GRAFANA_SERVICE
    - GRAFANA_HTTP_PORT
    - GRAFANA_URL
    - GRAFANA_DOMAIN
    - GRAFANA_DOMAIN_URL
    - GRAFANA_USER
    - GRAFANA_TOKEN
    - INFLUXDB3_SERVICE
    - INFLUXDB3_API_PORT
    - INFLUXDB3_DATABASE_HOME
    - INFLUXDB3_TOKEN_HOME
    - POSTGRES_SERVICE
    - POSTGRES_API_PORT
    - POSTGRES_DATABASE_WRANGLE
    - POSTGRES_USER_WRANGLE
    - POSTGRES_KEY_WRANGLE
  volumes:
    - ${SERVICE_DATA_DIR}:/asystem/mnt
  logging:
    driver: "json-file"
    options:
      max-file: "5"
      max-size: "100m"
services:
  grafana:
    container_name: grafana
    <<: *common
    restart: ${SERVICE_RESTART}
    ports:
      - ${GRAFANA_HTTP_PORT}:${GRAFANA_HTTP_PORT}
    healthcheck:
      test: /asystem/etc/checkhealthy.sh
      interval: 2m
      timeout: 30s
      retries: 3
      start_period: 1m
      start_interval: 10s
    deploy:
      resources:
        limits:
          memory: 2G
  grafana_bootstrap:
    container_name: grafana_bootstrap
    <<: *common
    restart: 'no'
    entrypoint: bash
    command: /asystem/etc/bootstrap.sh
    depends_on:
      - grafana
