services:
  sabnzbd:
    # https://sabnzbd.org/downloads#
    image: linuxserver/sabnzbd:4.4.1
    container_name: sabnzbd
    init: false
    restart: ${SERVICE_RESTART}
    environment:
      - TZ=Australia/Perth
      - PUID=0
      - PGID=0
      - SABNZBD_SERVICE_PROD
      - SABNZBD_HTTP_PORT
      - SABNZBD_API_KEY
      - SABNZBD_NZB_KEY
    volumes:
      - ${SERVICE_DATA_DIR}:/config
      - ${SABNZBD_SHARE_DIR}/enqueued:/downloads/enqueued
      - ${SABNZBD_SHARE_DIR}/finished:/downloads/finished
      - ${SABNZBD_SHARE_DIR}/staging:/downloads/staging
    ports:
      - ${SABNZBD_HTTP_PORT}:8080
    healthcheck:
      test: 'if STATUS="$(curl -sf --connect-timeout 2 --max-time 2 "http://${SABNZBD_SERVICE_PROD}:${SABNZBD_HTTP_PORT}/sabnzbd/api?output=json&apikey=${SABNZBD_API_KEY}&mode=status&skip_dashboard=0")" && [ "$(jq -er ".status.paused" <<<"${STATUS}")" == "false" ] && [ "$(jq -er "[.status.servers[].serveractiveconn] | add" <<<"${STATUS}")" -gt 0 ]; then exit 0; else exit 1; fi'
      interval: 2m
      timeout: 10s
      retries: 3
      start_period: 30s
      start_interval: 10s
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "100m"
    deploy:
      resources:
        limits:
          memory: 2G