# https://hub.docker.com/r/linuxserver/sabnzbd/tags
version: '3.7'
services:
  sabnzbd:
    container_name: sabnzbd
    image: linuxserver/sabnzbd:4.2.2-ls148
    init: false
    restart: ${SERVICE_RESTART}
    environment:
      - TZ=Australia/Perth
      - PUID=1000
      - PGID=100
    volumes:
      - ${SERVICE_DATA_DIR}:/config
      - /share/3/tmp/usenet/enqueued:/downloads/enqueued
      - /share/3/tmp/usenet/finished:/downloads/finished
      - /share/3/tmp/usenet/incomplete:/downloads/incomplete
    ports:
      - ${SABNZBD_HTTP_PORT}:8080
    deploy:
      resources:
        limits:
          memory: 5G