# https://hub.docker.com/r/linuxserver/sabnzbd/tags
version: '3.7'
services:
  sabnzbd:
    container_name: sabnzbd
    image: linuxserver/sabnzbd:4.2.2-ls148
    init: false
    restart: ${SERVICE_RESTART}
    environment:
      - TZ=Australia/Perth
      - PUID=0
      - PGID=0
    volumes:
      - ${SERVICE_DATA_DIR}:/config
      - ${SABNZBD_SHARE_DIR}/enqueued:/downloads/enqueued
      - ${SABNZBD_SHARE_DIR}/finished:/downloads/finished
      - ${SABNZBD_SHARE_DIR}/staging:/downloads/staging
    ports:
      - ${SABNZBD_HTTP_PORT}:8080
    deploy:
      resources:
        limits:
          memory: 5G