#######################################################################################
default_config:
#######################################################################################
homeassistant:
  name: 'Home'
  latitude: -31.918381
  longitude: 116.079391
  elevation: 246
  unit_system: 'metric'
  currency: 'AUD'
  country: 'AU'
  internal_url: !env_var HOMEASSISTANT_INTERNAL_URL
  external_url: !env_var HOMEASSISTANT_EXTERNAL_URL
  customize_domain:
    fan:
      assumed_state: false
    light:
      assumed_state: false
    switch:
      assumed_state: false
  customize: !include customise.yaml
  packages: !include_dir_named custom_packages
#######################################################################################
#######################################################################################
http:
  server_host: '0.0.0.0'
  server_port: !env_var HOMEASSISTANT_HTTP_PORT


  # TODO: Disable IP banning until I can find out where the rogue logins are coming from
  ip_ban_enabled: false
  #  ip_ban_enabled: true
  #  login_attempts_threshold: 3


  use_x_frame_options: true
  use_x_forwarded_for: true
  trusted_proxies:
    - '127.0.0.1'
    - '10.0.0.0/16'
    - '192.168.0.0/16'
  cors_allowed_origins:
    - 'https://home.janeandgraham.com'
    - 'https://homeassistant.janeandgraham.com'
#######################################################################################
tts:
  - platform: 'google_translate'
#######################################################################################
recorder:
  db_url: !env_var HOMEASSISTANT_DB
  commit_interval: 120
  purge_keep_days: 7
  auto_purge: true
influxdb:
  api_version: 2
  ssl: false
  host: !env_var INFLUXDB_SERVICE
  port: !env_var INFLUXDB_HTTP_PORT
  token: !env_var INFLUXDB_TOKEN
  organization: !env_var INFLUXDB_ORG
  bucket: !env_var INFLUXDB_BUCKET_HOME_PRIVATE
  precision: 's'
  measurement_attr: 'domain__device_class'
  default_measurement: 'sensor'
  tags:
    source: 'hass'
    version: !env_var SERVICE_VERSION_COMPACT
  tags_attributes:
    - 'state_class'
    - 'friendly_name'
    - 'unit_of_measurement'
  exclude:
    domains:
      - 'zone'
      - 'scene'
      - 'select'
    entity_globs:
      - '*_bass'
      - '*_treble'
      - '*_sim_*'
      - '*_microphone_level'
      - 'adaptive_lighting_*'
  ignore_attributes: !include influxdb-ignores.yaml
  #####################################################################################
mqtt:
# The UI is now used to configure MQTT, perhaps return with a version 2022.2.9-
#  broker: !env_var VERNEMQ_SERVICE
#  port: !env_var VERNEMQ_PORT
#  client_id: 'homeassistant'
#  discovery: true
#  discovery_prefix: 'homeassistant'
#  birth_message:
#    topic: 'homeassistant/status'
#    payload: 'online'
#    qos: 2
#    retain: true
#  will_message:
#    topic: 'homeassistant/status'
#    payload: 'offline'
#    qos: 2
#    retain: true
#######################################################################################
google_assistant:
  project_id: 'home-assistant-31854'
  service_account: !include .google_service_account.json
  report_state: true
  expose_by_default: false
  entity_config: !include hass-entities.yaml
#######################################################################################
automation: !include automations.yaml
#######################################################################################
panel_custom: !include ui-panel-custom.yaml
#######################################################################################
lovelace:
  mode: 'yaml'
  resources:
    - url: '/local/custom_ui/bom-weather-card.js?v=0.90a-HACKED'
      type: 'module'
    - url: '/local/custom_ui/layout-card/layout-card.js?v=2.4.4'
      type: 'module'
    - url: '/local/custom_ui/bom-radar-card/bom-radar-card.js?v=v3.0.3'
      type: 'module'
    - url: '/local/custom_ui/apexcharts-card/apexcharts-card.js?v=v2.0.4'
      type: 'module'
    - url: '/local/custom_ui/mini-graph-card/mini-graph-card-bundle.js?v=v0.11.0'
      type: 'module'
  dashboards:
    lovelace-generated:
      mode: 'yaml'
      filename: 'notexist.yaml'
      title: 'Generated'
      icon: 'mdi:tools'
      show_in_sidebar: true
      require_admin: true
#######################################################################################
logger:
  default: warn # critical/fatal/error/warning/warn/info/debug/notset
  logs:
    ###################################################################################
    homeassistant.components.recorder.migration: info
    homeassistant.components.system_log.external: info
    ###################################################################################
    homeassistant.core: warn
    ###################################################################################
    homeassistant.loader: error

    # TODO: Disable warnings introduced in 2023.8.1 until zigbee2mqtt has been updated
    homeassistant.components.mqtt.mixins: error

    homeassistant.components.integration.sensor: error
    homeassistant.components.compensation.sensor: error
    homeassistant.components.sonos: error
    homeassistant.config_entries: error
    homeassistant.components.sensor: error
    custom_components.tplink: error
    custom_components.average.sensor: error
    custom_components.powercalc.sensors.group: error
    ###################################################################################
    homeassistant.components.websocket_api.http.connection: fatal
    ###################################################################################
    #google_assistant: debug
    #homeassistant.components.google_assistant: debug
    #homeassistant.components.google_assistant.http: debug
    #homeassistant.components.google_assistant.trait: debug
    #homeassistant.components.google_assistant.helpers: debug
    #homeassistant.components.google_assistant.smart_home: debug
    #homeassistant.components.google_assistant.report_state: debug
    #homeassistant.components.mqtt: info
    #homeassistant.components.webhook: debug
    #custom_components.powercalc: info
    #custom_components.adaptive_lighting: info
    #custom_components.bureau_of_meteorology: info
  #####################################################################################
