#######################################################################################
# WARNING: This file is written to by the build process, any manual edits will be lost!
#######################################################################################
sensor.compensation_sensor_roof_temperature:
  name: Roof Temperature
  aliases: ['Temperature']
  room: Roof
sensor.compensation_sensor_ada_temperature:
  name: Ada Temperature
  aliases: ['Adas Temperature', 'Temperature', 's Temperature']
  room: Ada
sensor.compensation_sensor_edwin_temperature:
  name: Edwin Temperature
  aliases: ['Edwins Temperature', 'Temperature', 's Temperature']
  room: Edwin
sensor.compensation_sensor_office_office_office_lounge_temperature:
  name: Lounge Temperature
  aliases: ['Temperature']
  room: Lounge
sensor.compensation_sensor_parents_temperature:
  name: Parents Temperature
  aliases: ['Temperature']
  room: Parents
sensor.compensation_sensor_office_temperature:
  name: Office Temperature
  aliases: ['Temperature']
  room: Office
sensor.compensation_sensor_kitchen_temperature:
  name: Kitchen Temperature
  aliases: ['Temperature']
  room: Kitchen
sensor.compensation_sensor_office_office_office_pantry_temperature:
  name: Pantry Temperature
  aliases: ['Temperature']
  room: Pantry
sensor.compensation_sensor_office_office_office_dining_temperature:
  name: Dining Temperature
  aliases: ['Temperature']
  room: Dining
sensor.compensation_sensor_laundry_temperature:
  name: Laundry Temperature
  aliases: ['Temperature']
  room: Laundry
sensor.compensation_sensor_wardrobe_temperature:
  name: Wardrobe Temperature
  aliases: ['Temperature']
  room: Wardrobe
sensor.compensation_sensor_utility_temperature:
  name: Rack Temperature
  aliases: ['Temperature']
  room: Rack
sensor.compensation_sensor_deck_festoons_plug_temperature:
  name: Ceiling Temperature
  aliases: ['Temperature']
  room: Ceiling
sensor.compensation_sensor_office_office_office_basement_temperature:
  name: Basement Temperature
  aliases: ['Temperature']
  room: Basement
input_boolean.home_security:
  name: Home Secure
  aliases: ['Home Secure Mode', 'Secure', 'Secure Mode']
  room: Abode
input_boolean.home_movie:
  name: Home Movie
  aliases: ['Home Movie Mode', 'Movie', 'Movie Mode']
  room: Abode
input_boolean.home_sleep:
  name: Home Sleep
  aliases: ['Home Sleep Mode', 'Sleep', 'Sleep Mode']
  room: Abode
input_boolean.home_reset:
  name: Home Reset
  aliases: ['Home Reset Mode', 'Reset', 'Reset Mode']
  room: Abode
fan.ada_fan:
  name: Ada Fan
  aliases: ['Adas Fan', 'Fan', 's Fan']
  room: Ada
fan.edwin_fan:
  name: Edwin Fan
  aliases: ['Edwins Fan', 'Fan', 's Fan']
  room: Edwin
fan.parents_fan:
  name: Parents Fan
  aliases: ['Fan']
  room: Parents
fan.kitchen_fan_plug:
  name: Kitchen Fan
  aliases: ['Fan']
  room: Kitchen
fan.lounge_fan:
  name: Lounge Fan
  aliases: ['Fan']
  room: Lounge
fan.deck_fan:
  name: Deck Fans
  aliases: ['Deck Fan', 'Fans', 'Fan']
  room: Deck
fan.dining_air_purifier:
  name: Dining Air Purifier
  aliases: ['Air Purifier']
  room: Zombie
fan.lounge_air_purifier:
  name: Lounge Air Purifier
  aliases: ['Air Purifier']
  room: Zombie
fan.parents_air_purifier:
  name: Parents Air Purifier
  aliases: ['Air Purifier']
  room: Zombie
fan.kitchen_air_purifier:
  name: Kitchen Air Purifier
  aliases: ['Air Purifier']
  room: Zombie
light.ada_fan:
  name: Ada Main Light
  aliases: ['Adas Main Light', 'Main Light', 's Main Light']
  room: Ada
light.ada_lamp:
  name: Ada Lamp
  aliases: ['Lamp']
  room: Zombie
light.edwin_lamp:
  name: Edwin Lamp
  aliases: ['Lamp']
  room: Zombie
light.edwin_fan:
  name: Edwin Main Light
  aliases: ['Edwins Main Light', 'Main Light', 's Main Light']
  room: Edwin
light.edwin_night_light:
  name: Edwin Night Light
  aliases: ['Night Light']
  room: Zombie
light.hallway_main:
  name: Hallway Main Lights
  aliases: ['Hallway Main Light', 'Main Lights', 'Main Light']
  room: Hallway
light.hallway_sconces:
  name: Hallway Sconces
  aliases: ['Sconces']
  room: Hallway
light.dining_main:
  name: Dining Main Lights
  aliases: ['Dining Main Light', 'Main Lights', 'Main Light']
  room: Dining
light.lounge_main:
  name: Lounge Main Lights
  aliases: ['Lounge Main Light', 'Main Lights', 'Main Light']
  room: Lounge
light.lounge_fan:
  name: Lounge Fan Light
  aliases: ['Fan Light']
  room: Zombie
light.lounge_lamp:
  name: Lounge Lamp
  aliases: ['Lamp']
  room: Zombie
light.parents_main:
  name: Parents Main Lights
  aliases: ['Parents Main Light', 'Main Lights', 'Main Light']
  room: Parents
light.parents_jane_bedside:
  name: Parents Sconces
  aliases: ['Parents Bedside', 'Parents Jane', 'Parents Jane Bedside', 'Sconces', 'Bedside', 'Jane', 'Jane Bedside']
  room: Zombie
light.parents_graham_bedside:
  name: Parents Sconces
  aliases: ['Parents Bedside', 'Parents Graham', 'Parents Graham Bedside', 'Sconces', 'Bedside', 'Graham', 'Graham Bedside']
  room: Zombie
light.study_lamp:
  name: Study Lamp
  aliases: ['Lamp']
  room: Zombie
light.kitchen_main:
  name: Kitchen Main Lights
  aliases: ['Kitchen Main Light', 'Main Lights', 'Main Light']
  room: Kitchen
light.kitchen_bench_lights_plug:
  name: Kitchen Bench Light
  aliases: ['Kitchen Bench Lights', 'Kitchen Bench', 'Bench Light', 'Bench Lights', 'Bench']
  room: Kitchen
light.laundry_main:
  name: Laundry Main Light
  aliases: ['Main Light']
  room: Laundry
light.pantry_main:
  name: Pantry Main Light
  aliases: ['Main Light']
  room: Pantry
light.office_main:
  name: Office Main Light
  aliases: ['Main Light']
  room: Office
light.bathroom_main:
  name: Bathroom Main Light
  aliases: ['Main Light']
  room: Bathroom
light.bathroom_sconces:
  name: Bathroom Sconces
  aliases: ['Sconces']
  room: Bathroom
light.ensuite_main:
  name: Ensuite Main Light
  aliases: ['Main Light']
  room: Ensuite
light.ensuite_sconces:
  name: Ensuite Sconces
  aliases: ['Sconces']
  room: Ensuite
light.wardrobe_main:
  name: Wardrobe Main Light
  aliases: ['Main Light']
  room: Wardrobe
light.deck_festoons_plug:
  name: Deck Festoons
  aliases: ['Festoons']
  room: Deck
light.landing_festoons_plug:
  name: Landing Festoons
  aliases: ['Festoons']
  room: Landing
light.tree_spotlights:
  name: Tree Spotlights
  aliases: ['Spotlights']
  room: Tree
sensor.compensation_sensor_landing_festoons_plug_temperature:
  name: Ceiling Temperature
  aliases: ['Temperature']
  room: Ceiling
switch.bathroom_rails_plug:
  name: Bathroom Towel Rails
  aliases: ['Towel Rails']
  room: Bathroom
switch.ceiling_water_booster_plug:
  name: Ceiling Hot Water Booster
  aliases: ['Hot Water Booster']
  room: Ceiling
switch.garden_pool_filter_plug:
  name: Garden Pool Filter
  aliases: ['Pool Filter']
  room: Garden
sensor.compensation_sensor_rack_top_temperature:
  name: Rack Temperature
  aliases: ['Temperature']
  room: Rack
sensor.compensation_sensor_rack_bottom_temperature:
  name: Rack Temperature
  aliases: ['Temperature']
  room: Rack
input_boolean.lighting_reset_adaptive_lighting_ada_lamp:
  name: Ada Lamp Reset
  aliases: ['Lamp Reset']
  room: Zombie
input_boolean.lighting_reset_adaptive_lighting_edwin_lamp:
  name: Edwin Lamp Reset
  aliases: ['Lamp Reset']
  room: Zombie
input_boolean.lighting_reset_adaptive_lighting_edwin_night_light:
  name: Edwin Night Light Reset
  aliases: ['Night Light Reset']
  room: Zombie
input_boolean.lighting_reset_adaptive_lighting_hallway_main:
  name: Hallway Main Reset
  aliases: ['Main Reset']
  room: Hallway
input_boolean.lighting_reset_adaptive_lighting_hallway_sconces:
  name: Hallway Sconces Reset
  aliases: ['Sconces Reset']
  room: Hallway
input_boolean.lighting_reset_adaptive_lighting_dining_main:
  name: Dining Main Reset
  aliases: ['Main Reset']
  room: Dining
input_boolean.lighting_reset_adaptive_lighting_lounge_main:
  name: Lounge Main Reset
  aliases: ['Main Reset']
  room: Lounge
input_boolean.lighting_reset_adaptive_lighting_lounge_lamp:
  name: Home Lamp Reset
  aliases: ['Lamp Reset']
  room: Zombie
input_boolean.lighting_reset_adaptive_lighting_parents_main:
  name: Parents Main Reset
  aliases: ['Main Reset']
  room: Parents
input_boolean.lighting_reset_adaptive_lighting_parents_jane_bedside:
  name: Parents Jane Bedside Reset
  aliases: ['Jane Bedside Reset']
  room: Parents
input_boolean.lighting_reset_adaptive_lighting_parents_graham_bedside:
  name: Parents Graham Bedside Reset
  aliases: ['Graham Bedside Reset']
  room: Parents
input_boolean.lighting_reset_adaptive_lighting_study_lamp:
  name: Study Lamp Reset
  aliases: ['Lamp Reset']
  room: Study
input_boolean.lighting_reset_adaptive_lighting_kitchen_main:
  name: Kitchen Main Reset
  aliases: ['Main Reset']
  room: Kitchen
input_boolean.lighting_reset_adaptive_lighting_laundry_main:
  name: Laundry Main Reset
  aliases: ['Main Reset']
  room: Laundry
input_boolean.lighting_reset_adaptive_lighting_pantry_main:
  name: Pantry Main Reset
  aliases: ['Main Reset']
  room: Pantry
input_boolean.lighting_reset_adaptive_lighting_office_main:
  name: Office Main Reset
  aliases: ['Main Reset']
  room: Office
input_boolean.lighting_reset_adaptive_lighting_bathroom_main:
  name: Bathroom Main Reset
  aliases: ['Main Reset']
  room: Bathroom
input_boolean.lighting_reset_adaptive_lighting_bathroom_sconces:
  name: Bathroom Sconces Reset
  aliases: ['Sconces Reset']
  room: Bathroom
input_boolean.lighting_reset_adaptive_lighting_ensuite_main:
  name: Ensuite Main Reset
  aliases: ['Main Reset']
  room: Ensuite
input_boolean.lighting_reset_adaptive_lighting_ensuite_sconces:
  name: Ensuite Sconces Reset
  aliases: ['Sconces Reset']
  room: Ensuite
input_boolean.lighting_reset_adaptive_lighting_wardrobe_main:
  name: Wardrobe Main Reset
  aliases: ['Main Reset']
  room: Wardrobe
#######################################################################################
