#######################################################################################
title: Home
views:
  #######################################################################################
  - title: Weather
    path: default_view
    type: custom:vertical-layout
    layout:
      width: 300
      max_cols: 10
    cards: !include ui-lovelace/weather.yaml
  #######################################################################################
  - title: Conditions
    path: conditions
    type: custom:vertical-layout
    layout:
      width: 300
      max_cols: 10
    cards: !include ui-lovelace/conditions.yaml
  #######################################################################################
  - title: Water
    path: water
    type: custom:vertical-layout
    layout:
      width: 300
      max_cols: 10
    cards: !include ui-lovelace/water.yaml
  #######################################################################################
  - title: Control
    path: control
    type: custom:vertical-layout
    layout:
      width: 300
      max_cols: 10
    cards: !include ui-lovelace/control.yaml
  #######################################################################################
  - title: Media
    path: media
    type: custom:vertical-layout
    layout:
      width: 300
      max_cols: 10
    cards: !include ui-lovelace/media.yaml
  #######################################################################################
  - title: Security
    path: security
    type: custom:vertical-layout
    layout:
      width: 300
      max_cols: 10
    cards: !include ui-lovelace/security.yaml
  #######################################################################################
  - title: Electricity
    path: electricity
    type: custom:vertical-layout
    layout:
      width: 300
      max_cols: 10
    cards: !include ui-lovelace/electricity.yaml
  #######################################################################################
  - title: Diagnostics
    path: diagnostics
    type: custom:vertical-layout
    layout:
      width: 300
      max_cols: 10
    cards: !include ui-lovelace/diagnostics.yaml
  #######################################################################################
