#######################################################################################
# WARNING: This file is written to by the build process, any manual edits will be lost!
################################################################################
- type: entities
  title: Default Adaptive Lighting
  show_header_toggle: false
  entities:
    - entity: switch.adaptive_lighting_default
      name: Status
    - entity: switch.adaptive_lighting_sleep_mode_default
      name: Sleep
################################################################################
- type: entities
  title: Bedroom Adaptive Lighting
  show_header_toggle: false
  entities:
    - entity: switch.adaptive_lighting_bedroom
      name: Status
    - entity: switch.adaptive_lighting_sleep_mode_bedroom
      name: Sleep
################################################################################
- type: entities
  title: Night Light Adaptive Lighting
  show_header_toggle: false
  entities:
    - entity: switch.adaptive_lighting_night_light
      name: Status
    - entity: switch.adaptive_lighting_sleep_mode_night_light
      name: Sleep
################################################################################
- type: custom:layout-break
################################################################################
- type: entities
  title: Reset Adaptive Lighting
  show_header_toggle: false
  entities:
    - entity: input_boolean.lighting_reset_adaptive_lighting_ada_lamp
      name: Ada Lamp
      icon: mdi:lightbulb-group
    - entity: input_boolean.lighting_reset_adaptive_lighting_edwin_lamp
      name: Edwin Lamp
      icon: mdi:lightbulb-group
    - entity: input_boolean.lighting_reset_adaptive_lighting_edwin_night_light
      name: Edwin Night Light
      icon: mdi:lightbulb-group
    - entity: input_boolean.lighting_reset_adaptive_lighting_hallway_main
      name: Hallway Main
      icon: mdi:lightbulb-group
    - entity: input_boolean.lighting_reset_adaptive_lighting_dining_main
      name: Dining Main
      icon: mdi:lightbulb-group
    - entity: input_boolean.lighting_reset_adaptive_lighting_lounge_main
      name: Lounge Main
      icon: mdi:lightbulb-group
    - entity: input_boolean.lighting_reset_adaptive_lighting_lounge_lamp
      name: Lounge Lamp
      icon: mdi:lightbulb-group
    - entity: input_boolean.lighting_reset_adaptive_lighting_parents_main
      name: Parents Main
      icon: mdi:lightbulb-group
    - entity: input_boolean.lighting_reset_adaptive_lighting_kitchen_main
      name: Kitchen Main
      icon: mdi:lightbulb-group
    - entity: input_boolean.lighting_reset_adaptive_lighting_laundry_main
      name: Laundry Main
      icon: mdi:lightbulb-group
    - entity: input_boolean.lighting_reset_adaptive_lighting_pantry_main
      name: Pantry Main
      icon: mdi:lightbulb-group
    - entity: input_boolean.lighting_reset_adaptive_lighting_office_main
      name: Office Main
      icon: mdi:lightbulb-group
    - entity: input_boolean.lighting_reset_adaptive_lighting_bathroom_main
      name: Bathroom Main
      icon: mdi:lightbulb-group
    - entity: input_boolean.lighting_reset_adaptive_lighting_ensuite_main
      name: Ensuite Main
      icon: mdi:lightbulb-group
    - entity: input_boolean.lighting_reset_adaptive_lighting_wardrobe_main
      name: Wardrobe Main
      icon: mdi:lightbulb-group
################################################################################
- type: custom:layout-break
################################################################################
- type: entities
  title: Power Plugs
  show_header_toggle: false
  entities:
    - entity: switch.lounge_tv_outlet
      name: Lounge TV
      icon: mdi:television
    - entity: switch.various_adhoc_outlet
      name: Adhoc Outlet
      icon: mdi:power-plug-outline
    - entity: switch.study_outlet
      name: Study Outlet
      icon: mdi:power-plug-outline
    - entity: switch.office_outlet
      name: Office Outlet
      icon: mdi:power-plug-outline
    - entity: switch.kitchen_dish_washer
      name: Dish Washer
      icon: mdi:dishwasher
    - entity: switch.laundry_clothes_dryer
      name: Clothes Dryer
      icon: mdi:tumble-dryer
    - entity: switch.laundry_washing_machine
      name: Washing Machine
      icon: mdi:washing-machine
    - entity: switch.kitchen_fridge
      name: Kitchen Fridge
      icon: mdi:fridge-outline
    - entity: switch.deck_freezer
      name: Deck Freezer
      icon: mdi:fridge-top
    - entity: switch.study_battery_charger
      name: Battery Charger
      icon: mdi:battery-charging-30
    - entity: switch.laundry_vacuum_charger
      name: Vacuum Charger
      icon: mdi:battery-charging-30
    - entity: switch.deck_fans_outlet
      name: Deck Fans Outlet
      icon: mdi:power-plug-outline
    - entity: switch.kitchen_fan_outlet
      name: Kitchen Fan Outlet
      icon: mdi:power-plug-outline
    - entity: switch.edwin_wardrobe_outlet
      name: Edwin Wardobe Outlet
      icon: mdi:power-plug-outline
    - entity: switch.rack_fans
      name: Rack Fans
      icon: mdi:server-remove
    - entity: switch.rack_outlet
      name: Server Rack
      icon: mdi:server
    - entity: switch.roof_network_switch
      name: Network Switch
      icon: mdi:server-network
    - entity: switch.rack_modem
      name: Internet Modem
      icon: mdi:router-wireless
################################################################################
- type: custom:layout-break
################################################################################
- type: entities
  title: Battery Charge
  entities:
    - entity: sensor.front_door_sensor_battery
      name: Yale Front Door Lock
    - entity: sensor.back_door_sensor_battery
      name: Yale Back Door Lock
    - entity: sensor.front_door_sensor_battery
      name: Sonoff Front Door Sensor
    - entity: sensor.back_door_sensor_battery
      name: Sonoff Back Door Sensor
    - entity: sensor.bertram_2_office_pantry_battery_percent
      name: Netatmo Pantry
    - entity: sensor.bertram_2_office_lounge_battery_percent
      name: Netatmo Lounge
    - entity: sensor.bertram_2_office_dining_battery_percent
      name: Netatmo Dining
    - entity: sensor.bertram_2_office_basement_battery_percent
      name: Netatmo Basement
    - entity: sensor.home_cube_remote_battery
      name: Xiaomi Cube Remote
    - entity: sensor.parents_speaker_battery
      name: Sonos Parents
    - entity: sensor.kitchen_home_battery
      name: Sonos Kitchen
    - entity: sensor.weatherstation_console_battery_percent
      name: Davis Console
################################################################################
- type: custom:layout-break
################################################################################
- type: entities
  title: Device Maintenance
  entities:
    - entity: button.synchronize_devices
      name: Google Device Sync
################################################################################
- type: entities
  title: Telemetry
  entities:
    - entity: sensor.weatherstation_coms_signal_quality
      name: Davis Signal Quality
      icon: mdi:signal
################################################################################
