#######################################################################################
# WARNING: This file is written to by the build process, any manual edits will be lost!
################################################################################
- type: entities
  title: Front Door
  entities:
    - entity: input_boolean.front_door_lock_security
      name: Secure
      icon: mdi:home-lock
    - entity: lock.front_door_lock
      name: Action
    - entity: binary_sensor.template_front_door_sensor_contact_last
      name: Status
################################################################################
- type: entities
  title: Back Door
  entities:
    - entity: input_boolean.back_door_lock_security
      name: Secure
      icon: mdi:home-lock
    - entity: lock.back_door_lock
      name: Action
    - entity: binary_sensor.template_back_door_sensor_contact_last
      name: Status
################################################################################
- type: custom:layout-break
################################################################################
- type: entities
  title: Ada's Room
  entities:
    - entity: binary_sensor.uvc_ada_motion
      name: Motion
################################################################################
- type: picture-entity
  entity: camera.uvc_ada_medium
  show_name: false
  show_state: false
  camera_view: live
################################################################################
- type: custom:layout-break
################################################################################
- type: entities
  title: Edwin's Room
  entities:
    - entity: binary_sensor.uvc_edwin_motion
      name: Motion
################################################################################
- type: picture-entity
  entity: camera.uvc_edwin_medium
  show_name: false
  show_state: false
  camera_view: live
################################################################################
- type: custom:layout-break
################################################################################
- type: entities
  title: House Occupancy
  entities:
    - entity: binary_sensor.ada_fan_occupancy
      name: Ada
    - entity: binary_sensor.edwin_fan_occupancy
      name: Edwin
    - entity: binary_sensor.parents_fan_occupancy
      name: Parents
    - entity: binary_sensor.lounge_fan_occupancy
      name: Lounge
    - entity: binary_sensor.deck_east_fan_occupancy
      name: Deck East
    - entity: binary_sensor.deck_west_fan_occupancy
      name: Deck West
################################################################################
