#######################################################################################
# WARNING: This file is written to by the build process, any manual edits will be lost!
################################################################################
- type: entities
  title: Door Locks
  entities:
    - entity: lock.front_door_lock
      name: Front Door Lock
    - entity: lock.back_door_lock
      name: Back Door Lock
################################################################################
- type: picture-entity
  entity: camera.uvc_ada_medium
  camera_view: live
################################################################################
- type: entities
  title: Ada Motion
  entities:
    - entity: binary_sensor.uvc_ada_motion
      name: Ada
################################################################################
- type: custom:layout-break
################################################################################
- type: picture-entity
  entity: camera.uvc_edwin_medium
  camera_view: live
################################################################################
- type: entities
  title: Edwin Motion
  entities:
    - entity: binary_sensor.uvc_edwin_motion
      name: Edwin
################################################################################
- type: custom:layout-break
################################################################################
- type: entities
  title: Fan Motion
  entities:
    - entity: binary_sensor.ada_fan_occupancy
      name: Ada
    - entity: binary_sensor.edwin_fan_occupancy
      name: Edwin
    - entity: binary_sensor.parents_fan_occupancy
      name: Parents
    - entity: binary_sensor.lounge_fan_occupancy
      name: Lounge
    - entity: binary_sensor.deck_east_fan_occupancy
      name: Deck East
    - entity: binary_sensor.deck_west_fan_occupancy
      name: Deck West
################################################################################
