#######################################################################################
# WARNING: This file is written to by the build process, any manual edits will be lost!
################################################################################
- type: picture-entity
  entity: camera.uvc_ada_medium
  camera_view: live
################################################################################
- type: entities
  title: Ada Motion
  entities:
    - entity: binary_sensor.uvc_ada_motion
      name: Ada
################################################################################
- type: custom:layout-break
################################################################################
- type: picture-entity
  entity: camera.uvc_edwin_medium
  camera_view: live
################################################################################
- type: entities
  title: Edwin Motion
  entities:
    - entity: binary_sensor.uvc_edwin_motion
      name: Edwin
################################################################################
- type: custom:layout-break
################################################################################
- type: entities
  title: Fan Motion
  entities:
    - entity: binary_sensor.ada_fan_light_motion
      name: Ada
    - entity: binary_sensor.edwin_fan_light_motion
      name: Edwin
    - entity: binary_sensor.parents_fan_light_motion
      name: Parents
    - entity: binary_sensor.lounge_fan_light_motion
      name: Lounge
    - entity: binary_sensor.deck_east_fan_light_motion
      name: Deck East
    - entity: binary_sensor.deck_west_fan_light_motion
      name: Deck West
################################################################################
