version: '3.7'
services:
  anode:
    container_name: anode
    image: anode:${VERSION}
    init: true
    restart: ${RESTART}
    environment:
      - TZ=Australia/Perth
      - HOST_IP
      - ANODE_HOST
      - ANODE_PORT
      - VERNEMQ_HOST
      - VERNEMQ_PORT
      - INFLUXDB_PORT
      - INFLUXDB_HOST
    ports:
      - 8091:8091
    volumes:
      - ${DATA_DIR}:/etc/anode
    deploy:
      resources:
        limits:
          memory: 5G