version: '3.7'
services:
  anode:
    container_name: anode
    image: anode:${SERVICE_VERSION_ABSOLUTE}
    init: true
    restart: ${SERVICE_RESTART}
    environment:
      - TZ=Australia/Perth
      - ANODE_IP
      - ANODE_PORT
      - VERNEMQ_IP
      - VERNEMQ_PORT
      - INFLUXDB_IP
      - INFLUXDB_PORT
    ports:
      - 8091:8091
    volumes:
      - ${SERVICE_DATA_DIR}:/etc/anode
    deploy:
      resources:
        limits:
          memory: 5G