permit_join: true
advanced:
  channel: 11
mqtt:
  base_topic: zigbee
  server: 'mqtt://$VERNEMQ_IP:$VERNEMQ_PORT'
frontend:
  port: $ZIGBEE2MQTT_PORT
  url: 'http://$ZIGBEE2MQTT_IP:$ZIGBEE2MQTT_PORT'
homeassistant:
  discovery_topic: 'haas/entity/sensor/zigbee'
  status_topic: 'haas/entity/sensor/zigbee/status'
  legacy_entity_attributes: true
  legacy_triggers: true
serial:
  port: /dev/ttyACM0
