permit_join: false
advanced:
  log_level: debug
  channel: 11

# TODO: Doesnt seem to work?
#availability:
#  active:
#    timeout: 1
#  passive:
#    timeout: 1500

availability: true
experimental:
  availability_new: true

mqtt:
  base_topic: zigbee
  server: 'mqtt://$VERNEMQ_IP:$VERNEMQ_PORT'
frontend:
  port: $ZIGBEE2MQTT_PORT
  url: 'http://$ZIGBEE2MQTT_IP:$ZIGBEE2MQTT_PORT'
homeassistant:
  discovery_topic: 'haas/entity'
  status_topic: 'haas/status'
  legacy_entity_attributes: false
  legacy_triggers: true
serial:
  port: /dev/ttyACM0
device_options:
  retain: true
  qos: 1
  debounce: 0.5
  optimistic: false
devices: devices.yaml
groups: groups.yaml
