permit_join: true
advanced:
  channel: 11
availability:
  active:
    timeout: 1
  passive:
    timeout: 1500
mqtt:
  base_topic: zigbee
  server: 'mqtt://$VERNEMQ_IP:$VERNEMQ_PORT'
frontend:
  port: $ZIGBEE2MQTT_PORT
  url: 'http://$ZIGBEE2MQTT_IP:$ZIGBEE2MQTT_PORT'
homeassistant:
  discovery_topic: 'haas/entity'
  status_topic: 'haas/status'
  legacy_entity_attributes: false
  legacy_triggers: true
serial:
  port: /dev/ttyACM0
devices: devices.yaml
groups: groups.yaml
