permit_join: true
advanced:
  channel: 11
mqtt:
  base_topic: zigbee
  server: 'mqtt://$VERNEMQ_IP:$VERNEMQ_PORT'
frontend:
  port: $ZIGBEE2MQTT_PORT
  url: 'http://$ZIGBEE2MQTT_IP:$ZIGBEE2MQTT_PORT'
homeassistant:
  discovery_topic: 'haas/entity'
  status_topic: 'haas/status'
  legacy_entity_attributes: true
  legacy_triggers: true
serial:
  port: /dev/ttyACM0
devices:
  '0x9035eafffe404425':
    friendly_name: 'air_purifier'
    retain: true
    qos: 1
    homeassistant:
      expire_after: 30
