homeassistant: true
permit_join: true
mqtt:
  base_topic: zigbee
  server: 'mqtt://$VERNEMQ_IP:$VERNEMQ_PORT'
frontend:
  port: $ZIGBEE2MQTT_PORT
  url: 'http://$ZIGBEE2MQTT_IP:$ZIGBEE2MQTT_PORT'
serial:
  port: /dev/ttyACM0
