#######################################################################################
# WARNING: This file is written to by the build process, any manual edits will be lost!
#######################################################################################
'0x9035eafffe404425':
  friendly_name: 'Lounge Air Purifier'
  retain: true
  qos: 1
  debounce: 0.5
  homeassistant:
    expire_after: 3600
'0x00178801039f585a':
  friendly_name: 'Parents Main 1'
  retain: true
  qos: 1
  debounce: 0.5
'0x00178801039f69d1':
  friendly_name: 'Parents Main 2'
  retain: true
  qos: 1
  debounce: 0.5
'0x001788010432a064':
  friendly_name: 'Parents Main 3'
  retain: true
  qos: 1
  debounce: 0.5
'0x00158d0005d9d088':
  friendly_name: 'Home Cube Remote'
  retain: true
  qos: 1
  debounce: 0.5
  legacy: true
  homeassistant:
    expire_after: 3600
