# https://github.com/adferrand/dnsrobocert/releases
version: '3.7'
services:
  letsencrypt:
    container_name: letsencrypt
    image: adferrand/dnsrobocert:3.20.1
    init: true
    environment:
      - TZ=Australia/Perth
      - CLOUDFLARE_TOKEN
      - LETSENCRYPT_STAGING
    volumes:
      - ${SERVICE_DATA_DIR}/letsencrypt:/etc/letsencrypt
      - ${SERVICE_DATA_DIR}/dnsrobocert:/etc/dnsrobocert
    deploy:
      resources:
        limits:
          memory: 5G
